'use strict';
// CRM: painel inteligente, clientes 360 (RFM, previsão de recompra, produto favorito, comprados juntos),
// mais vendidos, estados/cidades/regiões (mapa do Brasil) e oportunidades com links de contato.
// Os marketplaces não repassam telefone/e-mail do comprador: o contato padrão é a conversa do pedido
// na própria plataforma (e o Bling); WhatsApp/e-mail aparecem quando cadastrados na ficha do cliente.
(()=>{
Object.assign(paths,{heart:'M12 21s-7-4.5-9.5-9A5.5 5.5 0 0 1 12 6a5.5 5.5 0 0 1 9.5 6c-2.5 4.5-9.5 9-9.5 9z',map:'M9 4 3 6v14l6-2 6 2 6-2V4l-6 2z M9 4v14 M15 6v14',target:'M12 21a9 9 0 1 1 0-18 9 9 0 0 1 0 18z M12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8z M12 12h.01',gift:'M4 11h16v10H4z M3 7h18v4H3z M12 7v14 M12 7s-1.5-4-4-4a2 2 0 0 0 0 4z M12 7s1.5-4 4-4a2 2 0 0 1 0 4z',
 whats:'M3 21l1.6-4.8A8.5 8.5 0 1 1 8 19.6z M9 9.5c.3 2.2 2.3 4.2 4.5 4.5l1.2-1.1 1.8.8-.4 1.6c-3.5.3-7.3-3.5-7-7l1.6-.4.8 1.8z',mail:'M3 6h18v12H3z M3 7l9 6 9-6',chat:'M4 5h16v11H9l-5 4z',ext:'M14 4h6v6 M20 4l-9 9 M18 14v6H4V6h6'});
const REG={AC:'Norte',AM:'Norte',AP:'Norte',PA:'Norte',RO:'Norte',RR:'Norte',TO:'Norte',AL:'Nordeste',BA:'Nordeste',CE:'Nordeste',MA:'Nordeste',PB:'Nordeste',PE:'Nordeste',PI:'Nordeste',RN:'Nordeste',SE:'Nordeste',DF:'Centro-Oeste',GO:'Centro-Oeste',MS:'Centro-Oeste',MT:'Centro-Oeste',ES:'Sudeste',MG:'Sudeste',RJ:'Sudeste',SP:'Sudeste',PR:'Sul',RS:'Sul',SC:'Sul'};
const GRADE={RR:[3,0],AP:[5,0],AM:[2,1],PA:[4,1],MA:[5,1],CE:[6,1],RN:[7,1],AC:[1,2],RO:[2,2],TO:[4,2],PI:[5,2],PB:[7,2],PE:[6,2],MT:[3,3],GO:[4,3],BA:[5,3],AL:[7,3],SE:[6,3],DF:[4,4],MG:[5,4],ES:[6,4],MS:[3,4],SP:[4,5],RJ:[5,5],PR:[3,6],SC:[4,6],RS:[3,7]};
const SEGS=['VIP','Recorrente','Novo','Em risco','Inativo'],SEGTOM={VIP:'info',Recorrente:'ok',Novo:'',['Em risco']:'warn',Inativo:'bad'};
const ESTAGIOS=['Novo','Contatado','Negociando','Recomprou','Fidelizado','Sem interesse'];
const ui={periodo:'12m',plat:'',rank:'receita',uf:'',acao:'previsao',busca:'',seg:'',ordem:'total',pag:0};
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const dias=d=>Math.round((new Date(hoje()+'T12:00:00')-new Date(d+'T12:00:00'))/864e5);
const addDias=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+Math.round(n));return x.toLocaleDateString('sv-SE')};
const dBR=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const nf=n=>Number(n||0).toLocaleString('pt-BR');
const pctf=n=>(Number.isFinite(n)?n:0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const ufDe=o=>String(o.state||o.customer?.state||'').toUpperCase().slice(0,2);
const cidadeDe=o=>String(o.customer?.city||'').trim();
const qtdItens=o=>(o.items||[]).reduce((a,i)=>a+(Number(i.qty)||0),0);
const chave=o=>{const c=o.customer;if(!c)return null;const d=String(c.doc||'').replace(/\D/g,'');if(d.length>=11)return 'DOC-'+d;if(c.id&&!/-(undefined|null|)$/.test(c.id))return String(c.id);if(c.name)return 'NOME-'+normalized(c.name).replace(/\s+/g,'-');return null};
const primeiroNome=n=>String(n||'').trim().split(/\s+/)[0].toLowerCase().replace(/^./,c=>c.toUpperCase());
function pedidos(){const h=hoje();let r=db.orders;if(ui.periodo==='mes')r=r.filter(o=>o.date.startsWith(month));else if(ui.periodo!=='tudo'){const n={'3m':90,'6m':182,'12m':365}[ui.periodo];const lim=addDias(h,-n);r=r.filter(o=>o.date>=lim&&o.date<=h)}return ui.plat?r.filter(o=>o.platform===ui.plat):r}

// ─────────────── Base de clientes (com RFM e previsão de recompra) ───────────────
let cache=null,cacheKey='';
function clientes(){const k=db.orders.length+'|'+(db.orders.at(-1)?.id||'')+'|'+Object.keys(db.crm||{}).length;if(cache&&cacheKey===k)return cache;const map=new Map();
 for(const o of db.orders){const key=chave(o);if(!key)continue;const c=map.get(key)||{key,nome:'',doc:'',cidade:'',uf:'',pedidos:[],total:0,itens:0,canais:{},prods:{},apelido:'',contatoBling:''};const s=o.customer||{};
  c.nome=c.nome||s.name||'';c.doc=c.doc||s.doc||'';c.cidade=c.cidade||s.city||'';c.uf=c.uf||ufDe(o);c.apelido=c.apelido||o.external?.buyer_nickname||'';c.contatoBling=c.contatoBling||(s.id&&!/^\d{12,}$/.test(String(s.id))?'':s.id)||'';
  c.pedidos.push(o);c.total+=o.gross;c.itens+=qtdItens(o);c.canais[o.platform]=(c.canais[o.platform]||0)+1;for(const it of o.items||[]){const t=it.title||it.sku||'?';c.prods[t]=(c.prods[t]||0)+(Number(it.qty)||1)}map.set(key,c)}
 const l=[...map.values()].map(c=>{c.pedidos.sort((a,b)=>a.date.localeCompare(b.date));const n=c.pedidos.length,prim=c.pedidos[0].date,ult=c.pedidos.at(-1).date;const intervalo=n>1?(new Date(ult)-new Date(prim))/864e5/(n-1):null;
  const fav=Object.entries(c.prods).sort((a,b)=>b[1]-a[1])[0]?.[0]||'',canal=Object.entries(c.canais).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';
  return {...c,total:round(c.total),n,ticket:round(c.total/n),primeira:prim,ultima:ult,recencia:dias(ult),intervalo:intervalo&&Math.max(1,Math.round(intervalo)),proxima:intervalo?addDias(ult,Math.max(7,intervalo)):null,fav,canal,ultimoPedido:c.pedidos.at(-1),crm:db.crm?.[c.key]||{}}});
 // RFM de 1 a 5: recência (mais recente = 5), frequência e valor (quintis).
 const quint=(arr,v,inv)=>{const i=arr.findIndex(x=>x>=v);const p=(i<0?arr.length:i)/Math.max(1,arr.length);const q=Math.min(5,Math.max(1,Math.ceil(p*5)||1));return inv?6-q:q};
 const rs=l.map(c=>c.recencia).sort((a,b)=>a-b),ms=l.map(c=>c.total).sort((a,b)=>a-b);
 for(const c of l){c.R=quint(rs,c.recencia,true);c.F=c.n>=6?5:c.n>=4?4:c.n>=3?3:c.n>=2?2:1;c.M=quint(ms,c.total,false);c.rfm=`${c.R}${c.F}${c.M}`;
  c.seg=c.recencia>180?'Inativo':c.recencia>90?'Em risco':c.n>=2&&c.M>=5?'VIP':c.n>=2?'Recorrente':'Novo';
  c.status=c.proxima?(c.proxima<hoje()?(dias(c.proxima)<=30?'Recompra atrasada':'Fora da janela'):(dias(c.proxima)>=-15?'Recompra próxima':'Aguardando')):(c.recencia>=25&&c.recencia<=60?'Janela 2ª compra':'')}
 cache=l;cacheKey=k;return l}
// Comprados juntos: pares de produtos no mesmo pedido.
function juntos(rows,lim=8){const m={};for(const o of rows){const t=[...new Set((o.items||[]).map(i=>i.title||i.sku).filter(Boolean))];for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++){const k=[t[i],t[j]].sort().join(' ⟷ ');m[k]=(m[k]||0)+1}}return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,lim)}
function sugestoes(c){const meus=new Set(Object.keys(c.prods)),co={};for(const o of db.orders){const t=(o.items||[]).map(i=>i.title||i.sku);if(!t.some(x=>meus.has(x)))continue;for(const x of t)if(!meus.has(x))co[x]=(co[x]||0)+1}return Object.entries(co).sort((a,b)=>b[1]-a[1]).slice(0,4)}

// ─────────────── Links de contato ───────────────
function links(c){const o=c.ultimoPedido,ext=o?.external||{},out=[],crm=c.crm||{};
 const tel=String(crm.telefone||'').replace(/\D/g,''),email=crm.email||'';
 const msg=encodeURIComponent(`Olá, ${primeiroNome(c.nome)}! Aqui é da Compra Store. Vimos que você comprou ${c.fav?`"${c.fav}"`:'com a gente'} — temos novidades e condições especiais para você. Posso te mostrar?`);
 if(tel)out.push(['whats',`https://wa.me/${tel.length<=11?'55':''}${tel}?text=${msg}`,'WhatsApp']);
 if(email)out.push(['mail',`mailto:${email}?subject=${encodeURIComponent('Uma novidade da Compra Store para você')}&body=${msg}`,'E-mail']);
 if(o?.platform==='Mercado Livre'){const id=(ext.ml_order_ids||[])[0]||ext.pack_id||o.id;out.push(['chat',`https://www.mercadolivre.com.br/vendas/${id}/detalhe`,'Conversa no Mercado Livre'])}
 if(o?.platform==='Shopee')out.push(['chat',`https://seller.shopee.com.br/portal/sale/order?search=${encodeURIComponent(o.id)}`,'Pedido na Shopee']);
 if(o?.platform==='Magalu')out.push(['chat','https://seller.magalu.com/','Pedido no Magalu']);
 if(ext.bling_id)out.push(['ext',`https://www.bling.com.br/vendas.php#edit/${ext.bling_id}`,'Pedido no Bling']);
 return out}
const botoesContato=(c,compacto)=>links(c).map(([ic,href,t])=>`<a class="cbtn ${ic}" href="${esc(href)}" target="_blank" rel="noopener" title="${esc(t)}" data-crm-contato="${esc(c.key)}">${icon(ic)}${compacto?'':`<span>${esc(t)}</span>`}</a>`).join('');

// ─────────────── Componentes visuais ───────────────
const filtros=(extra='')=>`<div class="crmbar"><div class="segtabs">${[['mes','Mês'],['3m','3 meses'],['6m','6 meses'],['12m','12 meses'],['tudo','Tudo']].map(([k,t])=>`<button class="${ui.periodo===k?'active':''}" data-crm-per="${k}">${t}</button>`).join('')}</div><select data-crm-plat aria-label="Canal"><option value="">Todos os canais</option>${['Mercado Livre','Shopee','Magalu'].map(p=>`<option ${ui.plat===p?'selected':''}>${p}</option>`).join('')}</select>${extra}</div>`;
const kpi=(l,v,s,tom='')=>`<div class="card kpi"><span class="kpil">${l}</span><span class="kpiv ${tom}">${v}</span><span class="kpis">${s}</span></div>`;
function barras(l,val,lab,cor='var(--accent)',fmt=money){const max=Math.max(1,...l.map(val));return l.map(x=>`<div class="hrow"><span class="hlab" title="${esc(lab(x))}">${esc(lab(x))}</span><span class="htrack"><i style="width:${val(x)/max*100}%;background:${cor}"></i></span><strong>${fmt(val(x))}</strong></div>`).join('')}
function porUF(rows){const m={};for(const o of rows){const uf=ufDe(o);if(!uf)continue;const s=m[uf]||(m[uf]={uf,pedidos:0,receita:0,itens:0,clientes:new Set()});s.pedidos++;s.receita+=o.gross;s.itens+=qtdItens(o);const k=chave(o);if(k)s.clientes.add(k)}return m}
function mapaBrasil(m,sel=''){const max=Math.max(1,...Object.values(m).map(s=>s.receita));
 return `<div class="brmap" role="img" aria-label="Mapa do Brasil por receita">${Object.entries(GRADE).map(([uf,[x,y]])=>{const s=m[uf],v=s?s.receita:0,a=v?0.15+0.85*Math.sqrt(v/max):0;return `<button class="uf ${sel===uf?'sel':''}" style="grid-column:${x+1};grid-row:${y+1};background:${v?`rgba(168,138,255,${a.toFixed(2)})`:'var(--panel2)'};color:${a>0.55?'#170e31':'var(--text)'}" data-crm-uf="${uf}" title="${uf} · ${s?money(s.receita)+' · '+nf(s.pedidos)+' pedidos · '+nf(s.clientes.size)+' clientes':'sem vendas'}"><b>${uf}</b><small>${s?(s.receita>=1000?(s.receita/1000).toLocaleString('pt-BR',{maximumFractionDigits:0})+'k':Math.round(s.receita)):''}</small></button>`}).join('')}</div>`}
function rankProdutos(rows){const m=new Map();for(const o of rows)for(const it of o.items||[]){const k=normalized(it.sku||it.title)||'?';const p=m.get(k)||{sku:it.sku||'',titulo:it.title||it.sku||'Sem descrição',qtd:0,receita:0,pedidos:new Set(),clientes:new Set(),canais:{},ufs:{}};const q=Number(it.qty)||0,v=q*(Number(it.price)||0);p.qtd+=q;p.receita+=v;p.pedidos.add(o.id);const ck=chave(o);if(ck)p.clientes.add(ck);p.canais[o.platform]=(p.canais[o.platform]||0)+v;const uf=ufDe(o);if(uf)p.ufs[uf]=(p.ufs[uf]||0)+q;m.set(k,p)}
 return [...m.values()].map(p=>({...p,qtd:round(p.qtd),receita:round(p.receita),pedidos:p.pedidos.size,clientes:p.clientes.size,uf:Object.entries(p.ufs).sort((a,b)=>b[1]-a[1])[0]?.[0]||''}))}
function linhaMensal(){const meses=[...new Set(db.orders.map(o=>o.date.slice(0,7)))].sort().slice(-12);const prim=new Map(clientes().map(c=>[c.key,c.primeira.slice(0,7)]));
 const dados=meses.map(m=>{const ks=new Set(db.orders.filter(o=>o.date.startsWith(m)&&(!ui.plat||o.platform===ui.plat)).map(chave).filter(Boolean));let nov=0,rec=0;for(const k of ks)prim.get(k)===m?nov++:rec++;return {m,nov,rec}});const max=Math.max(1,...dados.map(d=>d.nov+d.rec));
 return `<div class="colchart2">${dados.map(d=>`<div class="col2" title="${d.m}: ${d.nov} novos · ${d.rec} recorrentes"><div class="stack"><i class="rec" style="height:${d.rec/max*100}%"></i><i class="nov" style="height:${d.nov/max*100}%"></i></div><small>${new Date(d.m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></div>`).join('')}</div><div class="legend" style="margin-top:10px"><span><i style="background:var(--accent)"></i>Novos</span><span><i style="background:var(--green)"></i>Recorrentes</span></div>`}
function rfmGrade(cl){const g={};for(const c of cl){const k=c.R+'-'+c.F;g[k]=(g[k]||0)+1}const max=Math.max(1,...Object.values(g));
 return `<div class="rfm"><div class="rfmy">Frequência →</div><div class="rfmgrid">${[5,4,3,2,1].map(f=>[1,2,3,4,5].map(r=>{const n=g[r+'-'+f]||0;return `<div class="rfmc" style="background:rgba(102,223,181,${n?(0.12+0.8*n/max).toFixed(2):0.04})" title="Recência ${r} · Frequência ${f}: ${n} clientes">${n||''}</div>`}).join('')).join('')}</div><div class="rfmx">Recência → (5 = comprou há pouco)</div></div>`}

// ─────────────── Painel ───────────────
function painelView(){const rows=pedidos(),ks=new Set(rows.map(chave).filter(Boolean)),todos=clientes(),cl=todos.filter(c=>ks.has(c.key)),rec=cl.filter(c=>c.n>=2),receita=round(rows.reduce((a,o)=>a+o.gross,0)),itens=rows.reduce((a,o)=>a+qtdItens(o),0);
 const recRec=round(rows.filter(o=>{const c=todos.find(x=>x.key===chave(o));return c&&o.date>c.primeira}).reduce((a,o)=>a+o.gross,0));
 const ints=rec.map(c=>c.intervalo).filter(Boolean).sort((a,b)=>a-b),medInt=ints.length?ints[Math.floor(ints.length/2)]:0,prox=todos.filter(c=>c.status==='Recompra próxima'||c.status==='Recompra atrasada').length;
 const uf=porUF(rows),top=rankProdutos(rows).sort((a,b)=>b.receita-a.receita).slice(0,8),regioes={};for(const s of Object.values(uf)){const r=REG[s.uf]||'—';regioes[r]=(regioes[r]||0)+s.receita}
 const cid={};for(const o of rows){const c=cidadeDe(o);if(!c)continue;const k=c+' / '+ufDe(o);cid[k]=(cid[k]||0)+o.gross}const topCid=Object.entries(cid).sort((a,b)=>b[1]-a[1]).slice(0,6);
 return filtros()+`<div class="grid kpis4">${kpi('Clientes compradores',nf(cl.length),`${nf(cl.filter(c=>c.primeira>=(rows.at(0)?.date||'')&&rows.some(o=>o.date===c.primeira)).length)} fizeram a 1ª compra no período`)}${kpi('Taxa de recompra',pctf(cl.length?rec.length/cl.length*100:0),`${nf(rec.length)} clientes com 2+ pedidos`,'green')}${kpi('Ticket médio',money(rows.length?receita/rows.length:0),`${nf(rows.length)} pedidos · ${(rows.length?itens/rows.length:0).toLocaleString('pt-BR',{maximumFractionDigits:2})} itens/pedido`)}${kpi('Valor por cliente',money(cl.length?receita/cl.length:0),'receita ÷ clientes no período','gold')}</div>
 <div class="grid kpis4">${kpi('Unidades vendidas',nf(itens),`${nf(rankProdutos(rows).length)} brinquedos diferentes`)}${kpi('Receita de recompra',pctf(receita?recRec/receita*100:0),money(recRec)+' de clientes que voltaram','green')}${kpi('Intervalo de recompra',medInt?medInt+' dias':'—','mediana entre pedidos do mesmo cliente')}${kpi('Recompra prevista',nf(prox),'clientes na janela ou atrasados agora','gold')}</div>
 <div class="grid crm2"><section class="card"><div class="cardhead"><div><h2>Onde estão seus clientes</h2><p class="caption">Receita por estado · clique para ver as cidades</p></div><button class="small quiet" data-nav="crmgeo">Detalhar ${icon('arrow')}</button></div>${mapaBrasil(uf)}
  <div class="grid three minis">${['Sudeste','Sul','Nordeste','Centro-Oeste','Norte'].map(r=>`<div><small>${r}</small><strong>${pctf(receita?(regioes[r]||0)/receita*100:0)}</strong><small>${money(regioes[r]||0)}</small></div>`).join('')}</div></section>
 <section class="card"><div class="cardhead"><div><h2>Mais vendidos</h2><p class="caption">Por receita no período</p></div><button class="small quiet" data-nav="crmprodutos">Ranking ${icon('arrow')}</button></div>${top.length?barras(top,x=>x.receita,x=>x.titulo):'<p class="caption">Sem itens no período.</p>'}
  <div class="navlabel" style="margin:18px 0 6px">Cidades que mais compram</div>${topCid.map(([c,v])=>`<div class="listline"><span>${esc(c)}</span><strong>${money(v)}</strong></div>`).join('')||'<p class="caption">Sem cidade nos pedidos.</p>'}</section></div>
 <div class="grid crm3" style="margin-top:18px"><section class="card"><div class="cardhead"><div><h2>Clientes novos × recorrentes</h2><p class="caption">Últimos 12 meses</p></div></div>${linhaMensal()}</section>
 <section class="card"><div class="cardhead"><div><h2>Mapa RFM</h2><p class="caption">Recência × frequência · quanto mais verde, mais clientes</p></div></div>${rfmGrade(todos)}</section>
 <section class="card"><div class="cardhead"><h2>Segmentos</h2><button class="small quiet" data-nav="crmclientes">Clientes ${icon('arrow')}</button></div>${SEGS.map(s=>`<button class="listline segline" data-crm-seg="${s}"><span><span class="badge ${SEGTOM[s]}">${s}</span></span><strong>${nf(todos.filter(c=>c.seg===s).length)}</strong></button>`).join('')}
  <div class="navlabel" style="margin:16px 0 6px">Comprados juntos</div>${juntos(rows,4).map(([k,n])=>`<p class="caption" style="margin:4px 0">${esc(k)} <strong>${n}×</strong></p>`).join('')||'<p class="caption">Poucos pedidos com mais de um item.</p>'}</section></div>`}

// ─────────────── Clientes 360 ───────────────
function clientesView(){const q=normalized(ui.busca);let l=clientes().filter(c=>(!ui.seg||c.seg===ui.seg)&&(!ui.uf||c.uf===ui.uf)&&(!ui.plat||c.canais[ui.plat])&&(!q||normalized(c.nome+' '+c.doc+' '+c.cidade+' '+c.apelido).includes(q)));
 const ord={total:(a,b)=>b.total-a.total,recente:(a,b)=>b.ultima.localeCompare(a.ultima),pedidos:(a,b)=>b.n-a.n,itens:(a,b)=>b.itens-a.itens,proxima:(a,b)=>String(a.proxima||'9').localeCompare(String(b.proxima||'9'))}[ui.ordem];l.sort(ord);const pg=200,tot=l.length;l=l.slice(ui.pag*pg,(ui.pag+1)*pg);
 return `<div class="crmbar"><div class="searchin">${icon('search')}<input type="search" id="crmBusca" placeholder="Nome, CPF, cidade ou apelido…" value="${esc(ui.busca)}"></div><select data-crm-segsel aria-label="Segmento"><option value="">Todos os segmentos</option>${SEGS.map(s=>`<option ${ui.seg===s?'selected':''}>${s}</option>`).join('')}</select><select data-crm-ufsel aria-label="Estado"><option value="">Todos os estados</option>${Object.keys(REG).sort().map(u=>`<option ${ui.uf===u?'selected':''}>${u}</option>`).join('')}</select><select data-crm-plat aria-label="Canal"><option value="">Todos os canais</option>${['Mercado Livre','Shopee','Magalu'].map(p=>`<option ${ui.plat===p?'selected':''}>${p}</option>`).join('')}</select><select data-crm-ordem aria-label="Ordenar"><option value="total" ${ui.ordem==='total'?'selected':''}>Maior valor</option><option value="recente" ${ui.ordem==='recente'?'selected':''}>Compra mais recente</option><option value="pedidos" ${ui.ordem==='pedidos'?'selected':''}>Mais pedidos</option><option value="itens" ${ui.ordem==='itens'?'selected':''}>Mais itens</option><option value="proxima" ${ui.ordem==='proxima'?'selected':''}>Próxima recompra</option></select><span style="flex:1"></span><button class="small" data-crm-csv="clientes">${icon('download')} Exportar</button></div>
 <div class="tablebox"><div class="tablewrap"><table class="crmtable"><thead><tr><th>Cliente</th><th>Local</th><th class="num">Pedidos</th><th class="num">Itens</th><th class="num">Total</th><th>Última compra</th><th>Recompra</th><th>Segmento</th><th>Contato</th></tr></thead><tbody>
 ${l.map(c=>`<tr class="clk" data-crm-ficha="${esc(c.key)}"><td><strong>${esc(c.nome||'—')}</strong><br><span class="caption">${esc(c.apelido||c.doc||'')}</span></td><td>${esc(c.cidade)}<br><span class="caption">${c.uf} · ${REG[c.uf]||''}</span></td><td class="num">${c.n}</td><td class="num">${nf(c.itens)}</td><td class="num"><strong>${money(c.total)}</strong><br><span class="caption">ticket ${money(c.ticket)}</span></td><td>${dBR(c.ultima)} <span class="caption">(${c.recencia}d)</span><br><span class="caption ellipsis" style="display:block;max-width:220px">${esc(c.ultimoPedido?.items?.[0]?.title||'')}</span></td><td>${c.proxima?`${dBR(c.proxima)}<br><span class="caption ${c.status==='Recompra atrasada'?'red':c.status==='Recompra próxima'?'gold':''}">${c.status} · a cada ${c.intervalo}d</span>`:`<span class="caption">${c.status||'1 compra'}</span>`}</td><td><span class="badge ${SEGTOM[c.seg]}">${c.seg}</span><br><span class="caption mono">RFM ${c.rfm}</span></td><td><div class="cbtns">${botoesContato(c,true)}</div></td></tr>`).join('')||'<tr><td colspan="9" class="empty">Nenhum cliente com esses filtros.</td></tr>'}</tbody></table></div>
 <div class="tablefoot">${nf(tot)} cliente(s)${tot>pg?` · <button class="small quiet" data-crm-pag="-1" ${ui.pag?'':'disabled'}>‹</button> página ${ui.pag+1} de ${Math.ceil(tot/pg)} <button class="small quiet" data-crm-pag="1" ${(ui.pag+1)*pg>=tot?'disabled':''}>›</button>`:''}</div></div>`}
function ficha(key){const c=clientes().find(x=>x.key===key);if(!c)return;const crm=db.crm[key]=db.crm[key]||{stage:'Novo',tags:[],notes:'',interactions:[]};const sug=sugestoes(c);
 modal(esc(c.nome||'Cliente'),`<div class="c360head"><div class="c360av">${esc((c.nome||'?').slice(0,2).toUpperCase())}</div><div><div class="caption">${esc(c.doc||'')} ${c.apelido?'· @'+esc(c.apelido):''}</div><div>${esc(c.cidade)} · ${c.uf} · ${REG[c.uf]||''}</div><div style="margin-top:6px"><span class="badge ${SEGTOM[c.seg]}">${c.seg}</span> <span class="badge mono">RFM ${c.rfm}</span> ${c.status?`<span class="badge ${c.status==='Recompra atrasada'?'bad':c.status==='Recompra próxima'?'warn':''}">${c.status}</span>`:''}</div></div></div>
 <div class="grid kpis4 small" style="margin-top:14px"><div class="card"><small>Total comprado</small><strong>${money(c.total)}</strong><small>ticket ${money(c.ticket)}</small></div><div class="card"><small>Pedidos · itens</small><strong>${c.n} · ${nf(c.itens)}</strong><small>desde ${dBR(c.primeira)}</small></div><div class="card"><small>Última compra</small><strong>${dBR(c.ultima)}</strong><small>há ${c.recencia} dias · ${esc(c.canal)}</small></div><div class="card"><small>Próxima compra prevista</small><strong>${c.proxima?dBR(c.proxima):'—'}</strong><small>${c.intervalo?'compra a cada '+c.intervalo+' dias':'só 1 compra até agora'}</small></div></div>
 <div class="cbtns big" style="margin:14px 0">${botoesContato(c,false)}</div>
 <div class="grid two" style="gap:14px"><div><h3>Brinquedo favorito</h3><p>${esc(c.fav||'—')}</p><h3 style="margin-top:12px">Sugestões para recompra</h3>${sug.map(([t,n])=>`<p class="caption" style="margin:3px 0">• ${esc(t)} <span class="gold">(${n} clientes parecidos compraram)</span></p>`).join('')||'<p class="caption">Sem dados suficientes.</p>'}</div>
 <div><h3>Relacionamento</h3><label for="c360est">Estágio</label><select id="c360est" style="width:100%">${ESTAGIOS.map(s=>`<option ${crm.stage===s?'selected':''}>${s}</option>`).join('')}</select>
  <div class="row" style="gap:10px"><div style="flex:1"><label for="c360tel">WhatsApp / telefone</label><input id="c360tel" value="${esc(crm.telefone||'')}" placeholder="(47) 99999-9999" style="width:100%"></div><div style="flex:1"><label for="c360mail">E-mail</label><input id="c360mail" value="${esc(crm.email||'')}" style="width:100%"></div></div>
  <label for="c360nota">Anotações</label><textarea id="c360nota" style="min-height:60px">${esc(crm.notes||'')}</textarea><p class="caption">Cadastre telefone/e-mail só com consentimento do cliente (LGPD) e respeite as regras de cada marketplace sobre contato fora da plataforma.</p></div></div>
 ${window.CRMx?.secao?.(c)||''}
 <h3 style="margin:14px 0 6px">Histórico de pedidos</h3><div class="tablewrap" style="max-height:220px"><table><tbody>${[...c.pedidos].reverse().map(o=>`<tr><td>${dBR(o.date)}</td><td>${esc(o.platform)}</td><td>${(o.items||[]).map(i=>`${nf(i.qty)}× ${esc(i.title||i.sku)}`).join('<br>')}</td><td class="num">${money(o.gross)}</td></tr>`).join('')}</tbody></table></div>
 ${(crm.interactions||[]).length?`<h3 style="margin:14px 0 6px">Contatos registrados</h3>${crm.interactions.slice(-6).reverse().map(i=>`<p class="caption" style="margin:3px 0">${new Date(i.time).toLocaleString('pt-BR')} · ${esc(i.text)}</p>`).join('')}`:''}
 <div class="modalfoot"><button data-action="close">Fechar</button><button class="primary" data-crm-salvar="${esc(key)}">Salvar</button></div>`)}

// ─────────────── Mais vendidos, geografia e oportunidades ───────────────
function produtosView(){const rows=pedidos().filter(o=>!ui.uf||ufDe(o)===ui.uf),l=rankProdutos(rows).sort((a,b)=>ui.rank==='qtd'?b.qtd-a.qtd:b.receita-a.receita),tot=l.reduce((a,p)=>a+p.receita,0)||1;
 const d30=addDias(hoje(),-30),d60=addDias(hoje(),-60),r30=new Map(rankProdutos(db.orders.filter(o=>o.date>=d30)).map(p=>[p.titulo,p.receita])),r60=new Map(rankProdutos(db.orders.filter(o=>o.date>=d60&&o.date<d30)).map(p=>[p.titulo,p.receita]));const t=p=>{const a=r30.get(p.titulo)||0,b=r60.get(p.titulo)||0;return b?(a-b)/b*100:a?100:0};
 let acum=0;return filtros(`<select data-crm-rank aria-label="Ordenar"><option value="receita" ${ui.rank==='receita'?'selected':''}>Por receita</option><option value="qtd" ${ui.rank==='qtd'?'selected':''}>Por quantidade</option></select><select data-crm-ufsel aria-label="Estado"><option value="">Todos os estados</option>${Object.keys(REG).sort().map(u=>`<option ${ui.uf===u?'selected':''}>${u}</option>`).join('')}</select>`)+
 `<div class="grid kpis4">${kpi('Brinquedos vendidos',nf(l.length),'itens diferentes no período')}${kpi('Unidades',nf(l.reduce((a,p)=>a+p.qtd,0)),'peças vendidas')}${kpi('Top 10',pctf(l.slice(0,10).reduce((a,p)=>a+p.receita,0)/tot*100),'da receita de produtos','gold')}${kpi('Campeão',esc((l[0]?.titulo||'—').slice(0,26)),l[0]?`${money(l[0].receita)} · ${nf(l[0].qtd)} un.`:'','green')}</div>
 <div class="tablebox"><div class="tabletop"><h2>Ranking${ui.uf?' · '+ui.uf:''}</h2><button class="small" data-crm-csv="produtos">${icon('download')} Exportar</button></div><div class="tablewrap"><table><thead><tr><th>#</th><th>Brinquedo</th><th class="num">Unidades</th><th class="num">Pedidos</th><th class="num">Clientes</th><th class="num">Receita</th><th class="num">%</th><th class="num">ABC</th><th>Canais</th><th>Estado líder</th><th class="num">30 dias</th></tr></thead><tbody>${l.slice(0,300).map((p,i)=>{acum+=p.receita;const cv=acum/tot<=.8?'A':acum/tot<=.95?'B':'C',tr=t(p);return `<tr><td class="caption">${i+1}</td><td><strong>${esc(p.titulo)}</strong><br><span class="caption mono">${esc(p.sku)}</span></td><td class="num">${nf(p.qtd)}</td><td class="num">${nf(p.pedidos)}</td><td class="num">${nf(p.clientes)}</td><td class="num">${money(p.receita)}</td><td class="num">${pctf(p.receita/tot*100)}</td><td class="num"><span class="badge ${cv==='A'?'ok':cv==='B'?'warn':''}">${cv}</span></td><td class="caption">${Object.entries(p.canais).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`${c.replace('Mercado Livre','ML')} ${pctf(v/p.receita*100)}`).join(' · ')}</td><td>${p.uf||'—'}</td><td class="num ${tr>5?'green':tr<-5?'red':''}">${tr>0?'▲':tr<0?'▼':'•'} ${pctf(Math.abs(tr))}</td></tr>`}).join('')||'<tr><td colspan="11" class="empty">Sem vendas no período.</td></tr>'}</tbody></table></div></div>`}
function geoView(){const rows=pedidos(),m=porUF(rows),tot=rows.reduce((a,o)=>a+o.gross,0)||1,sel=ui.uf;
 const cidades={};for(const o of rows){const uf=ufDe(o),c=cidadeDe(o);if(!c||(sel&&uf!==sel))continue;const k=c+' / '+uf,x=cidades[k]||(cidades[k]={cidade:c,uf,pedidos:0,receita:0,itens:0,clientes:new Set()});x.pedidos++;x.receita+=o.gross;x.itens+=qtdItens(o);const kk=chave(o);if(kk)x.clientes.add(kk)}
 const cl=Object.values(cidades).sort((a,b)=>b.receita-a.receita),ufs=Object.values(m).sort((a,b)=>b.receita-a.receita),regs={};for(const s of ufs){const r=REG[s.uf]||'—',x=regs[r]||(regs[r]={r,receita:0,pedidos:0,clientes:0});x.receita+=s.receita;x.pedidos+=s.pedidos;x.clientes+=s.clientes.size}
 return filtros()+`<div class="grid crm2"><section class="card"><div class="cardhead"><div><h2>Mapa de vendas</h2><p class="caption">${sel?`Estado: <strong>${sel}</strong> · <button class="quiet small" data-crm-uf="">limpar</button>`:'Clique num estado para filtrar as cidades'}</p></div></div>${mapaBrasil(m,sel)}</section>
 <section class="card"><div class="cardhead"><h2>Regiões</h2></div>${Object.values(regs).sort((a,b)=>b.receita-a.receita).map(x=>`<div class="hrow"><span class="hlab">${x.r}</span><span class="htrack"><i style="width:${x.receita/tot*100}%;background:var(--accent)"></i></span><strong>${pctf(x.receita/tot*100)}</strong></div><p class="caption" style="margin:-4px 0 10px">${money(x.receita)} · ${nf(x.pedidos)} pedidos · ${nf(x.clientes)} clientes · ticket ${money(x.receita/x.pedidos)}</p>`).join('')}</section></div>
 <div class="grid crm2" style="margin-top:18px"><div class="tablebox"><div class="tabletop"><h2>Estados</h2><button class="small" data-crm-csv="estados">${icon('download')} Exportar</button></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>UF</th><th>Região</th><th class="num">Pedidos</th><th class="num">Itens</th><th class="num">Clientes</th><th class="num">Receita</th><th class="num">%</th><th class="num">Ticket</th></tr></thead><tbody>${ufs.map(s=>`<tr class="clk ${sel===s.uf?'sel':''}" data-crm-uf="${s.uf}"><td><strong>${s.uf}</strong></td><td class="caption">${REG[s.uf]||''}</td><td class="num">${nf(s.pedidos)}</td><td class="num">${nf(s.itens)}</td><td class="num">${nf(s.clientes.size)}</td><td class="num">${money(s.receita)}</td><td class="num">${pctf(s.receita/tot*100)}</td><td class="num">${money(s.receita/s.pedidos)}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="tablebox"><div class="tabletop"><h2>Cidades${sel?' · '+sel:''}</h2><button class="small" data-crm-csv="cidades">${icon('download')} Exportar</button></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>Cidade</th><th class="num">Pedidos</th><th class="num">Itens</th><th class="num">Clientes</th><th class="num">Receita</th></tr></thead><tbody>${cl.slice(0,300).map(c=>`<tr><td><strong>${esc(c.cidade)}</strong> <span class="caption">${c.uf}</span></td><td class="num">${nf(c.pedidos)}</td><td class="num">${nf(c.itens)}</td><td class="num">${nf(c.clientes.size)}</td><td class="num">${money(c.receita)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Sem cidade nos pedidos.</td></tr>'}</tbody></table></div></div></div>`}
const ACOES={previsao:['Recompra prevista','Pelo intervalo de compras de cada cliente: estão na janela ou atrasados até 30 dias',c=>c.status==='Recompra próxima'||c.status==='Recompra atrasada'],segunda:['Janela da 2ª compra','Compraram uma vez há 25–60 dias: o momento de maior chance de voltar',c=>c.status==='Janela 2ª compra'],reativar:['Reativar','Compraram 2+ vezes e sumiram há mais de 90 dias',c=>c.n>=2&&c.recencia>90],vip:['VIPs','Maiores clientes (RFM valor 5) — cuide primeiro deles',c=>c.seg==='VIP']};
function acoesView(){const cl=clientes(),[t,d,f]=ACOES[ui.acao],l=cl.filter(f).sort((a,b)=>b.total-a.total);
 return `<div class="grid kpis4">${Object.entries(ACOES).map(([k,[tt,dd,ff]])=>`<button class="card kpi kpibtn ${ui.acao===k?'on':''}" data-crm-acao="${k}"><span class="kpil">${tt}</span><span class="kpiv">${nf(cl.filter(ff).length)}</span><span class="kpis">${dd}</span></button>`).join('')}</div>
 <div class="notice"><strong>Como agir:</strong> use o botão de conversa do pedido (Mercado Livre/Shopee) para pós-venda, e as ferramentas das plataformas para oferta: <strong>cupom de seguidores e de loja na Shopee</strong>, <strong>cupons e campanhas no Mercado Livre</strong>. WhatsApp e e-mail aparecem quando cadastrados na ficha com consentimento do cliente.</div>
 <div class="tablebox"><div class="tabletop"><div><h2>${t}</h2><p class="caption">${d}</p></div><button class="small primary" data-crm-csv="acao">${icon('download')} Exportar lista</button></div><div class="tablewrap"><table class="crmtable"><thead><tr><th>Cliente</th><th>Local</th><th class="num">Pedidos</th><th class="num">Total</th><th>Última compra</th><th>Brinquedo favorito</th><th>Recompra</th><th>Contato</th></tr></thead><tbody>${l.slice(0,400).map(c=>`<tr class="clk" data-crm-ficha="${esc(c.key)}"><td><strong>${esc(c.nome||'—')}</strong><br><span class="caption">${esc(c.apelido||c.doc||'')}</span></td><td>${esc(c.cidade)} <span class="caption">${c.uf}</span></td><td class="num">${c.n}</td><td class="num">${money(c.total)}</td><td>${dBR(c.ultima)} <span class="caption">(${c.recencia}d)</span></td><td class="caption ellipsis" style="max-width:220px">${esc(c.fav)}</td><td>${c.proxima?dBR(c.proxima):'—'}<br><span class="caption">${c.status}</span></td><td><div class="cbtns">${botoesContato(c,true)}</div></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Ninguém nesta lista agora.</td></tr>'}</tbody></table></div></div>`}

window.CRM={clientes,ficha,botoesContato:(c,p)=>botoesContato(c,p)};
addPage('crm','heart','Painel do CRM',painelView,'Quem compra, o que compra, de onde e quando deve voltar — com ações para vender mais para quem já é cliente.','',bind);
addPage('crmclientes','users','Clientes 360',clientesView,'Cada cliente com pedidos, itens, última compra, previsão de recompra, RFM e contato direto.','',bind);
addPage('crmprodutos','gift','Mais vendidos',produtosView,'Ranking por receita ou quantidade, clientes, curva ABC, canais, estado líder e tendência de 30 dias.','',bind);
addPage('crmgeo','map','Estados e cidades',geoView,'Mapa de vendas, regiões, estados e cidades com itens, clientes e ticket médio.','',bind);
addPage('crmacoes','target','Oportunidades',acoesView,'Listas prontas: recompra prevista, 2ª compra, reativação e VIPs — com o contato a um clique.','',bind);
function bind(){$$('[data-crm-plat]').forEach(s=>s.onchange=()=>{ui.plat=s.value;ui.pag=0;render()});$$('[data-crm-rank]').forEach(s=>s.onchange=()=>{ui.rank=s.value;render()});$$('[data-crm-ufsel]').forEach(s=>s.onchange=()=>{ui.uf=s.value;ui.pag=0;render()});$$('[data-crm-segsel]').forEach(s=>s.onchange=()=>{ui.seg=s.value;ui.pag=0;render()});$$('[data-crm-ordem]').forEach(s=>s.onchange=()=>{ui.ordem=s.value;render()});
 const b=$('#crmBusca');if(b)b.oninput=e=>{ui.busca=e.target.value;ui.pag=0;const pos=e.target.selectionStart;render();const n=$('#crmBusca');n.focus();n.setSelectionRange(pos,pos)}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-crm-contato]');if(a){const crm=db.crm[a.dataset.crmContato]=db.crm[a.dataset.crmContato]||{stage:'Novo',tags:[],notes:'',interactions:[]};crm.interactions=[...(crm.interactions||[]),{time:new Date().toISOString(),text:'Contato iniciado: '+a.title}];if(crm.stage==='Novo')crm.stage='Contatado';save?.();return}
 const b=e.target.closest('[data-crm-per],[data-crm-uf],[data-crm-acao],[data-crm-csv],[data-crm-ficha],[data-crm-salvar],[data-crm-seg],[data-crm-pag]');if(!b)return;const d=b.dataset;
 if(d.crmPer){ui.periodo=d.crmPer;render();return}
 if(d.crmUf!==undefined){ui.uf=ui.uf===d.crmUf?'':d.crmUf;if(page==='crm'&&ui.uf)navigate('crmgeo');else render();return}
 if(d.crmAcao){ui.acao=d.crmAcao;render();return}
 if(d.crmSeg){ui.seg=d.crmSeg;navigate('crmclientes');return}
 if(d.crmPag){ui.pag=Math.max(0,ui.pag+Number(d.crmPag));render();return}
 if(d.crmFicha){ficha(d.crmFicha);return}
 if(d.crmSalvar){const crm=db.crm[d.crmSalvar];crm.stage=$('#c360est').value;crm.telefone=$('#c360tel').value.trim();crm.email=$('#c360mail').value.trim();crm.notes=$('#c360nota').value;audit('CRM: ficha do cliente atualizada',d.crmSalvar);cache=null;closeModal();render();toast('Cliente atualizado.');return}
 if(d.crmCsv){const rows=pedidos();let out;
  if(d.crmCsv==='produtos')out=[['sku','produto','unidades','pedidos','clientes','receita','estado_lider'],...rankProdutos(rows).sort((a,b)=>b.receita-a.receita).map(p=>[p.sku,p.titulo,p.qtd,p.pedidos,p.clientes,p.receita,p.uf])];
  else if(d.crmCsv==='estados')out=[['uf','regiao','pedidos','itens','clientes','receita'],...Object.values(porUF(rows)).map(s=>[s.uf,REG[s.uf]||'',s.pedidos,s.itens,s.clientes.size,round(s.receita)])];
  else if(d.crmCsv==='cidades'){const c={};for(const o of rows){if(!cidadeDe(o))continue;const k=cidadeDe(o)+'|'+ufDe(o);const x=c[k]||(c[k]=[cidadeDe(o),ufDe(o),0,0]);x[2]++;x[3]=round(x[3]+o.gross)}out=[['cidade','uf','pedidos','receita'],...Object.values(c)]}
  else{const lista=d.crmCsv==='acao'?clientes().filter(ACOES[ui.acao][2]):clientes();out=[['cliente','documento','apelido','cidade','uf','pedidos','itens','total','ticket','primeira_compra','ultima_compra','proxima_prevista','segmento','rfm','brinquedo_favorito','canal'],...lista.map(c=>[c.nome,c.doc,c.apelido,c.cidade,c.uf,c.n,c.itens,c.total,c.ticket,c.primeira,c.ultima,c.proxima||'',c.seg,c.rfm,c.fav,c.canal])]}
  download(`EcomBalance_CRM_${d.crmCsv}.csv`,csv(out))}});
})();
