'use strict';
// Estoque operacional: inventário com leitor de código de barras (o leitor "digita" o EAN), pedidos de compra
// da sugestão ao recebimento (o recebimento é reconhecido pela nota de entrada e mede o prazo real do
// fornecedor) e lista de separação do dia (itens somados por SKU e localização, pronta para imprimir).
(()=>{
Object.assign(paths,{scan:'M4 7V4h3 M17 4h3v3 M20 17v3h-3 M7 20H4v-3 M8 8v8 M11 8v8 M14 8v8 M17 8v8',clipboard:'M9 4h6v3H9z M7 5H5v16h14V5h-2 M9 12h6 M9 16h4'});
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const dBR=d=>d?new Date(String(d).length>10?d:d+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const nf=(v,d=0)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:d});
const quem=()=>window.Cloud?.session?.user?.email||'—';
const st={prods:null,inv:null,pcs:null,invAtual:null,ultimo:null,dataSep:hoje(),canalSep:''};
async function carregar(){if(!window.Cloud?.ws)return;const [p,i,c]=await Promise.all([Cloud.client.from('produtos').select('id,nome,saldo,custo,gtin,localizacao,fornecedor,prazo_reposicao,ignorar,imagem').eq('workspace_id',Cloud.ws).limit(5000),Cloud.client.from('inventarios').select('*').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(50),Cloud.client.from('pedidos_compra').select('*').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(200)]);
 st.prods=p.data||[];st.inv=i.data||[];st.pcs=c.data||[];if(['inventario','pedcompra','separacao'].includes(page)&&!document.querySelector('.modalback'))render()}
const prod=sku=>(st.prods||[]).find(p=>p.id===sku);
const porCodigo=c=>{c=String(c).trim();return (st.prods||[]).find(p=>p.gtin&&p.gtin===c)||(st.prods||[]).find(p=>p.id.toLowerCase()===c.toLowerCase())};
const upsert=async(t,row)=>{const {error}=await Cloud.client.from(t).upsert({...row,workspace_id:Cloud.ws,updated_at:new Date().toISOString()},{onConflict:'workspace_id,id'});if(error)throw error};

// ─────────── Inventário ───────────
function inventarioView(){if(!st.prods){carregar();return '<div class="empty">Carregando…</div>'}
 const inv=st.invAtual&&st.inv.find(x=>x.id===st.invAtual);
 if(inv)return contagemView(inv);
 return `<div class="notice">Faça a contagem física com o leitor de código de barras (ou digitando o SKU) direto no navegador — no computador ou no celular. Ao concluir, o EcomBalance mostra as diferenças contra o saldo do sistema e gera a planilha de ajuste.</div>
 <div class="crmbar"><input id="invNome" placeholder="Nome do inventário (ex.: Inventário setembro · depósito)" style="flex:1;min-width:260px"><input id="invLocal" placeholder="Local/rua (opcional)"><button class="primary small" data-inv="novo">${icon('scan')} Iniciar contagem</button></div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Inventário</th><th>Local</th><th>Situação</th><th class="num">Itens contados</th><th class="num">Divergências</th><th>Criado</th><th></th></tr></thead><tbody>
 ${st.inv.map(x=>{const n=Object.keys(x.contagens||{}).length,dv=x.sistema?Object.entries(x.contagens||{}).filter(([s,c])=>Number(c.qtd)!==Number(x.sistema[s]??0)).length:null;return `<tr><td><strong>${esc(x.nome)}</strong></td><td>${esc(x.local||'—')}</td><td><span class="badge ${x.status==='concluido'?'ok':x.status==='aberto'?'info':''}">${x.status}</span></td><td class="num">${n}</td><td class="num">${dv??'—'}</td><td>${dBR(x.created_at)} · ${esc(x.criado_por||'')}</td><td><button class="small" data-inv-abrir="${esc(x.id)}">${x.status==='aberto'?'Continuar':'Ver'}</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Nenhum inventário ainda.</td></tr>'}</tbody></table></div></div>`}
function contagemView(inv){const cont=inv.contagens||{},aberto=inv.status==='aberto',sis=inv.sistema||Object.fromEntries((st.prods||[]).map(p=>[p.id,Number(p.saldo)||0]));
 const linhas=Object.entries(cont).map(([sku,c])=>({sku,p:prod(sku),q:Number(c.qtd)||0,s:Number(sis[sku]??0),c})).sort((a,b)=>String(b.c.em).localeCompare(String(a.c.em)));
 const dif=linhas.filter(l=>l.q!==l.s),valor=dif.reduce((x,l)=>x+(l.q-l.s)*(Number(l.p?.custo)||0),0);
 const naoContados=aberto?[]:(st.prods||[]).filter(p=>!cont[p.id]&&Number(p.saldo)>0&&!p.ignorar);
 return `<div class="row" style="margin-bottom:12px"><button class="small" data-inv-voltar="1">‹ Inventários</button><h2 style="margin:0 12px">${esc(inv.nome)}</h2><span class="badge ${aberto?'info':'ok'}">${inv.status}</span></div>
 ${aberto?`<section class="card scancard"><label for="invCod">${icon('scan')} Bipe o código de barras ou digite o SKU e tecle Enter</label><div class="row"><input id="invCod" autocomplete="off" autofocus placeholder="EAN ou SKU" style="flex:1;font-size:20px;padding:14px"><input id="invQtd" type="number" value="1" min="0" style="width:90px;font-size:20px;padding:14px" aria-label="Quantidade"><label class="check-l" style="margin:0"><input type="checkbox" class="check" id="invSomar" checked> somar</label></div>
  ${st.ultimo?`<div class="scanlast ${st.ultimo.ok?'ok':'bad'}">${st.ultimo.ok?`${icon('check')} <strong>${esc(st.ultimo.nome)}</strong> · agora ${nf(st.ultimo.qtd)} un.`:`${icon('alert')} Código não encontrado: <strong>${esc(st.ultimo.cod)}</strong>`}</div>`:''}</section>`:''}
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Itens contados</span><span class="kpiv">${linhas.length}</span><span class="kpis">${nf(linhas.reduce((x,l)=>x+l.q,0))} unidades</span></div><div class="card kpi"><span class="kpil">Com diferença</span><span class="kpiv ${dif.length?'gold':''}">${dif.length}</span><span class="kpis">contra o saldo do sistema</span></div><div class="card kpi"><span class="kpil">Diferença em valor</span><span class="kpiv ${valor<0?'red':''}">${money(valor)}</span><span class="kpis">a custo</span></div><div class="card kpi"><span class="kpil">Não contados</span><span class="kpiv">${aberto?'—':naoContados.length}</span><span class="kpis">${aberto?'aparece ao concluir':'com saldo no sistema'}</span></div></div>
 <div class="tablebox"><div class="tabletop"><h2>Contagem</h2><div class="row">${aberto?`<button class="small primary" data-inv-concluir="${esc(inv.id)}">${icon('check')} Concluir inventário</button>`:''}<button class="small" data-inv-csv="${esc(inv.id)}">${icon('download')} Planilha de ajuste</button></div></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th>Local</th><th class="num">Contado</th><th class="num">Sistema</th><th class="num">Diferença</th><th>Quem · quando</th>${aberto?'<th></th>':''}</tr></thead><tbody>
 ${linhas.map(l=>`<tr><td><strong>${esc(l.p?.nome||l.sku)}</strong><br><span class="caption mono">${esc(l.sku)}</span></td><td>${esc(l.p?.localizacao||'')}</td><td class="num">${aberto?`<input class="ufin" data-inv-qtd="${esc(l.sku)}" value="${l.q}">`:nf(l.q)}</td><td class="num">${nf(l.s)}</td><td class="num ${l.q-l.s<0?'red':l.q-l.s>0?'green':''}">${l.q-l.s>0?'+':''}${nf(l.q-l.s)}</td><td class="caption">${esc(String(l.c.por||'').split('@')[0])} · ${l.c.em?new Date(l.c.em).toLocaleTimeString('pt-BR'):''}</td>${aberto?`<td><button class="small quiet" data-inv-tirar="${esc(l.sku)}">${icon('x')}</button></td>`:''}</tr>`).join('')||'<tr><td colspan="7" class="empty">Nada contado ainda. Comece bipando um produto.</td></tr>'}
 ${naoContados.map(p=>`<tr class="muted"><td>${esc(p.nome)}<br><span class="caption mono">${esc(p.id)}</span></td><td>${esc(p.localizacao||'')}</td><td class="num">0</td><td class="num">${nf(p.saldo)}</td><td class="num red">−${nf(p.saldo)}</td><td class="caption">não contado</td></tr>`).join('')}</tbody></table></div></div>`}
async function contar(cod,qtd,somar){const inv=st.inv.find(x=>x.id===st.invAtual);if(!inv)return;const p=porCodigo(cod);if(!p){st.ultimo={ok:false,cod};render();focar();return}
 const c={...(inv.contagens||{})},antes=Number(c[p.id]?.qtd)||0,novo=somar?antes+qtd:qtd;c[p.id]={qtd:novo,por:quem(),em:new Date().toISOString()};inv.contagens=c;st.ultimo={ok:true,nome:p.nome,qtd:novo};render();focar();
 try{await upsert('inventarios',{id:inv.id,nome:inv.nome,status:inv.status,local:inv.local,contagens:c,criado_por:inv.criado_por})}catch(e){toast('Não salvou: '+e.message)}}
const focar=()=>setTimeout(()=>$('#invCod')?.focus(),30);

// ─────────── Pedidos de compra ───────────
const PC_ST={rascunho:['Rascunho',''],enviado:['Enviado','info'],parcial:['Recebido em parte','warn'],recebido:['Recebido','ok'],cancelado:['Cancelado','']};
function pcView(){if(!st.pcs){carregar();return '<div class="empty">Carregando…</div>'}reconhecerRecebimentos();
 const abertos=st.pcs.filter(p=>['enviado','parcial'].includes(p.status)),lt=prazosReais();
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">Em aberto</span><span class="kpiv">${abertos.length}</span><span class="kpis">${money(abertos.reduce((s,p)=>s+tot(p),0))}</span></div><div class="card kpi"><span class="kpil">Rascunhos</span><span class="kpiv">${st.pcs.filter(p=>p.status==='rascunho').length}</span><span class="kpis">aguardando envio</span></div><div class="card kpi"><span class="kpil">Recebidos (90 dias)</span><span class="kpiv">${st.pcs.filter(p=>p.status==='recebido'&&p.recebido_em>=new Date(Date.now()-90*864e5).toISOString()).length}</span><span class="kpis">reconhecidos pela nota</span></div><div class="card kpi"><span class="kpil">Prazo real médio</span><span class="kpiv">${lt.media!=null?Math.round(lt.media)+' d':'—'}</span><span class="kpis">do envio até a nota de entrada</span></div></div>
 <div class="crmbar"><button class="small primary" data-nav="estcompras">${icon('cart')} Criar a partir da sugestão de compras</button><button class="small" data-pc="novo">${icon('plus')} Pedido em branco</button></div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Nº</th><th>Fornecedor</th><th>Situação</th><th class="num">Itens</th><th class="num">Total</th><th>Previsto</th><th>Enviado</th><th>Recebido</th><th></th></tr></thead><tbody>
 ${st.pcs.map(p=>{const [t,tom]=PC_ST[p.status]||[p.status,''];return `<tr class="clickrow" data-pc-abrir="${esc(p.id)}"><td class="mono">${p.numero||'—'}</td><td><strong>${esc(p.fornecedor)}</strong></td><td><span class="badge ${tom}">${t}</span></td><td class="num">${(p.itens||[]).length}</td><td class="num">${money(tot(p))}</td><td>${dBR(p.previsto)}</td><td>${p.enviado_em?dBR(p.enviado_em):'—'}</td><td>${p.recebido_em?dBR(p.recebido_em):'—'}</td><td>${icon('chev')}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Nenhum pedido de compra. Crie a partir da Sugestão de compras.</td></tr>'}</tbody></table></div></div>
 ${Object.keys(lt.porForn).length?`<div class="tablebox" style="margin-top:16px"><div class="tabletop"><h2>Prazo real por fornecedor</h2><button class="small" data-pc="aplicar-prazos">Usar como prazo de reposição dos produtos</button></div><div class="tablewrap"><table><tbody>${Object.entries(lt.porForn).map(([f,d])=>`<tr><td>${esc(f)}</td><td class="num">${Math.round(d)} dias</td></tr>`).join('')}</tbody></table></div></div>`:''}`}
const tot=p=>(p.itens||[]).reduce((s,i)=>s+Number(i.qtd||0)*Number(i.custo||0),0);
const normal=s=>normalized(String(s||'')).replace(/[^a-z0-9]/g,'');
// Recebimento: nota de entrada do mesmo fornecedor, emitida depois do envio, com os SKUs do pedido.
function reconhecerRecebimentos(){for(const p of st.pcs.filter(x=>['enviado','parcial'].includes(x.status))){
 const notas=(db.purchases||[]).filter(n=>n.tipo==='compra'&&n.emissao>=String(p.enviado_em||'').slice(0,10)&&(normal(n.fornecedor).includes(normal(p.fornecedor).slice(0,12))||(p.fornecedor_doc&&String(n.fornecedorDoc||'').replace(/\D/g,'')===String(p.fornecedor_doc).replace(/\D/g,''))));
 if(!notas.length)continue;const rec={};for(const n of notas)for(const it of n.itens||[])rec[it.sku]=(rec[it.sku]||0)+Number(it.qtd||0);
 const itens=(p.itens||[]).map(i=>({...i,recebido:Math.min(Number(i.qtd),rec[i.sku]||0)}));const tudo=itens.every(i=>i.recebido>=Number(i.qtd)),algum=itens.some(i=>i.recebido>0);
 if(!algum)continue;const novo=tudo?'recebido':'parcial';if(novo===p.status&&JSON.stringify(itens)===JSON.stringify(p.itens))continue;
 Object.assign(p,{itens,status:novo,recebido_em:tudo?(notas.map(n=>n.emissao).sort().at(-1)+'T12:00:00Z'):p.recebido_em,notas:notas.map(n=>({id:n.id,numero:n.numero,emissao:n.emissao}))});
 upsert('pedidos_compra',p).then(()=>audit('Pedido de compra recebido',`nº ${p.numero} · ${p.fornecedor} · ${novo}`)).catch(()=>{})}}
function prazosReais(){const l=st.pcs.filter(p=>p.status==='recebido'&&p.enviado_em&&p.recebido_em),porForn={};for(const p of l){const d=(new Date(p.recebido_em)-new Date(p.enviado_em))/864e5;(porForn[p.fornecedor]=porForn[p.fornecedor]||[]).push(d)}
 for(const f in porForn)porForn[f]=porForn[f].reduce((a,b)=>a+b,0)/porForn[f].length;const v=Object.values(porForn);return {porForn,media:v.length?v.reduce((a,b)=>a+b,0)/v.length:null}}
function abrirPc(id){const p=st.pcs.find(x=>x.id===id);if(!p)return;const ed=p.status==='rascunho',[t,tom]=PC_ST[p.status];
 modal(`Pedido de compra ${p.numero?'nº '+p.numero:''}`,`<div class="grid three"><div class="field"><label>Fornecedor</label><input id="pcForn" value="${esc(p.fornecedor)}" ${ed?'':'disabled'}></div><div class="field"><label>CNPJ</label><input id="pcDoc" value="${esc(p.fornecedor_doc||'')}" ${ed?'':'disabled'}></div><div class="field"><label>Previsão de entrega</label><input id="pcPrev" type="date" value="${esc(p.previsto||'')}"></div></div>
 <p><span class="badge ${tom}">${t}</span> ${p.notas?.length?`· notas: ${p.notas.map(n=>`NF ${esc(n.numero)} (${dBR(n.emissao)})`).join(', ')}`:''}</p>
 <div class="tablewrap" style="max-height:320px"><table><thead><tr><th>Produto</th><th class="num">Qtd.</th><th class="num">Custo</th><th class="num">Total</th><th class="num">Recebido</th>${ed?'<th></th>':''}</tr></thead><tbody>${(p.itens||[]).map((i,k)=>`<tr><td>${esc(i.nome||i.sku)}<br><span class="caption mono">${esc(i.sku)}</span></td><td class="num">${ed?`<input class="ufin" data-pci="${k}" data-pci-c="qtd" value="${i.qtd}">`:nf(i.qtd)}</td><td class="num">${ed?`<input class="ufin" data-pci="${k}" data-pci-c="custo" value="${i.custo}">`:money(i.custo)}</td><td class="num">${money(i.qtd*i.custo)}</td><td class="num">${nf(i.recebido||0)}</td>${ed?`<td><button class="small quiet" data-pc-tirar="${k}">${icon('x')}</button></td>`:''}</tr>`).join('')}</tbody></table></div>
 ${ed?`<div class="row" style="margin-top:8px"><input id="pcAdd" placeholder="Adicionar produto: SKU ou EAN" style="flex:1"><button class="small" data-pc-add="${esc(p.id)}">Adicionar</button></div>`:''}
 <label for="pcObs">Observação</label><textarea id="pcObs" rows="2">${esc(p.observacao||'')}</textarea>
 <div class="modalfoot"><button data-action="close">Fechar</button><button data-pc-print="${esc(p.id)}">${icon('print')} Imprimir / PDF</button><button data-pc-csv="${esc(p.id)}">${icon('download')} Planilha</button>${p.status==='rascunho'?`<button class="primary" data-pc-enviar="${esc(p.id)}">${icon('send')} Marcar como enviado</button>`:''}${['rascunho','enviado'].includes(p.status)?`<button class="quiet" data-pc-cancelar="${esc(p.id)}">Cancelar pedido</button>`:''}<button class="primary" data-pc-salvar="${esc(p.id)}">${icon('check')} Salvar</button></div>`);st.pcAberto=id}
function lerModalPc(p){if(p.status==='rascunho'){p.fornecedor=$('#pcForn').value.trim()||p.fornecedor;p.fornecedor_doc=$('#pcDoc').value.trim()||null;$$('[data-pci]').forEach(i=>{p.itens[Number(i.dataset.pci)][i.dataset.pciC]=Number(String(i.value).replace(',','.'))||0})}p.previsto=$('#pcPrev').value||null;p.observacao=$('#pcObs').value.trim()||null}
async function novoPc(fornecedor,itens){const numero=Math.max(0,...st.pcs.map(p=>p.numero||0))+1,p={id:'pc-'+uid(),numero,fornecedor:fornecedor||'Fornecedor',status:'rascunho',itens,notas:[],criado_por:quem()};await upsert('pedidos_compra',p);st.pcs.unshift(p);audit('Pedido de compra criado',`nº ${numero} · ${p.fornecedor} · ${itens.length} item(ns)`);return p}
function imprimirPc(p){const w=window.open('','_blank');if(!w)return toast('Libere pop-ups para imprimir.');w.document.write(`<html><head><title>Pedido de compra ${p.numero}</title><style>body{font:13px Arial;margin:32px;color:#111}table{width:100%;border-collapse:collapse;margin-top:16px}td,th{border-bottom:1px solid #ccc;padding:8px;text-align:left}th:nth-child(n+2),td:nth-child(n+2){text-align:right}h1{margin:0}small{color:#555}</style></head><body><h1>Pedido de compra nº ${p.numero}</h1><small>${esc(window.Cloud?.wsName||'')} · emitido em ${new Date().toLocaleDateString('pt-BR')}</small><p><strong>Fornecedor:</strong> ${esc(p.fornecedor)} ${p.fornecedor_doc?'· '+esc(p.fornecedor_doc):''}<br><strong>Previsão:</strong> ${dBR(p.previsto)}</p><table><tr><th>Produto</th><th>Qtd.</th><th>Custo</th><th>Total</th></tr>${(p.itens||[]).map(i=>`<tr><td>${esc(i.sku)} · ${esc(i.nome||'')}</td><td>${i.qtd}</td><td>${money(i.custo)}</td><td>${money(i.qtd*i.custo)}</td></tr>`).join('')}<tr><th>Total</th><th></th><th></th><th>${money(tot(p))}</th></tr></table>${p.observacao?`<p>${esc(p.observacao)}</p>`:''}<script>print()<\/script></body></html>`);w.document.close()}

// ─────────── Separação do dia ───────────
function separacaoView(){if(!st.prods){carregar();return '<div class="empty">Carregando…</div>'}const l=db.orders.filter(o=>o.date===st.dataSep&&(!st.canalSep||o.platform===st.canalSep));
 const soma=new Map();for(const o of l)for(const it of o.items||[]){const k=String(it.sku||it.title);const x=soma.get(k)||{sku:it.sku,nome:it.title,q:0,pedidos:0};x.q+=Number(it.qty)||0;x.pedidos++;soma.set(k,x)}
 const itens=[...soma.values()].map(x=>({...x,loc:prod(x.sku)?.localizacao||'',saldo:prod(x.sku)?.saldo})).sort((a,b)=>String(a.loc||'zzz').localeCompare(String(b.loc||'zzz'))||b.q-a.q);
 const canais=[...new Set(db.orders.map(o=>o.platform))];
 return `<div class="crmbar"><input type="date" id="sepData" value="${st.dataSep}"><div class="segtabs">${[['','Todos'],...canais.map(c=>[c,c])].map(([k,t])=>`<button class="${st.canalSep===k?'active':''}" data-sep-canal="${esc(k)}">${esc(t)}</button>`).join('')}</div><button class="small primary" data-sep-print="1">${icon('print')} Imprimir lista de separação</button></div>
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Pedidos</span><span class="kpiv">${nf(l.length)}</span><span class="kpis">${dBR(st.dataSep)}</span></div><div class="card kpi"><span class="kpil">Unidades a separar</span><span class="kpiv">${nf(itens.reduce((s,i)=>s+i.q,0))}</span><span class="kpis">${itens.length} SKU(s)</span></div><div class="card kpi"><span class="kpil">Sem localização</span><span class="kpiv ${itens.filter(i=>!i.loc).length?'gold':''}">${itens.filter(i=>!i.loc).length}</span><span class="kpis">cadastre na ficha do produto</span></div><div class="card kpi"><span class="kpil">Saldo insuficiente</span><span class="kpiv ${itens.filter(i=>i.saldo!=null&&i.saldo<0).length?'red':''}">${itens.filter(i=>i.saldo!=null&&Number(i.saldo)<0).length}</span><span class="kpis">saldo negativo no sistema</span></div></div>
 <div class="tablebox"><div class="tabletop"><div><h2>Lista de separação</h2><p class="caption">Ordenada por localização para um caminho só no depósito.</p></div></div><div class="tablewrap"><table><thead><tr><th>Local</th><th>Produto</th><th class="num">Quantidade</th><th class="num">Pedidos</th><th class="num">Saldo</th></tr></thead><tbody>
 ${itens.map(i=>`<tr><td><strong>${esc(i.loc||'—')}</strong></td><td>${esc(i.nome||i.sku)}<br><span class="caption mono">${esc(i.sku||'')}</span></td><td class="num"><strong>${nf(i.q)}</strong></td><td class="num">${i.pedidos}</td><td class="num ${Number(i.saldo)<0?'red':''}">${i.saldo==null?'—':nf(i.saldo)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum pedido nesta data.</td></tr>'}</tbody></table></div></div>`}
function imprimirSep(){const w=window.open('','_blank');if(!w)return toast('Libere pop-ups para imprimir.');const t=document.querySelector('#view .tablebox table')?.outerHTML||'';w.document.write(`<html><head><title>Separação ${dBR(st.dataSep)}</title><style>body{font:13px Arial;margin:28px}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #ccc;padding:8px;text-align:left}td:first-child::before{content:'☐ ';font-size:16px}</style></head><body><h2>Lista de separação · ${dBR(st.dataSep)}${st.canalSep?' · '+esc(st.canalSep):''}</h2>${t}<script>print()<\/script></body></html>`);w.document.close()}

// ─────────── Eventos ───────────
function csv(nome,linhas){const txt=linhas.map(l=>l.map(x=>`"${String(x??'').replace(/"/g,'""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+txt],{type:'text/csv'}));a.download=nome;a.click()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-inv],[data-inv-abrir],[data-inv-voltar],[data-inv-concluir],[data-inv-csv],[data-inv-tirar],[data-pc],[data-pc-abrir],[data-pc-salvar],[data-pc-enviar],[data-pc-cancelar],[data-pc-add],[data-pc-tirar],[data-pc-print],[data-pc-csv],[data-sep-canal],[data-sep-print],[data-est-gerarpc]');if(!b)return;const d=b.dataset;
 try{
 if(d.inv==='novo'){const nome=$('#invNome').value.trim()||`Inventário ${new Date().toLocaleDateString('pt-BR')}`,x={id:'inv-'+uid(),nome,local:$('#invLocal').value.trim()||null,status:'aberto',contagens:{},criado_por:quem()};await upsert('inventarios',x);st.inv.unshift(x);st.invAtual=x.id;st.ultimo=null;audit('Inventário iniciado',nome);render();focar();return}
 if(d.invAbrir){st.invAtual=d.invAbrir;st.ultimo=null;render();focar();return}if(d.invVoltar){st.invAtual=null;render();return}
 if(d.invTirar){const inv=st.inv.find(x=>x.id===st.invAtual);const c={...inv.contagens};delete c[d.invTirar];inv.contagens=c;await upsert('inventarios',inv);render();return}
 if(d.invConcluir){const inv=st.inv.find(x=>x.id===d.invConcluir);if(!confirm('Concluir o inventário? A contagem fica travada e o saldo do sistema é registrado para comparação.'))return;inv.sistema=Object.fromEntries(st.prods.map(p=>[p.id,Number(p.saldo)||0]));inv.status='concluido';inv.concluido_por=quem();inv.concluido_em=new Date().toISOString();await upsert('inventarios',inv);audit('Inventário concluído',`${inv.nome} · ${Object.keys(inv.contagens).length} itens`);render();return}
 if(d.invCsv){const inv=st.inv.find(x=>x.id===d.invCsv),sis=inv.sistema||Object.fromEntries(st.prods.map(p=>[p.id,Number(p.saldo)||0]));csv(`ajuste-${normalized(inv.nome).replace(/[^a-z0-9]+/g,'-')}.csv`,[['SKU','Produto','Contado','Sistema','Ajuste'],...Object.entries(inv.contagens).map(([s,c])=>[s,prod(s)?.nome||'',c.qtd,sis[s]??0,Number(c.qtd)-Number(sis[s]??0)])]);return}
 if(d.pc==='novo'){const p=await novoPc(prompt('Fornecedor:')||'Fornecedor',[]);abrirPc(p.id);return}
 if(d.pc==='aplicar-prazos'){const lt=prazosReais().porForn;let n=0;for(const p of st.prods){const f=Object.keys(lt).find(k=>normal(p.fornecedor).includes(normal(k).slice(0,12)));if(!f)continue;await Cloud.client.from('produtos').update({prazo_reposicao:Math.round(lt[f])}).eq('workspace_id',Cloud.ws).eq('id',p.id);n++}toast(`${n} produto(s) com prazo real de reposição.`);return}
 if(d.pcAbrir){abrirPc(d.pcAbrir);return}
 const p=st.pcs?.find(x=>x.id===(d.pcSalvar||d.pcEnviar||d.pcCancelar||d.pcAdd||d.pcPrint||d.pcCsv||st.pcAberto));
 if(d.pcSalvar){lerModalPc(p);await upsert('pedidos_compra',p);closeModal();toast('Pedido salvo.');render();return}
 if(d.pcEnviar){lerModalPc(p);p.status='enviado';p.enviado_em=new Date().toISOString();await upsert('pedidos_compra',p);audit('Pedido de compra enviado',`nº ${p.numero} · ${p.fornecedor} · ${money(tot(p))}`);closeModal();toast('Pedido marcado como enviado. O recebimento é reconhecido sozinho pela nota de entrada.');render();return}
 if(d.pcCancelar){if(!confirm('Cancelar este pedido?'))return;p.status='cancelado';await upsert('pedidos_compra',p);closeModal();render();return}
 if(d.pcAdd){lerModalPc(p);const x=porCodigo($('#pcAdd').value);if(!x)return toast('Produto não encontrado.');p.itens.push({sku:x.id,nome:x.nome,qtd:1,custo:Number(x.custo)||0,recebido:0});await upsert('pedidos_compra',p);abrirPc(p.id);return}
 if(d.pcTirar!==undefined){lerModalPc(p);p.itens.splice(Number(d.pcTirar),1);await upsert('pedidos_compra',p);abrirPc(p.id);return}
 if(d.pcPrint){lerModalPc(p);imprimirPc(p);return}
 if(d.pcCsv){csv(`pedido-compra-${p.numero}.csv`,[['SKU','Produto','Quantidade','Custo','Total'],...p.itens.map(i=>[i.sku,i.nome,i.qtd,String(i.custo).replace('.',','),String((i.qtd*i.custo).toFixed(2)).replace('.',',')])]);return}
 if(d.sepCanal!==undefined){st.canalSep=d.sepCanal;render();return}if(d.sepPrint){imprimirSep();return}
 if(d.estGerarpc){const itens=JSON.parse(d.estGerarpc);if(!st.pcs)await carregar();const pc=await novoPc(b.dataset.forn,itens);toast(`Pedido de compra nº ${pc.numero} criado (rascunho).`);navigate('pedcompra');setTimeout(()=>abrirPc(pc.id),300);return}
 }catch(x){toast(x.message||String(x))}});
document.addEventListener('keydown',e=>{if(e.target.id==='invCod'&&e.key==='Enter'){e.preventDefault();const v=e.target.value.trim();if(!v)return;contar(v,Number($('#invQtd').value)||1,$('#invSomar').checked)}});
document.addEventListener('change',async e=>{if(e.target.id==='sepData'){st.dataSep=e.target.value;render();return}const q=e.target.closest('[data-inv-qtd]');if(q){const inv=st.inv.find(x=>x.id===st.invAtual);inv.contagens[q.dataset.invQtd]={...inv.contagens[q.dataset.invQtd],qtd:Number(q.value)||0,por:quem(),em:new Date().toISOString()};await upsert('inventarios',inv);render()}});
addPage('inventario','scan','Inventário',inventarioView,'Contagem física com leitor de código de barras, diferenças contra o sistema e planilha de ajuste.','',()=>{focar()});
addPage('pedcompra','clipboard','Pedidos de compra',pcView,'Do pedido ao fornecedor até o recebimento pela nota de entrada — com o prazo real de cada fornecedor.','',()=>{});
addPage('separacao','box','Separação do dia',separacaoView,'Itens dos pedidos somados por SKU e localização, prontos para imprimir.','',()=>{});
window.Estoque2={carregar};
})();
