'use strict';
// Fechamento contábil do mês, pronto para o escritório: (1) checklist do que precisa estar certo antes de
// fechar; (2) de-para de cada conta da contabilidade automática para a conta do plano do escritório (lido do
// balancete importado), com sugestão automática; (3) lote de lançamentos no plano do escritório (detalhado ou
// consolidado por dia) para importar no sistema contábil; (4) registro do fechamento (quem, quando).
(()=>{
Object.assign(paths,{lockbook:'M5 4h11l3 3v13H5z M9 12h6v5H9z M10 12v-2a2 2 0 0 1 4 0v2'});
const ui={aba:'checklist',modo:'consolidado',busca:''};
const mesFim=m=>{const [y,mm]=m.split('-').map(Number);return new Date(y,mm,0).toLocaleDateString('sv-SE')};
const cfgC=()=>db.gerencial?.contabil||{};
const salvarC=o=>{db.gerencial={...(db.gerencial||{}),contabil:{...cfgC(),...o}};save()};
// Plano do escritório: contas analíticas vistas nos balancetes importados.
let peCache=null;
function planoEscritorio(){const k=(db.accLines||[]).length;if(peCache?.k===k)return peCache.v;const m=new Map(),pai=new Map();
 for(const l of db.accLines||[]){const c=l.conta||l.account;if(!c)continue;const d=l.descricao||l.description||'';if(c.split('.').length<5){pai.set(c,d);continue}const x=m.get(c)||new Set();x.add(d);m.set(c,x)}
 const v=[...m].map(([c,ds])=>[c,ds.size>1?`${pai.get(c.split('.').slice(0,4).join('.'))||[...ds][0]} (auxiliar por participante)`:[...ds][0]]).sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));peCache={k,v};return v}
// Sugestão: regras conhecidas deste plano + semelhança de nome.
const REGRAS=[[/^1\.1\.01\.(0[1-9]|[1-8]\d)$/,'1.1.01.02.004'],[/^1\.1\.02\.\d\d$/,'1.1.01.03.004'],[/^1\.1\.01\.90$/,'1.1.01.01.001'],[/^1\.1\.03\.01$/,'1.1.02.04.010'],[/^1\.1\.03\.03$/,'1.1.02.04.012'],[/^1\.1\.04$/,'1.1.02.14.001'],
 [/^1\.2\.01$/,'1.4.04.01.005'],[/^1\.2\.02$/,'1.4.04.01.009'],[/^1\.2\.03$/,'1.4.04.01.002'],[/^3\.1\.01$/,'2.7.01.01.001'],[/^4\.1\.0\d$/,'3.1.01.01.002'],[/^4\.2\.01$/,'3.1.02.02.003'],[/^4\.2\.02$/,'3.1.02.02.007'],[/^4\.2\.03$/,'3.1.02.01.001'],[/^4\.2\.04$/,'3.1.02.02.001'],
 [/^4\.3\.01$/,'3.1.03.02.002'],[/^5\.1\.01$/,'4.1.01.01.001'],[/^5\.1\.02$/,'4.2.01.03.044'],[/^6\.1\.01$/,'4.2.01.03.044'],[/^6\.1\.02$/,'4.2.01.03.014'],[/^6\.1\.03$/,'4.2.01.03.013'],[/^6\.2\.01$/,'4.2.02.02.002'],[/^6\.2\.02$/,'4.2.02.01.001'],
 [/^6\.3\.01$/,'4.2.01.03.002'],[/^6\.3\.02$/,'4.2.02.03.021'],[/^6\.3\.0[34]$/,'4.2.02.03.019'],[/^6\.3\.05$/,'4.2.01.03.034'],[/^6\.3\.06$/,'4.2.02.03.028'],[/^6\.3\.07$/,'4.2.02.03.009'],[/^6\.4\.01$/,'4.2.04.01.008'],[/^6\.5\.01$/,'4.2.03.03.001'],[/^6\.5\.02$/,'4.2.03.02.002'],[/^6\.8\.01$/,'4.3.01.01.001'],[/^2\.1\.01$/,'2.1.01.01.001'],[/^1\.1\.03\.02$/,'1.1.02.04.011'],[/^2\.1\.02$/,'2.1.04.03.001'],[/^2\.1\.02\.01$/,'2.1.04.03.001'],[/^2\.1\.02\.03$/,'2.1.04.03.003'],[/^2\.1\.02\.04$/,'2.1.04.03.002'],[/^1\.1\.06$/,'1.1.02.10.001'],
 [/^4\.2\.04$/,'3.1.02.02.001'],[/^4\.2\.04\.01$/,'3.1.02.02.001'],[/^4\.2\.04\.02$/,'3.1.02.02.007'],[/^4\.2\.04\.03$/,'3.1.02.02.002'],[/^4\.2\.04\.04$/,'3.1.02.02.003'],
 [/^6\.8\.02$/,'4.3.01.01.001'],[/^6\.8\.03$/,'4.3.01.02.001'],[/^2\.1\.03\.01$/,'2.1.04.02.001'],[/^2\.1\.03\.02$/,'2.1.04.02.002']];
function sugerir(c,nome,pe){const uf=c.match(/^2\.1\.02\.02\.([A-Z]{2})$/)?.[1];if(uf){const x=pe.find(([k,d])=>/^2\.1\.04\.10\./.test(k)&&new RegExp('[-\\s]'+uf+'\\s*$').test(d));if(x)return x[0]}
 const r=REGRAS.find(([re])=>re.test(c));if(r&&pe.some(([k])=>k===r[1]))return r[1];
 const tk=s=>new Set(normalized(s).split(/[^a-z]+/).filter(w=>w.length>3));const a=tk(nome);let best=null,score=0;for(const [k,d] of pe){const b=tk(d);let n=0;for(const w of a)if(b.has(w))n++;if(n>score){score=n;best=k}}return score>=1?best:null}
function contasUsadas(ini,fim){const {L,plano}=Contab.diario(),u=new Map();for(const e of L){if(e.d<ini||e.d>fim)continue;for(const [c,v] of e.l){const x=u.get(c)||{c,n:plano.get(c)?.n||c,deb:0,cred:0};v>0?x.deb+=v:x.cred-=v;u.set(c,x)}}return [...u.values()].sort((a,b)=>a.c.localeCompare(b.c,undefined,{numeric:true}))}
function depara(){return cfgC().depara||{}}
const destino=(c,nome,pe)=>depara()[c]||sugerir(c,nome,pe);

// ─────────── Lote ───────────
function lote(ini,fim,modo){const {L,plano}=Contab.diario(),pe=planoEscritorio(),memo=new Map(),out=[];
 const dpC=c=>{if(!memo.has(c))memo.set(c,destino(c,plano.get(c)?.n||c,pe));return memo.get(c)};
 const dp=c=>dpC(c);
 for(const e of L){if(e.d<ini||e.d>fim)continue;const deb=e.l.filter(([,v])=>v>0).map(([c,v])=>({c,v})),cred=e.l.filter(([,v])=>v<0).map(([c,v])=>({c,v:-v}));
  // Partidas simples: casa débitos e créditos na ordem (um lançamento composto vira vários pares).
  let i=0,j=0;while(i<deb.length&&j<cred.length){const v=Math.min(deb[i].v,cred[j].v);if(v>=0.005)out.push({d:e.d,deb:dp(deb[i].c)||`?${deb[i].c}`,cred:dp(cred[j].c)||`?${cred[j].c}`,v,h:e.hist,o:e.orig?.tipo,p:/^2\.1\.01/.test(deb[i].c+' '+cred[j].c)?(e.orig?.forn||''):''});deb[i].v-=v;cred[j].v-=v;if(deb[i].v<0.005)i++;if(cred[j].v<0.005)j++}}
 if(modo!=='consolidado')return out;
 const HIST={pedido:'Vendas do dia (marketplaces)',extrato:'Movimento bancário',titulo:'Títulos de fornecedores',provisao:'Provisão de tributos (vendas, IRPJ e CSLL)',venda_direta:'Vendas diretas',nota:'Devoluções de vendas',abertura:'Saldo de abertura',rendimento:'Rendimentos de aplicações'};
 const g=new Map();for(const x of out){const k=[x.d,x.deb,x.cred,x.o,x.p].join('|');const y=g.get(k)||{...x,v:0,h:HIST[x.o]||x.h,n:0};y.v+=x.v;y.n++;g.set(k,y)}return [...g.values()].map(y=>({...y,h:y.n>1?`${y.h} (${y.n} lançamentos)`:y.h}))}

// ─────────── Checklist ───────────
function checklist(m){const ini=m+'-01',fim=mesFim(m),itens=[];const add=(ok,t,s,nav)=>itens.push({ok,t,s,nav});
 const pend=(db.bankTx||[]).filter(t=>t.status==='pendente'&&t.data<=fim);add(!pend.length,'Extrato bancário conciliado até o fim do mês',pend.length?`${pend.length} movimento(s) a conciliar`:'tudo conciliado','concbanco');
 const cc=(db.bankAccounts||[]).filter(a=>a.ativo!==false&&a.saldoExtrato!=null&&window.Tesouraria?.saldoConta);const dif=cc.filter(a=>Math.abs(Tesouraria.saldoConta(a,a.dataSaldoExtrato)-a.saldoExtrato)>=0.01),velho=cc.filter(a=>a.dataSaldoExtrato<fim);const ok=!dif.length&&!velho.length;add(ok,'Saldos bancários batem com o extrato',dif.length?dif.map(a=>a.nome).join(', ')+' diferente do banco':velho.length?'extrato de '+velho.map(a=>a.nome).join(', ')+' não chega ao fim do mês':cc.length+' conta(s) iguais ao extrato','tesouraria');
 const {s:sal}=Contab.saldos(fim,ini),trans=sal.get('9.1.01'),vt=trans?trans.deb-trans.cred:0;add(Math.abs(vt)<0.01,'Nada em conta transitória (a classificar)',Math.abs(vt)<0.01?'zerada':`${money(vt)} sem classificação`,'concbanco');
 const semNf=db.orders.filter(o=>o.date>=ini&&o.date<=fim&&!o.nf).length;add(!semNf,'Pedidos do mês com nota fiscal',semNf?`${semNf} pedido(s) sem nota`:'todos faturados','faturamento');
 const semCat=(db.payables||[]).filter(p=>(p.emissao||p.vencimento||'').startsWith(m)&&!p.categoria).length;add(!semCat,'Títulos do mês com categoria',semCat?`${semCat} sem categoria`:'todos classificados','pagar');
 const pe=planoEscritorio(),us=contasUsadas(ini,fim),sem=us.filter(c=>!destino(c.c,c.n,pe));add(pe.length&&!sem.length,'De-para completo com o plano do escritório',!pe.length?'importe um balancete do escritório para ler o plano de contas':sem.length?`${sem.length} conta(s) sem conta do escritório`:`${us.length} contas mapeadas`,null);
 const tem=(db.accLines||[]).some(l=>l.month===m);add(tem,'Balancete do escritório importado para o mês',tem?'disponível para conferência':'ainda não recebido — a conferência fica pendente','contabil');
 const fech=cfgC().fechados?.[m];return {itens,fech,okTodos:itens.every(i=>i.ok)}}

function view(){if(!window.Contab)return '<div class="empty">Contabilidade automática indisponível.</div>';const m=month,ini=m+'-01',fim=mesFim(m),pe=planoEscritorio();
 const abas=[['checklist','Checklist do mês'],['depara','De-para com o escritório'],['lote','Lote para o escritório'],['confere','Conferência por conta']];
 const head=`<div class="crmbar"><div class="segtabs">${abas.map(([k,t])=>`<button class="${ui.aba===k?'active':''}" data-fc-aba="${k}">${t}</button>`).join('')}</div><span class="caption">Competência ${new Date(m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} — troque no seletor do topo.</span></div>`;
 if(ui.aba==='checklist'){const c=checklist(m);return `${head}<div class="grid two"><section class="card"><div class="cardhead"><h2>${icon('lockbook')} Pronto para fechar?</h2><span class="badge ${c.fech?'ok':c.okTodos?'info':'warn'}">${c.fech?'Fechado':c.okTodos?'Pronto':'Pendências'}</span></div>
  <div class="caption">${c.itens.filter(i=>i.ok).length} de ${c.itens.length} itens ok</div><div class="fcbar"><i style="width:${Math.round(c.itens.filter(i=>i.ok).length/c.itens.length*100)}%"></i></div>
  <div class="checklist">${c.itens.map(i=>`<div class="chk"><span class="avico ${i.ok?'ok':'warn'}">${icon(i.ok?'check':'alert')}</span><div><strong>${i.t}</strong><small>${i.s}</small></div>${i.nav&&!i.ok?`<button class="small" data-nav="${i.nav}">Resolver</button>`:''}</div>`).join('')}</div>
  <div class="row" style="margin-top:12px">${c.fech?`<span class="caption">Fechado por ${esc(c.fech.por)} em ${new Date(c.fech.em).toLocaleString('pt-BR')}.</span><button class="small quiet" data-fc-reabrir="1">Reabrir</button>`:`<button class="primary small" data-fc-fechar="1" ${c.okTodos?'':'title="Há pendências — dá para fechar com ressalva"'}>${icon('check')} Fechar a competência</button>`}<button class="small" data-fc-aba="lote">${icon('download')} Gerar lote</button></div></section>
  <div class="stack">${(()=>{const t=Contab.tributos?.(m),cr=Contab.creditoCompras?.();if(!t)return '';const pct=v=>t.receita?` <small>${(v/t.receita*100).toFixed(2).replace('.',',')}% da receita</small>`:'';
   return `<section class="card"><div class="cardhead"><h2>Tributos provisionados no mês</h2><span class="badge ${/conforme/.test(t.ref)?'ok':'info'}">${/conforme/.test(t.ref)?'igual ao escritório':'estimado'}</span></div><p class="caption">${esc(t.ref)}. Receita ${money(t.receita)}.</p>
   <div class="fctrib">${[['ICMS próprio',t.icms],['DIFAL + FCP',t.difal],['PIS',t.pis],['COFINS',t.cofins],['IRPJ',t.irpj||0],['CSLL',t.csll||0]].map(([k,v])=>`<div><small>${k}</small><strong>${money(v)}</strong>${pct(v)}</div>`).join('')}</div>
   ${cr?`<p class="caption" style="margin-top:10px">Crédito de ICMS nas compras: ${(cr.r*100).toFixed(2).replace('.',',')}% das notas de entrada (${esc(cr.fonte)}), compensado no ICMS próprio do mês.</p>`:''}</section>`})()}
  <section class="card"><h2>Como funciona</h2><p class="caption" style="line-height:1.8">O EcomBalance monta a contabilidade do mês sozinho (vendas, tarifas, CMV, notas, títulos, extrato, provisões). Com o de-para, cada lançamento sai na conta do plano da Escoben, pronto para importar no sistema contábil do escritório — ela revisa em vez de digitar.<br><br>Depois que o escritório processa, o balancete dele volta para cá (Resultado › DRE do escritório) e a aba <strong>Conferência com o escritório</strong> da Contabilidade automática mostra as diferenças linha a linha.</p><button class="small" data-nav="contabauto">Abrir contabilidade automática</button></section></div></div>`}
 if(ui.aba==='depara'){const us=contasUsadas(ini,fim),dp=depara();return `${head}${!pe.length?'<div class="notice warnbox">Nenhum plano do escritório encontrado. Importe um balancete em Resultado › DRE do escritório para o EcomBalance ler as contas.</div>':''}
  <div class="tablebox"><div class="tabletop"><div><h2>De-para · ${us.length} contas usadas no mês</h2><p class="caption">Sugestão automática em cinza (regra conhecida deste plano ou nome parecido). Confirme ou troque; as escolhas valem para todos os meses.</p></div><button class="small primary" data-fc-salvardp="1">${icon('check')} Salvar de-para</button></div><div class="tablewrap"><table><thead><tr><th>Conta EcomBalance</th><th class="num">Débitos</th><th class="num">Créditos</th><th>Conta do escritório</th></tr></thead><tbody>
  ${us.map(c=>{const sug=sugerir(c.c,c.n,pe),atual=dp[c.c]||'';return `<tr><td><span class="mono caption">${c.c}</span> ${esc(c.n)}</td><td class="num">${money(c.deb)}</td><td class="num">${money(c.cred)}</td><td><select data-dp="${c.c}" class="${atual?'':'dpsug'}"><option value="">${sug?'(sugestão abaixo)':'— escolher —'}</option>${pe.map(([k,d])=>`<option value="${k}" ${(atual||sug)===k?'selected':''}>${k} · ${esc(d)}</option>`).join('')}</select>${!atual&&sug?' <span class="badge info">sugerido</span>':!atual?' <span class="badge warn">pendente</span>':''}</td></tr>`}).join('')}</tbody></table></div></div>`}
 if(ui.aba==='confere'){const esc0=(db.accLines||[]).filter(l=>l.month===m&&(l.kind||'balancete')==='balancete'),nomeE=new Map(pe);
  if(!esc0.length)return `${head}<div class="empty">O balancete do escritório de ${new Date(m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})} ainda não foi importado. Quando chegar, a conferência conta a conta aparece aqui.</div>`;
  const nos=new Map();for(const x of lote(ini,fim,'detalhado')){for(const [c,s] of [[x.deb,1],[x.cred,-1]]){if(String(c).startsWith('?'))continue;nos.set(c,(nos.get(c)||0)+s*x.v)}}
  const ele=new Map();for(const l of esc0){const c=l.conta;if(c.split('.').length<5)continue;ele.set(c,(ele.get(c)||0)+(Number(l.debito)||0)-(Number(l.credito)||0))}
  const rows=[...new Set([...nos.keys(),...ele.keys()])].map(c=>({c,n:nomeE.get(c)||'',a:nos.get(c)||0,b:ele.get(c)||0})).map(r=>({...r,d:r.a-r.b})).filter(r=>Math.abs(r.a)>=0.01||Math.abs(r.b)>=0.01).sort((x,y)=>Math.abs(y.d)-Math.abs(x.d));
  const bate=rows.filter(r=>Math.abs(r.d)<Math.max(1,Math.abs(r.b)*0.005)).length;
  return `${head}<div class="tablebox"><div class="tabletop"><div><h2>Conferência por conta · ${bate} de ${rows.length} batem</h2><p class="caption">Movimento do mês (débitos − créditos) que o EcomBalance gera em cada conta do escritório, contra o balancete que o escritório processou. Tolerância de 0,5% ou R$ 1. Ordenado pela maior diferença.</p></div></div><div class="tablewrap"><table><thead><tr><th>Conta do escritório</th><th class="num">EcomBalance</th><th class="num">Escritório</th><th class="num">Diferença</th><th></th></tr></thead><tbody>
  ${rows.map(r=>{const ok=Math.abs(r.d)<Math.max(1,Math.abs(r.b)*0.005);return `<tr><td><span class="mono caption">${r.c}</span> ${esc(r.n)}</td><td class="num">${money(r.a)}</td><td class="num">${money(r.b)}</td><td class="num ${ok?'':'red'}">${money(r.d)}</td><td>${ok?'<span class="badge ok">bate</span>':!r.a?'<span class="badge warn">só no escritório</span>':!r.b?'<span class="badge warn">só no EcomBalance</span>':'<span class="badge warn">diferença</span>'}</td></tr>`}).join('')}</tbody></table></div></div>`}
 const l=lote(ini,fim,ui.modo),tot=l.reduce((s,x)=>s+x.v,0),sem=l.filter(x=>String(x.deb).startsWith('?')||String(x.cred).startsWith('?'));
 return `${head}<div class="crmbar"><div class="segtabs">${[['consolidado','Consolidado por dia'],['detalhado','Detalhado']].map(([k,t])=>`<button class="${ui.modo===k?'active':''}" data-fc-modo="${k}">${t}</button>`).join('')}</div><button class="small primary" data-fc-csv="1">${icon('download')} Exportar lote (CSV)</button><button class="small" data-fc-txt="1">${icon('download')} Exportar TXT (layout padrão)</button></div>
 ${sem.length?`<div class="notice warnbox">${sem.length} partida(s) com conta sem de-para (marcadas com ?). Complete na aba De-para antes de enviar.</div>`:''}
 <div class="tablebox"><div class="tabletop"><div><h2>${l.length.toLocaleString('pt-BR')} partida(s) · ${money(tot)}</h2><p class="caption">Débito = crédito em cada linha. Consolidado soma os lançamentos iguais do dia (ex.: todas as vendas da Shopee do dia numa linha).</p></div></div><div class="tablewrap"><table><thead><tr><th>Data</th><th>Débito</th><th>Crédito</th><th class="num">Valor</th><th>Histórico</th></tr></thead><tbody>
 ${l.slice(0,500).map(x=>`<tr><td>${new Date(x.d+'T12:00:00').toLocaleDateString('pt-BR')}</td><td class="mono ${String(x.deb).startsWith('?')?'red':''}">${esc(x.deb)}</td><td class="mono ${String(x.cred).startsWith('?')?'red':''}">${esc(x.cred)}</td><td class="num">${money(x.v)}</td><td class="caption">${esc(x.h)}${x.p?` · <strong>${esc(x.p)}</strong>`:''}</td></tr>`).join('')}</tbody></table></div>${l.length>500?'<p class="caption" style="padding:10px 18px">Mostrando 500 — a exportação leva todas.</p>':''}</div>`}
function baixar(nome,txt,tipo='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['﻿'+txt],{type:tipo}));a.download=nome;a.click()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-fc-aba],[data-fc-modo],[data-fc-salvardp],[data-fc-fechar],[data-fc-reabrir],[data-fc-csv],[data-fc-txt]');if(!b)return;const d=b.dataset,m=month;
 if(d.fcAba){ui.aba=d.fcAba;render();return}if(d.fcModo){ui.modo=d.fcModo;render();return}
 if(d.fcSalvardp){const dp={...depara()};$$('[data-dp]').forEach(s=>{if(s.value)dp[s.dataset.dp]=s.value});salvarC({depara:dp});audit('De-para contábil salvo',`${Object.keys(dp).length} contas`);toast('De-para salvo.');render();return}
 if(d.fcFechar){const c=checklist(m);const obs=c.okTodos?'':prompt('Há pendências no checklist. Justificativa para fechar com ressalva:');if(!c.okTodos&&!obs)return;salvarC({fechados:{...(cfgC().fechados||{}),[m]:{por:window.Cloud?.session?.user?.email||'—',em:new Date().toISOString(),obs:obs||''}}});audit('Fechamento contábil',`${m}${obs?' com ressalva: '+obs:''}`);toast('Competência fechada.');render();return}
 if(d.fcReabrir){const motivo=prompt('Motivo da reabertura:');if(!motivo)return;const f={...(cfgC().fechados||{})};delete f[m];salvarC({fechados:f});audit('Fechamento contábil reaberto',`${m} · ${motivo}`);render();return}
 const l=lote(m+'-01',mesFim(m),ui.modo),br=v=>v.toFixed(2).replace('.',',');
 if(d.fcCsv){baixar(`lote-contabil-${m}-${ui.modo}.csv`,[['data','conta_debito','conta_credito','valor','historico','participante'],...l.map(x=>[x.d.split('-').reverse().join('/'),x.deb,x.cred,br(x.v),x.h,x.p||''])].map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(';')).join('\n'));audit('Lote contábil exportado',`${m} · ${l.length} partidas · CSV`);return}
 if(d.fcTxt){baixar(`lote-contabil-${m}.txt`,l.map(x=>[x.d.split('-').reverse().join('/'),String(x.deb).replace(/\D/g,''),String(x.cred).replace(/\D/g,''),br(x.v),String(x.h).slice(0,200).replace(/[;\r\n]/g,' '),String(x.p||'').replace(/[;\r\n]/g,' ')].join(';')).join('\r\n'),'text/plain');audit('Lote contábil exportado',`${m} · ${l.length} partidas · TXT`);return}});
addPage('fechcontab','lockbook','Fechamento contábil',view,'Checklist do mês, de-para com o plano do escritório e lote de lançamentos pronto para importar.','',()=>{});
})();
