'use strict';
// CRM: painel de clientes, brinquedos mais vendidos, estados/cidades/regiões (com mapa do Brasil) e
// oportunidades de relacionamento (reativação, recompra, VIPs). Tudo calculado dos pedidos já conciliados.
(()=>{
Object.assign(paths,{heart:'M12 21s-7-4.5-9.5-9A5.5 5.5 0 0 1 12 6a5.5 5.5 0 0 1 9.5 6c-2.5 4.5-9.5 9-9.5 9z',map:'M9 4 3 6v14l6-2 6 2 6-2V4l-6 2z M9 4v14 M15 6v14',target:'M12 21a9 9 0 1 1 0-18 9 9 0 0 1 0 18z M12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8z M12 12h.01',gift:'M4 11h16v10H4z M3 7h18v4H3z M12 7v14 M12 7s-1.5-4-4-4a2 2 0 0 0 0 4z M12 7s1.5-4 4-4a2 2 0 0 1 0 4z'});
const REG={AC:'Norte',AM:'Norte',AP:'Norte',PA:'Norte',RO:'Norte',RR:'Norte',TO:'Norte',AL:'Nordeste',BA:'Nordeste',CE:'Nordeste',MA:'Nordeste',PB:'Nordeste',PE:'Nordeste',PI:'Nordeste',RN:'Nordeste',SE:'Nordeste',DF:'Centro-Oeste',GO:'Centro-Oeste',MS:'Centro-Oeste',MT:'Centro-Oeste',ES:'Sudeste',MG:'Sudeste',RJ:'Sudeste',SP:'Sudeste',PR:'Sul',RS:'Sul',SC:'Sul'};
// Mapa do Brasil em "blocos" (cartograma): cada estado numa célula da grade, na posição aproximada.
const GRADE={RR:[3,0],AP:[5,0],AM:[2,1],PA:[4,1],MA:[5,1],CE:[6,1],RN:[7,1],AC:[1,2],RO:[2,2],TO:[4,2],PI:[5,2],PB:[7,2],PE:[6,2],MT:[3,3],GO:[4,3],BA:[5,3],AL:[7,3],SE:[6,3],DF:[4,4],MG:[5,4],ES:[6,4],MS:[3,4],SP:[4,5],RJ:[5,5],PR:[3,6],SC:[4,6],RS:[3,7]};
const ui={periodo:'12m',plat:'',rank:'receita',uf:'',geo:'estados',acao:'reativar'};
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const dias=d=>Math.round((new Date(hoje()+'T12:00:00')-new Date(d+'T12:00:00'))/864e5);
const nf=n=>Number(n||0).toLocaleString('pt-BR');
const pctf=n=>(Number.isFinite(n)?n:0).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%';
const ufDe=o=>String(o.state||o.customer?.state||'').toUpperCase().slice(0,2);
const cidadeDe=o=>String(o.customer?.city||'').trim();
const chave=o=>{const c=o.customer;if(!c)return null;const d=String(c.doc||'').replace(/\D/g,'');if(d.length>=11)return 'DOC-'+d;if(c.id&&!/-(undefined|null|)$/.test(c.id))return String(c.id);if(c.name)return 'NOME-'+normalized(c.name).replace(/\s+/g,'-');return null};
function pedidos(){const h=hoje();let r=db.orders;if(ui.periodo==='mes')r=r.filter(o=>o.date.startsWith(month));else if(ui.periodo!=='tudo'){const n={'3m':90,'6m':182,'12m':365}[ui.periodo];const lim=new Date(Date.now()-n*864e5).toLocaleDateString('sv-SE');r=r.filter(o=>o.date>=lim&&o.date<=h)}return ui.plat?r.filter(o=>o.platform===ui.plat):r}
let cache=null,cacheKey='';
function clientes(){const k=db.orders.length+'|'+(db.orders.at(-1)?.id||'');if(cache&&cacheKey===k)return cache;const map=new Map(),h=hoje();
 for(const o of db.orders){const key=chave(o);if(!key)continue;const c=map.get(key)||{key,nome:'',doc:'',cidade:'',uf:'',pedidos:[],total:0,canais:new Set()};const s=o.customer||{};c.nome=c.nome||s.name||'';c.doc=c.doc||s.doc||'';c.cidade=c.cidade||s.city||'';c.uf=c.uf||ufDe(o);c.pedidos.push(o);c.total+=o.gross;c.canais.add(o.platform);map.set(key,c)}
 const l=[...map.values()].map(c=>{c.pedidos.sort((a,b)=>a.date.localeCompare(b.date));const ult=c.pedidos.at(-1).date;return {...c,total:round(c.total),n:c.pedidos.length,ticket:round(c.total/c.pedidos.length),primeira:c.pedidos[0].date,ultima:ult,recencia:dias(ult),canais:[...c.canais],crm:db.crm?.[c.key]||{}}});
 const tot=l.map(c=>c.total).sort((a,b)=>a-b),p90=tot[Math.floor(tot.length*.9)]??Infinity;for(const c of l)c.seg=c.recencia>180?'Inativo':c.recencia>90?'Em risco':c.n>=2&&c.total>=p90?'VIP':c.n>=2?'Recorrente':'Novo';
 cache=l;cacheKey=k;return l}
function rankProdutos(rows){const m=new Map();for(const o of rows)for(const it of o.items||[]){const k=normalized(it.sku||it.title)||'?';const p=m.get(k)||{sku:it.sku||'',titulo:it.title||it.sku||'Sem descrição',qtd:0,receita:0,pedidos:new Set(),canais:{},ufs:{}};const q=Number(it.qty)||0,v=q*(Number(it.price)||0);p.qtd+=q;p.receita+=v;p.pedidos.add(o.id);p.canais[o.platform]=(p.canais[o.platform]||0)+v;const uf=ufDe(o);if(uf)p.ufs[uf]=(p.ufs[uf]||0)+q;m.set(k,p)}
 return [...m.values()].map(p=>({...p,qtd:round(p.qtd),receita:round(p.receita),pedidos:p.pedidos.size,uf:Object.entries(p.ufs).sort((a,b)=>b[1]-a[1])[0]?.[0]||''}))}
function porUF(rows){const m={};for(const o of rows){const uf=ufDe(o);if(!uf)continue;const s=m[uf]||(m[uf]={uf,pedidos:0,receita:0,clientes:new Set(),cidades:{}});s.pedidos++;s.receita+=o.gross;const k=chave(o);if(k)s.clientes.add(k);const c=cidadeDe(o);if(c)s.cidades[c]=(s.cidades[c]||0)+o.gross}return m}

// ─────────────── Componentes visuais ───────────────
const filtros=(extra='')=>`<div class="toolbar"><div class="segtabs">${[['mes','Mês'],['3m','3 meses'],['6m','6 meses'],['12m','12 meses'],['tudo','Tudo']].map(([k,t])=>`<button class="${ui.periodo===k?'on':''}" data-crm-per="${k}">${t}</button>`).join('')}</div><select data-crm-plat aria-label="Canal"><option value="">Todos os canais</option>${['Mercado Livre','Shopee','Magalu'].map(p=>`<option ${ui.plat===p?'selected':''}>${p}</option>`).join('')}</select>${extra}<span style="flex:1"></span><span class="caption">${ui.periodo==='mes'?new Date(month+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):''}</span></div>`;
const kpi=(l,v,s,tom='')=>`<div class="card kpi"><span class="kpil">${l}</span><span class="kpiv ${tom}">${v}</span><span class="kpis">${s}</span></div>`;
function barras(l,val,lab,cor='var(--accent)',fmt=money){const max=Math.max(1,...l.map(val));return l.map(x=>`<div class="hrow"><span class="hlab" title="${esc(lab(x))}">${esc(lab(x))}</span><span class="htrack"><i style="width:${val(x)/max*100}%;background:${cor}"></i></span><strong>${fmt(val(x))}</strong></div>`).join('')}
function mapaBrasil(m,campo='receita',sel=''){const max=Math.max(1,...Object.values(m).map(s=>s[campo]));
 return `<div class="brmap" role="img" aria-label="Mapa do Brasil por ${campo}">${Object.entries(GRADE).map(([uf,[x,y]])=>{const s=m[uf],v=s?s[campo]:0,a=v?0.15+0.85*Math.sqrt(v/max):0;return `<button class="uf ${sel===uf?'sel':''}" style="grid-column:${x+1};grid-row:${y+1};background:${v?`rgba(168,138,255,${a.toFixed(2)})`:'var(--panel2)'};color:${a>0.55?'#170e31':'var(--text)'}" data-crm-uf="${uf}" title="${uf} · ${s?money(s.receita)+' · '+nf(s.pedidos)+' pedidos':'sem vendas'}"><b>${uf}</b><small>${s?(campo==='receita'?(s.receita>=1000?(s.receita/1000).toLocaleString('pt-BR',{maximumFractionDigits:0})+'k':Math.round(s.receita)):nf(s[campo])):''}</small></button>`}).join('')}</div>`}
function linhaMensal(){const meses=[...new Set(db.orders.map(o=>o.date.slice(0,7)))].sort().slice(-12);const cl=clientes();const primeiro=new Map(cl.map(c=>[c.key,c.primeira.slice(0,7)]));
 const dados=meses.map(m=>{const ks=new Set(db.orders.filter(o=>o.date.startsWith(m)&&(!ui.plat||o.platform===ui.plat)).map(chave).filter(Boolean));let novos=0,rec=0;for(const k of ks)primeiro.get(k)===m?novos++:rec++;return {m,novos,rec}});const max=Math.max(1,...dados.map(d=>d.novos+d.rec));
 return `<div class="colchart2">${dados.map(d=>`<div class="col2" title="${d.m}: ${d.novos} novos · ${d.rec} recorrentes"><div class="stack"><i class="rec" style="height:${d.rec/max*100}%"></i><i class="nov" style="height:${d.novos/max*100}%"></i></div><small>${new Date(d.m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></div>`).join('')}</div><div class="legend" style="margin-top:10px"><span><i style="background:var(--accent)"></i>Novos</span><span><i style="background:var(--green)"></i>Recorrentes</span></div>`}

// ─────────────── Telas ───────────────
function painelView(){const rows=pedidos(),ks=new Set(rows.map(chave).filter(Boolean)),cl=clientes().filter(c=>ks.has(c.key)),rec=cl.filter(c=>c.n>=2).length,receita=round(rows.reduce((a,o)=>a+o.gross,0));
 const novosPer=cl.filter(c=>rows.some(o=>chave(o)===c.key&&o.date===c.primeira)).length,uf=porUF(rows),top=rankProdutos(rows).sort((a,b)=>b.receita-a.receita).slice(0,8),segs=['VIP','Recorrente','Novo','Em risco','Inativo'].map(s=>[s,cl.filter(c=>c.seg===s).length]);
 const regioes={};for(const s of Object.values(uf)){const r=REG[s.uf]||'—';regioes[r]=(regioes[r]||0)+s.receita}
 return filtros()+`<div class="grid kpis4">${kpi('Clientes compradores',nf(cl.length),`${nf(novosPer)} novos no período`)}${kpi('Recompra',pctf(cl.length?rec/cl.length*100:0),`${nf(rec)} clientes com 2+ pedidos`,'green')}${kpi('Ticket médio',money(rows.length?receita/rows.length:0),`${nf(rows.length)} pedidos`)}${kpi('Valor por cliente',money(cl.length?receita/cl.length:0),'receita ÷ clientes (LTV no período)','gold')}</div>
 <div class="grid crm2"><section class="card"><div class="cardhead"><div><h2>Onde estão seus clientes</h2><p class="caption">Receita por estado · clique num estado para ver cidades</p></div><button class="small quiet" data-nav="crmgeo">Detalhar ${icon('arrow')}</button></div>${mapaBrasil(uf)}
  <div class="grid three minis">${['Sudeste','Sul','Nordeste','Centro-Oeste','Norte'].map(r=>`<div><small>${r}</small><strong>${pctf(receita?(regioes[r]||0)/receita*100:0)}</strong><small>${money(regioes[r]||0)}</small></div>`).join('')}</div></section>
 <section class="card"><div class="cardhead"><div><h2>Brinquedos mais vendidos</h2><p class="caption">Por receita no período</p></div><button class="small quiet" data-nav="crmprodutos">Ranking ${icon('arrow')}</button></div>${top.length?barras(top,x=>x.receita,x=>x.titulo):'<p class="caption">Sem itens nos pedidos do período.</p>'}</section></div>
 <div class="grid crm2" style="margin-top:18px"><section class="card"><div class="cardhead"><div><h2>Clientes novos × recorrentes</h2><p class="caption">Últimos 12 meses</p></div></div>${linhaMensal()}</section>
 <section class="card"><div class="cardhead"><h2>Segmentos</h2><button class="small quiet" data-nav="clientes">Clientes ${icon('arrow')}</button></div>${segs.map(([s,n])=>`<div class="listline"><span><span class="badge ${{VIP:'info',Recorrente:'ok',Novo:'',['Em risco']:'warn',Inativo:'bad'}[s]}">${s}</span></span><strong>${nf(n)}</strong></div>`).join('')}
  <button class="primary small" style="margin-top:14px" data-nav="crmacoes">${icon('target')} Ver oportunidades</button></section></div>`}

function produtosView(){const rows=pedidos().filter(o=>!ui.uf||ufDe(o)===ui.uf),l=rankProdutos(rows).sort((a,b)=>ui.rank==='qtd'?b.qtd-a.qtd:b.receita-a.receita),tot=l.reduce((a,p)=>a+p.receita,0)||1;
 // Tendência: receita do produto nos últimos 30 dias × 30 dias anteriores.
 const d30=new Date(Date.now()-30*864e5).toLocaleDateString('sv-SE'),d60=new Date(Date.now()-60*864e5).toLocaleDateString('sv-SE');const r30=rankProdutos(db.orders.filter(o=>o.date>=d30)),r60=rankProdutos(db.orders.filter(o=>o.date>=d60&&o.date<d30));const t=p=>{const a=r30.find(x=>x.sku===p.sku&&x.titulo===p.titulo)?.receita||0,b=r60.find(x=>x.sku===p.sku&&x.titulo===p.titulo)?.receita||0;return b?(a-b)/b*100:a?100:0};
 let acum=0;return filtros(`<select data-crm-rank aria-label="Ordenar"><option value="receita" ${ui.rank==='receita'?'selected':''}>Por receita</option><option value="qtd" ${ui.rank==='qtd'?'selected':''}>Por quantidade</option></select><select data-crm-ufsel aria-label="Estado"><option value="">Todos os estados</option>${Object.keys(REG).sort().map(u=>`<option ${ui.uf===u?'selected':''}>${u}</option>`).join('')}</select>`)+
 `<div class="grid kpis4">${kpi('Produtos vendidos',nf(l.length),'SKUs com venda no período')}${kpi('Unidades',nf(l.reduce((a,p)=>a+p.qtd,0)),'itens vendidos')}${kpi('Top 10 = ',pctf(l.slice(0,10).reduce((a,p)=>a+p.receita,0)/tot*100),'da receita de produtos','gold')}${kpi('Campeão',esc((l[0]?.titulo||'—').slice(0,28)),l[0]?money(l[0].receita):'','green')}</div>
 <div class="tablebox"><div class="tabletop"><h2>Ranking de brinquedos${ui.uf?' · '+ui.uf:''}</h2><button class="small" data-crm-csv="produtos">${icon('download')} Exportar</button></div><div class="tablewrap"><table><thead><tr><th>#</th><th>Brinquedo</th><th class="num">Unidades</th><th class="num">Receita</th><th class="num">%</th><th class="num">Curva</th><th>Canais</th><th>Estado líder</th><th class="num">30 dias</th></tr></thead><tbody>${l.slice(0,200).map((p,i)=>{acum+=p.receita;const cv=acum/tot<=.8?'A':acum/tot<=.95?'B':'C',tr=t(p);return `<tr><td class="caption">${i+1}</td><td><strong>${esc(p.titulo)}</strong><br><span class="caption mono">${esc(p.sku)}</span></td><td class="num">${nf(p.qtd)}</td><td class="num">${money(p.receita)}</td><td class="num">${pctf(p.receita/tot*100)}</td><td class="num"><span class="badge ${cv==='A'?'ok':cv==='B'?'warn':''}">${cv}</span></td><td class="caption">${Object.entries(p.canais).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`${c.replace('Mercado Livre','ML')} ${pctf(v/p.receita*100)}`).join(' · ')}</td><td>${p.uf||'—'}</td><td class="num ${tr>5?'green':tr<-5?'red':''}">${tr>0?'▲':tr<0?'▼':'•'} ${pctf(Math.abs(tr))}</td></tr>`}).join('')||'<tr><td colspan="9" class="empty">Sem vendas no período.</td></tr>'}</tbody></table></div></div>`}

function geoView(){const rows=pedidos(),m=porUF(rows),tot=rows.reduce((a,o)=>a+o.gross,0)||1,sel=ui.uf;
 const cidades={};for(const o of rows){const uf=ufDe(o),c=cidadeDe(o);if(!c||(sel&&uf!==sel))continue;const k=c+' / '+uf,x=cidades[k]||(cidades[k]={cidade:c,uf,pedidos:0,receita:0,clientes:new Set()});x.pedidos++;x.receita+=o.gross;const kk=chave(o);if(kk)x.clientes.add(kk)}
 const cl=Object.values(cidades).sort((a,b)=>b.receita-a.receita),ufs=Object.values(m).sort((a,b)=>b.receita-a.receita),regs={};for(const s of ufs){const r=REG[s.uf]||'—',x=regs[r]||(regs[r]={r,receita:0,pedidos:0,clientes:0});x.receita+=s.receita;x.pedidos+=s.pedidos;x.clientes+=s.clientes.size}
 return filtros()+`<div class="grid crm2"><section class="card"><div class="cardhead"><div><h2>Mapa de vendas</h2><p class="caption">${sel?`Estado selecionado: <strong>${sel}</strong> · <button class="quiet small" data-crm-uf="">limpar</button>`:'Clique num estado para filtrar as cidades'}</p></div></div>${mapaBrasil(m,'receita',sel)}</section>
 <section class="card"><div class="cardhead"><h2>Regiões</h2></div>${Object.values(regs).sort((a,b)=>b.receita-a.receita).map(x=>`<div class="hrow"><span class="hlab">${x.r}</span><span class="htrack"><i style="width:${x.receita/tot*100}%;background:var(--accent)"></i></span><strong>${pctf(x.receita/tot*100)}</strong></div><p class="caption" style="margin:-4px 0 10px">${money(x.receita)} · ${nf(x.pedidos)} pedidos · ${nf(x.clientes)} clientes · ticket ${money(x.receita/x.pedidos)}</p>`).join('')}</section></div>
 <div class="grid crm2" style="margin-top:18px"><div class="tablebox"><div class="tabletop"><h2>Estados</h2><button class="small" data-crm-csv="estados">${icon('download')} Exportar</button></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>UF</th><th>Região</th><th class="num">Pedidos</th><th class="num">Clientes</th><th class="num">Receita</th><th class="num">%</th><th class="num">Ticket</th></tr></thead><tbody>${ufs.map(s=>`<tr class="clk ${sel===s.uf?'sel':''}" data-crm-uf="${s.uf}"><td><strong>${s.uf}</strong></td><td class="caption">${REG[s.uf]||''}</td><td class="num">${nf(s.pedidos)}</td><td class="num">${nf(s.clientes.size)}</td><td class="num">${money(s.receita)}</td><td class="num">${pctf(s.receita/tot*100)}</td><td class="num">${money(s.receita/s.pedidos)}</td></tr>`).join('')}</tbody></table></div></div>
 <div class="tablebox"><div class="tabletop"><h2>Cidades${sel?' · '+sel:''}</h2><button class="small" data-crm-csv="cidades">${icon('download')} Exportar</button></div><div class="tablewrap" style="max-height:520px"><table><thead><tr><th>Cidade</th><th class="num">Pedidos</th><th class="num">Clientes</th><th class="num">Receita</th></tr></thead><tbody>${cl.slice(0,300).map(c=>`<tr><td><strong>${esc(c.cidade)}</strong> <span class="caption">${c.uf}</span></td><td class="num">${nf(c.pedidos)}</td><td class="num">${nf(c.clientes.size)}</td><td class="num">${money(c.receita)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">Sem cidade informada nos pedidos.</td></tr>'}</tbody></table></div></div></div>`}

const ACOES={reativar:['Reativar inativos','Compraram 2+ vezes e sumiram há mais de 90 dias',c=>c.n>=2&&c.recencia>90],vip:['VIPs sem compra recente','Maiores clientes sem pedido há mais de 45 dias',c=>c.seg==='VIP'&&c.recencia>45],recompra:['Janela de recompra','Primeira compra entre 25 e 60 dias atrás e ainda não voltaram',c=>c.n===1&&c.recencia>=25&&c.recencia<=60],fieis:['Mais fiéis','3 ou mais pedidos — candidatos a programa de fidelidade',c=>c.n>=3]};
function acoesView(){const cl=clientes(),[t,d,f]=ACOES[ui.acao],l=cl.filter(f).sort((a,b)=>b.total-a.total);
 return `<div class="grid kpis4">${Object.entries(ACOES).map(([k,[tt,dd,ff]])=>`<button class="card kpi kpibtn ${ui.acao===k?'on':''}" data-crm-acao="${k}"><span class="kpil">${tt}</span><span class="kpiv">${nf(cl.filter(ff).length)}</span><span class="kpis">${dd}</span></button>`).join('')}</div>
 <div class="tablebox"><div class="tabletop"><div><h2>${t}</h2><p class="caption">${d}. Os contatos ficam nas plataformas; use a lista para campanhas (cupom, anúncio, pós-venda).</p></div><button class="small primary" data-crm-csv="acao">${icon('download')} Exportar lista</button></div><div class="tablewrap"><table><thead><tr><th>Cliente</th><th>Cidade</th><th class="num">Pedidos</th><th class="num">Total</th><th>Última compra</th><th>Canais</th><th>Segmento</th></tr></thead><tbody>${l.slice(0,400).map(c=>`<tr class="clk" data-crm-cliente="${esc(c.key)}"><td><strong>${esc(c.nome||'—')}</strong><br><span class="caption">${esc(c.doc||'')}</span></td><td>${esc(c.cidade)} <span class="caption">${c.uf}</span></td><td class="num">${c.n}</td><td class="num">${money(c.total)}</td><td>${new Date(c.ultima+'T12:00:00').toLocaleDateString('pt-BR')} <span class="caption">(${c.recencia} dias)</span></td><td class="caption">${c.canais.join(', ')}</td><td><span class="badge">${c.seg}</span></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Ninguém nesta lista agora.</td></tr>'}</tbody></table></div></div>`}

addPage('crm','heart','Painel do CRM',painelView,'Quem compra, o que compra e de onde — e onde agir para vender mais para quem já é cliente.','',bind);
addPage('crmprodutos','gift','Mais vendidos',produtosView,'Ranking por receita ou quantidade, curva ABC, canais, estado líder e tendência dos últimos 30 dias.','',bind);
addPage('crmgeo','map','Estados e cidades',geoView,'Mapa de vendas do Brasil, regiões, estados e cidades com clientes e ticket médio.','',bind);
addPage('crmacoes','target','Oportunidades',acoesView,'Listas prontas para reativar, recomprar e fidelizar clientes.','',bind);
function bind(){$$('[data-crm-plat]').forEach(s=>s.onchange=()=>{ui.plat=s.value;render()});$$('[data-crm-rank]').forEach(s=>s.onchange=()=>{ui.rank=s.value;render()});$$('[data-crm-ufsel]').forEach(s=>s.onchange=()=>{ui.uf=s.value;render()})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-crm-per],[data-crm-uf],[data-crm-acao],[data-crm-csv],[data-crm-cliente]');if(!b)return;const d=b.dataset;
 if(d.crmPer){ui.periodo=d.crmPer;render();return}
 if(d.crmUf!==undefined){ui.uf=ui.uf===d.crmUf?'':d.crmUf;if(page==='crm'&&ui.uf)navigate('crmgeo');else render();return}
 if(d.crmAcao){ui.acao=d.crmAcao;render();return}
 if(d.crmCliente){navigate('clientes');return}
 if(d.crmCsv){const rows=pedidos();let out;if(d.crmCsv==='produtos')out=[['sku','produto','unidades','receita','pedidos','estado_lider'],...rankProdutos(rows).sort((a,b)=>b.receita-a.receita).map(p=>[p.sku,p.titulo,p.qtd,p.receita,p.pedidos,p.uf])];
  else if(d.crmCsv==='estados')out=[['uf','regiao','pedidos','clientes','receita'],...Object.values(porUF(rows)).map(s=>[s.uf,REG[s.uf]||'',s.pedidos,s.clientes.size,round(s.receita)])];
  else if(d.crmCsv==='cidades'){const c={};for(const o of rows){const k=cidadeDe(o)+'|'+ufDe(o);if(!cidadeDe(o))continue;const x=c[k]||(c[k]=[cidadeDe(o),ufDe(o),0,0]);x[2]++;x[3]=round(x[3]+o.gross)}out=[['cidade','uf','pedidos','receita'],...Object.values(c)]}
  else{const [t,,f]=ACOES[ui.acao];out=[['cliente','documento','cidade','uf','pedidos','total','ultima_compra','canais','segmento'],...clientes().filter(f).map(c=>[c.nome,c.doc,c.cidade,c.uf,c.n,c.total,c.ultima,c.canais.join(' '),c.seg])]}
  download(`EcomBalance_CRM_${d.crmCsv}.csv`,csv(out))}});
})();
