'use strict';
// Devoluções: notas de devolução (Bling) ligadas ao pedido original pelo CPF/CNPJ do cliente e pelo SKU,
// taxa de devolução por produto e por canal, prazo entre venda e devolução e notas rejeitadas que precisam
// ser corrigidas. Junta com o Atendimento (reclamações de devolução) para fechar o ciclo.
(()=>{
Object.assign(paths,{undo:'M9 14 4 9l5-5 M4 9h11a5 5 0 0 1 0 10h-4'});
const ui={periodo:90,aba:'produtos',busca:''};
const dig=s=>String(s||'').replace(/\D/g,'');
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const menos=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toLocaleDateString('sv-SE')};
const dBR=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const pct=v=>(v*100).toFixed(1).replace('.',',')+'%';
let cache=null;
function dados(){const k=[db.orders.length,(db.purchases||[]).length,ui.periodo].join('|');if(cache?.k===k)return cache.v;
 const ini=menos(ui.periodo),porDoc=new Map();for(const o of db.orders){const d=dig(o.customer?.doc);if(d)(porDoc.get(d)||porDoc.set(d,[]).get(d)).push(o)}
 const devs=(db.purchases||[]).filter(n=>n.tipo==='devolucao'&&n.emissao>=ini).map(n=>{const cand=(porDoc.get(dig(n.fornecedorDoc||n.fornecedor_doc))||[]).filter(o=>o.date<=n.emissao).sort((a,b)=>b.date.localeCompare(a.date));
  const skus=new Set((n.itens||[]).map(i=>String(i.sku||'').trim()));const orig=cand.find(o=>(o.items||[]).some(i=>skus.has(String(i.sku||'').trim())))||cand[0]||null;
  return {n,orig,dias:orig?Math.round((new Date(n.emissao+'T12:00:00')-new Date(orig.date+'T12:00:00'))/864e5):null,rejeitada:/rejeit|cancel|denegad/i.test(n.situacao||'')}});
 const vend=new Map(),dev=new Map(),canal=new Map();
 for(const o of db.orders){if(o.date<ini)continue;const c=canal.get(o.platform)||{v:0,d:0,vd:0};c.v+=o.gross;canal.set(o.platform,c);for(const it of o.items||[]){const s=String(it.sku||'').trim();if(!s)continue;const x=vend.get(s)||{q:0,t:it.title||s};x.q+=Number(it.qty)||0;vend.set(s,x)}}
 for(const d of devs){if(d.rejeitada)continue;if(d.orig){const c=canal.get(d.orig.platform)||{v:0,d:0,vd:0};c.d++;c.vd+=Number(d.n.valor)||0;canal.set(d.orig.platform,c)}for(const it of d.n.itens||[]){const s=String(it.sku||'').trim();const x=dev.get(s)||{q:0,v:0,t:it.descricao||s};x.q+=Number(it.qtd)||0;x.v+=Number(it.total)||0;dev.set(s,x)}}
 const prods=[...dev].map(([s,x])=>({sku:s,nome:vend.get(s)?.t||x.t,dev:x.q,valor:x.v,vend:vend.get(s)?.q||0})).map(p=>({...p,taxa:p.vend?p.dev/p.vend:null})).sort((a,b)=>(b.taxa??0)-(a.taxa??0)||b.dev-a.dev);
 cache={k,v:{devs,prods,canal}};return cache.v}
function view(){const {devs,prods,canal}=dados(),ok=devs.filter(d=>!d.rejeitada),rej=devs.filter(d=>d.rejeitada);
 const itensDev=prods.reduce((s,p)=>s+p.dev,0),itensVend=[...db.orders].filter(o=>o.date>=menos(ui.periodo)).reduce((s,o)=>s+(o.items||[]).reduce((x,i)=>x+(Number(i.qty)||0),0),0);
 const prazos=ok.filter(d=>d.dias!=null).map(d=>d.dias).sort((a,b)=>a-b),med=prazos.length?prazos[Math.floor(prazos.length/2)]:null;
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">Devoluções (${ui.periodo} dias)</span><span class="kpiv">${ok.length}</span><span class="kpis">${money(ok.reduce((s,d)=>s+(Number(d.n.valor)||0),0))} em notas</span></div><div class="card kpi"><span class="kpil">Taxa de devolução</span><span class="kpiv ${itensVend&&itensDev/itensVend>0.03?'red':''}">${itensVend?pct(itensDev/itensVend):'—'}</span><span class="kpis">${itensDev} de ${itensVend.toLocaleString('pt-BR')} itens vendidos</span></div><div class="card kpi"><span class="kpil">Prazo venda → devolução</span><span class="kpiv">${med!=null?med+' dias':'—'}</span><span class="kpis">mediana · ${ok.filter(d=>d.orig).length} ligadas ao pedido</span></div><div class="card kpi"><span class="kpil">Notas rejeitadas</span><span class="kpiv ${rej.length?'red':''}">${rej.length}</span><span class="kpis">${rej.length?'corrigir e reemitir no Bling':'nenhuma'}</span></div></div>
 ${rej.length?`<div class="notice warnbox"><strong>${rej.length} nota(s) de devolução rejeitada(s) pela SEFAZ</strong> — sem nota válida o estoque e o crédito do imposto não entram. ${rej.map(d=>`NF ${esc(d.n.numero)} · ${esc(d.n.fornecedor)} (${dBR(d.n.emissao)})`).join(' · ')}</div>`:''}
 <div class="crmbar"><div class="segtabs">${[['produtos','Por produto'],['lista','Devoluções'],['canais','Por canal']].map(([k,t])=>`<button class="${ui.aba===k?'active':''}" data-dv-aba="${k}">${t}</button>`).join('')}</div><select data-dv-periodo aria-label="Período">${[30,90,180,365].map(n=>`<option value="${n}" ${ui.periodo===n?'selected':''}>Últimos ${n} dias</option>`).join('')}</select>${ui.aba==='lista'?`<div class="searchin">${icon('search')}<input type="search" id="dvBusca" placeholder="Cliente, produto, nota…" value="${esc(ui.busca)}"></div>`:''}<button class="small quiet" data-nav="atendimento">${icon('headset')} Reclamações no Atendimento</button></div>
 ${ui.aba==='produtos'?`<div class="tablebox"><div class="tabletop"><div><h2>Taxa de devolução por produto</h2><p class="caption">Acima de 3% merece olhar: embalagem, descrição do anúncio, peça faltando ou defeito recorrente.</p></div></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th class="num">Vendidos</th><th class="num">Devolvidos</th><th class="num">Taxa</th><th class="num">Valor devolvido</th></tr></thead><tbody>
  ${prods.map(p=>`<tr class="clickrow" data-est-ficha="${esc(p.sku)}"><td><strong>${esc(p.nome)}</strong><br><span class="caption mono">${esc(p.sku)}</span></td><td class="num">${p.vend.toLocaleString('pt-BR')}</td><td class="num">${p.dev}</td><td class="num"><span class="badge ${p.taxa==null?'':p.taxa>0.05?'bad':p.taxa>0.03?'warn':'ok'}">${p.taxa==null?'—':pct(p.taxa)}</span></td><td class="num">${money(p.valor)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhuma devolução no período.</td></tr>'}</tbody></table></div></div>`
 :ui.aba==='canais'?`<div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Canal</th><th class="num">Vendas</th><th class="num">Devoluções</th><th class="num">Valor devolvido</th><th class="num">% do faturamento</th></tr></thead><tbody>${[...canal].sort((a,b)=>b[1].v-a[1].v).map(([c,x])=>`<tr><td><strong>${esc(c)}</strong></td><td class="num">${money(x.v)}</td><td class="num">${x.d}</td><td class="num">${money(x.vd)}</td><td class="num">${x.v?pct(x.vd/x.v):'—'}</td></tr>`).join('')}</tbody></table></div><p class="caption" style="padding:10px 18px">Canal pelo pedido original (ligado pelo CPF/CNPJ e SKU). ${devs.filter(d=>!d.orig&&!d.rejeitada).length} devolução(ões) sem pedido encontrado.</p></div>`
 :(()=>{const q=normalized(ui.busca);const l=devs.filter(d=>!q||normalized([d.n.fornecedor,d.n.numero,(d.n.itens||[]).map(i=>i.descricao).join(' ')].join(' ')).includes(q)).sort((a,b)=>b.n.emissao.localeCompare(a.n.emissao));
   return `<div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Nota</th><th>Cliente</th><th>Itens</th><th>Pedido original</th><th class="num">Dias</th><th>Situação</th><th class="num">Valor</th></tr></thead><tbody>
   ${l.slice(0,400).map(d=>`<tr ${d.orig?`class="clickrow" data-order="${esc(d.orig.id)}"`:''}><td>${dBR(d.n.emissao)}<br><span class="caption mono">NF ${esc(d.n.numero||'')}</span></td><td>${esc(d.n.fornecedor||'')}</td><td class="caption">${esc((d.n.itens||[]).map(i=>`${i.qtd}× ${i.descricao}`).join(' · '))}</td><td>${d.orig?`<span class="mono">${esc(d.orig.id)}</span><br><span class="caption">${esc(d.orig.platform)} · ${dBR(d.orig.date)}</span>`:'<span class="caption">não encontrado</span>'}</td><td class="num">${d.dias??'—'}</td><td><span class="badge ${d.rejeitada?'bad':/autoriz|danfe/i.test(d.n.situacao||'')?'ok':''}">${esc(d.n.situacao||'—')}</span></td><td class="num">${money(Number(d.n.valor)||0)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nenhuma devolução.</td></tr>'}</tbody></table></div></div>`})()}`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-dv-aba]');if(b){ui.aba=b.dataset.dvAba;render()}});
function bind(){const s=$('[data-dv-periodo]');if(s)s.onchange=()=>{ui.periodo=Number(s.value);cache=null;render()};const i=$('#dvBusca');if(i)i.oninput=e=>{ui.busca=e.target.value;const pos=e.target.selectionStart;render();const n=$('#dvBusca');n.focus();n.setSelectionRange(pos,pos)}}
addPage('devolucoes','undo','Devoluções',view,'Taxa de devolução por produto e canal, devoluções ligadas ao pedido original e notas rejeitadas.','',bind);
window.Devolucoes={avisos:()=>{const r=(db.purchases||[]).filter(n=>n.tipo==='devolucao'&&/rejeit|denegad/i.test(n.situacao||'')&&n.emissao>=menos(60));return r.length?[['bad','undo',`${r.length} nota(s) de devolução rejeitada(s)`,'Corrigir e reemitir no Bling','devolucoes']]:[]}};
})();
