'use strict';
// Faturamento: pedidos pagos que ainda não têm nota fiscal (com idade e prazo de postagem em risco), ritmo de
// emissão por dia e canal e a EMISSÃO DE NF-e pelo EcomBalance (Focus NFe): configuração fiscal, nota de teste
// em homologação, lista de notas com DANFE/XML, consulta e cancelamento. Produção só com confirmação.
(()=>{
Object.assign(paths,{receipt:paths.receipt||'M6 3h12v18l-3-2-3 2-3-2-3 2z M9 8h6 M9 12h6'});
const ui={canal:'',dias:14,aba:'monitor'};
const nfe={status:null,notas:null,carregando:false,erro:'',tentou:false};
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const menos=n=>{const d=new Date();d.setDate(d.getDate()-n);return d.toLocaleDateString('sv-SE')};
const idadeH=d=>(Date.now()-new Date(d+'T12:00:00'))/3600e3;
const PADRAO={ambiente:'homologacao',serie:'2',natureza:'Venda de mercadoria',cfop_interno:'5102',cfop_interestadual:'6108',cst_icms:'00',aliq_icms_interna:17,cst_pis:'01',aliq_pis:0.65,cst_cofins:'01',aliq_cofins:3,modalidade_frete:0,difal:true};
const STATUS={autorizado:['Autorizada','ok'],processando_autorizacao:['Processando','info'],processando:['Processando','info'],erro_autorizacao:['Rejeitada','bad'],erro:['Erro','bad'],cancelado:['Cancelada',''],denegado:['Denegada','bad']};
async function fn(action,body){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function carregarNfe(){if(nfe.carregando||!window.Cloud?.ws)return;nfe.carregando=true;nfe.tentou=true;try{const [s,n]=await Promise.all([fn('fiscal_status',{}),Cloud.client.from('notas_fiscais').select('*').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(200)]);nfe.status=s;nfe.notas=n.data||[];nfe.erro=''}catch(e){nfe.erro=e.message;nfe.notas=nfe.notas||[]}finally{nfe.carregando=false}if(page==='faturamento'&&!document.querySelector('.modalback'))render()}

function monitor(){const ini=menos(ui.dias),l=db.orders.filter(o=>o.date>=ini&&(!ui.canal||o.platform===ui.canal));
 const semNf=l.filter(o=>!o.nf).sort((a,b)=>a.date.localeCompare(b.date)),comNf=l.filter(o=>o.nf);
 const dias=[...Array(ui.dias)].map((_,i)=>menos(ui.dias-1-i)),por=new Map(dias.map(d=>[d,{t:0,nf:0}]));for(const o of l){const x=por.get(o.date);if(x){x.t++;if(o.nf)x.nf++}}
 const max=Math.max(1,...[...por.values()].map(x=>x.t)),W=720,H=150,bw=W/dias.length,pode=!!nfe.status?.[nfe.status?.ambiente==='producao'?'token_producao':'token_homologacao'];
 return `<section class="card"><div class="cardhead"><div><h2>Pedidos e notas por dia</h2><p class="caption">Barra cheia = pedidos; parte destacada = já faturados (${l.length?(comNf.length/l.length*100).toFixed(1).replace('.',','):'100'}%).</p></div></div>
  <svg viewBox="0 0 ${W} ${H+20}" class="fatchart" role="img" aria-label="Pedidos e notas por dia">${dias.map((d,i)=>{const x=por.get(d),h1=x.t/max*H,h2=x.nf/max*H;return `<rect x="${i*bw+bw*.15}" y="${H-h1}" width="${bw*.7}" height="${h1}" rx="3" class="fb"><title>${new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}: ${x.t} pedidos, ${x.nf} com nota</title></rect><rect x="${i*bw+bw*.15}" y="${H-h2}" width="${bw*.7}" height="${h2}" rx="3" class="fn"/>${i%Math.ceil(dias.length/7)===0?`<text x="${i*bw+2}" y="${H+15}">${d.slice(8,10)}/${d.slice(5,7)}</text>`:''}`}).join('')}</svg></section>
 <div class="tablebox" style="margin-top:16px"><div class="tabletop"><div><h2>Aguardando nota fiscal</h2><p class="caption">Mais antigos primeiro. Pedido pago sem nota há mais de 36 h costuma estourar o prazo de postagem.</p></div></div><div class="tablewrap"><table><thead><tr><th>Pedido</th><th>Canal</th><th>Data</th><th>Há</th><th>Itens</th><th class="num">Valor</th><th></th></tr></thead><tbody>
 ${semNf.slice(0,300).map(o=>{const h=idadeH(o.date);return `<tr><td class="mono clickrow" data-order="${esc(o.id)}">${esc(o.id)}</td><td>${esc(o.platform)}</td><td>${new Date(o.date+'T12:00:00').toLocaleDateString('pt-BR')}</td><td><span class="badge ${h>36?'bad':h>24?'warn':''}">${h<24?'hoje':Math.floor(h/24)+' d'}</span></td><td class="caption">${esc((o.items||[]).map(i=>`${i.qty}× ${i.title||i.sku}`).join(' · ').slice(0,90))}</td><td class="num">${money(o.gross)}</td><td>${pode?`<button class="small" data-nf-emitir="${esc(o.id)}">${nfe.status.ambiente==='producao'?'Emitir NF-e':'Emitir teste'}</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Todos os pedidos do período já têm nota. ✓</td></tr>'}</tbody></table></div></div>`}

function emissao(){if(!window.Cloud?.ws)return '<div class="empty">Entre no portal.</div>';if(!nfe.status&&!nfe.erro){if(!nfe.tentou)carregarNfe();return '<div class="empty">Carregando…</div>'}
 const s=nfe.status||{},c={...PADRAO,...(db.gerencial?.fiscal||{}),...(s.config||{})},prod=c.ambiente==='producao',tk=prod?s.token_producao:s.token_homologacao;
 const passo=(ok,t,sub)=>`<div class="chk"><span class="avico ${ok?'ok':'warn'}">${icon(ok?'check':'alert')}</span><div><strong>${t}</strong><small>${sub}</small></div></div>`;
 const campo=(k,t,w='')=>`<div class="field" ${w}><label>${t}</label><input data-fc="${k}" value="${esc(c[k]??'')}"></div>`;
 return `${nfe.erro?`<div class="notice warnbox">${esc(nfe.erro)}</div>`:''}
 <div class="grid two"><section class="card"><div class="cardhead"><h2>Prontidão da NF-e</h2><span class="badge ${prod?'bad':'info'}">${prod?'PRODUÇÃO':'Homologação (teste)'}</span></div>
  <div class="checklist">${passo(true,'Conta no Focus NFe criada','provedor homologado — emite e transmite à SEFAZ')}${passo(s.token_homologacao,'Token de homologação gravado',s.token_homologacao?'pronto para notas de teste':'grave FOCUS_NFE_TOKEN_HOMOLOGACAO com ops/gravar-segredo.ps1')}${passo(s.token_producao,'Token de produção gravado',s.token_producao?'gravado':'grave FOCUS_NFE_TOKEN depois dos testes')}${passo(!(s.sem_ncm||[]).length&&s.produtos>0,'NCM em todos os produtos',s.produtos==null?'aguardando o servidor':(s.sem_ncm||[]).length?`${s.sem_ncm.length} de ${s.produtos} sem NCM — o servidor lê do Bling a cada hora`:`${s.produtos} produtos com NCM`)}${passo(!!c.revisado,'Regras fiscais revisadas com a Escoben',c.revisado?`revisado em ${new Date(c.revisado).toLocaleDateString('pt-BR')}`:'CFOP, CST, alíquotas e DIFAL abaixo — confirme com o escritório')}</div>
  <div class="row wrap"><button class="small" data-nf="ler">${icon('refresh')} Ler NCM/origem do Bling agora</button><button class="small" data-nf="atualizar">${icon('refresh')} Atualizar notas</button></div>
  <div class="row wrap" style="margin-top:12px"><input id="nfTeste" placeholder="Nº do pedido para nota de teste" style="flex:1"><button class="small primary" data-nf="teste" ${tk?'':'disabled'}>${prod?'Emitir NF-e':'Emitir nota de teste'}</button></div>
  <p class="caption">${prod?'<span class="red">Produção: a nota tem valor fiscal.</span>':'Em homologação a nota não tem valor fiscal — serve para validar regras e dados antes de ligar a produção.'}</p></section>
 <section class="card"><div class="cardhead"><div><h2>Configuração fiscal</h2><p class="caption">Valores iniciais para empresa do Lucro Presumido vendendo a consumidor final. Confirme com a Escoben.</p></div></div>
  <div class="grid three">${campo('serie','Série')}${campo('natureza','Natureza da operação','style="grid-column:span 2"')}${campo('cfop_interno','CFOP dentro de SC')}${campo('cfop_interestadual','CFOP para outros estados')}${campo('cst_icms','CST ICMS')}${campo('aliq_icms_interna','ICMS interno SC (%)')}${campo('cst_pis','CST PIS')}${campo('aliq_pis','PIS (%)')}${campo('cst_cofins','CST COFINS')}${campo('aliq_cofins','COFINS (%)')}${campo('modalidade_frete','Modalidade do frete (0 = emitente)')}</div>
  <label class="check-l"><input type="checkbox" class="check" data-fc-bool="difal" ${c.difal!==false?'checked':''}> Calcular DIFAL (venda interestadual a não contribuinte)</label>
  <label class="check-l"><input type="checkbox" class="check" data-fc-bool="revisado" ${c.revisado?'checked':''}> Regras revisadas e aprovadas pela contabilidade</label>
  <div class="row wrap" style="margin-top:10px"><button class="small primary" data-nf="salvar">${icon('check')} Salvar configuração</button>${s.token_producao&&c.revisado?`<button class="small ${prod?'':'quiet'}" data-nf="ambiente">${prod?'Voltar para homologação':'Ligar PRODUÇÃO'}</button>`:''}</div></section></div>
 <div class="tablebox" style="margin-top:16px"><div class="tabletop"><div><h2>Notas emitidas pelo EcomBalance</h2><p class="caption">${(nfe.notas||[]).length} nota(s)</p></div></div><div class="tablewrap"><table><thead><tr><th>Quando</th><th>Pedido</th><th>Ambiente</th><th>Situação</th><th>Número</th><th>Mensagem</th><th class="num">Valor</th><th></th></tr></thead><tbody>
 ${(nfe.notas||[]).map(n=>{const [t,tom]=STATUS[n.status]||[n.status,''];return `<tr><td>${new Date(n.created_at).toLocaleString('pt-BR')}</td><td class="mono">${esc(n.pedido)}</td><td>${n.ambiente==='producao'?'<span class="badge bad">produção</span>':'<span class="badge">teste</span>'}</td><td><span class="badge ${tom}">${esc(t)}</span></td><td>${esc(n.numero||'—')}${n.serie?`/${esc(n.serie)}`:''}</td><td class="caption audres">${esc(n.mensagem||'')}</td><td class="num">${money(Number(n.valor)||0)}</td><td class="row" style="gap:6px">${n.danfe_url?`<a class="btnlink small" href="${esc(n.danfe_url)}" target="_blank" rel="noopener">DANFE</a>`:''}${n.xml_url?`<a class="btnlink small" href="${esc(n.xml_url)}" target="_blank" rel="noopener">XML</a>`:''}<button class="small quiet" data-nf-consultar="${esc(n.ref)}">Consultar</button>${n.status==='autorizado'?`<button class="small quiet" data-nf-cancelar="${esc(n.ref)}">Cancelar</button>`:''}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">Nenhuma nota emitida pelo EcomBalance ainda.</td></tr>'}</tbody></table></div></div>`}

function view(){const ini=menos(ui.dias),l=db.orders.filter(o=>o.date>=ini&&(!ui.canal||o.platform===ui.canal)),semNf=l.filter(o=>!o.nf),atras=semNf.filter(o=>idadeH(o.date)>36);
 const canais=[...new Set(db.orders.map(o=>o.platform))].sort(),s=nfe.status;if(!s&&!nfe.tentou&&window.Cloud?.ws)carregarNfe();
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">Pedidos sem nota</span><span class="kpiv ${semNf.length?'gold':''}">${semNf.length}</span><span class="kpis">${money(semNf.reduce((x,o)=>x+o.gross,0))}</span></div><div class="card kpi"><span class="kpil">Atrasados (+36 h)</span><span class="kpiv ${atras.length?'red':''}">${atras.length}</span><span class="kpis">Risco de atraso na postagem</span></div><div class="card kpi"><span class="kpil">Emissor</span><span class="kpiv">${s?.config?.ambiente==='producao'?'EcomBalance':'Bling'}</span><span class="kpis">${s?.config?.ambiente==='producao'?'NF-e pelo Focus em produção':'EcomBalance em testes (homologação)'}</span></div><div class="card kpi"><span class="kpil">Notas do EcomBalance</span><span class="kpiv">${(nfe.notas||[]).filter(n=>n.status==='autorizado').length}</span><span class="kpis">autorizadas · ${(nfe.notas||[]).filter(n=>/erro/.test(n.status)).length} com erro</span></div></div>
 <div class="crmbar"><div class="segtabs">${[['monitor','Monitor'],['emissao','Emissão de NF-e']].map(([k,t])=>`<button class="${ui.aba===k?'active':''}" data-fat-aba="${k}">${t}</button>`).join('')}</div>${ui.aba==='monitor'?`<div class="segtabs">${[['','Todos'],...canais.map(c=>[c,c])].map(([k,t])=>`<button class="${ui.canal===k?'active':''}" data-fat-canal="${esc(k)}">${esc(t)}</button>`).join('')}</div><select data-fat-dias aria-label="Período">${[7,14,30,60].map(n=>`<option value="${n}" ${ui.dias===n?'selected':''}>Últimos ${n} dias</option>`).join('')}</select>`:''}</div>
 ${ui.aba==='monitor'?monitor():emissao()}`}

async function emitir(pedido,b){const prod=nfe.status?.config?.ambiente==='producao';if(!pedido)return toast('Informe o pedido.');
 if(!confirm(prod?`Emitir NF-e COM VALOR FISCAL (produção) para o pedido ${pedido}?`:`Emitir nota de TESTE (homologação, sem valor fiscal) para o pedido ${pedido}?`))return;if(b){b.disabled=true;b.textContent='Enviando…'}
 try{const r=await fn('fiscal_emitir',{pedido,producao:prod});toast(r.status==='erro'?`Recusada: ${r.mensagem}`:'Nota enviada. Consultando a SEFAZ…');await new Promise(x=>setTimeout(x,4000));if(r.status!=='erro')await fn('fiscal_consultar',{ref:r.ref}).catch(()=>{});ui.aba='emissao'}catch(e){toast(e.message)}await carregarNfe()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-fat-canal],[data-fat-aba],[data-nf],[data-nf-emitir],[data-nf-consultar],[data-nf-cancelar]');if(!b)return;const d=b.dataset;
 if(d.fatCanal!==undefined){ui.canal=d.fatCanal;render();return}if(d.fatAba){ui.aba=d.fatAba;render();return}
 if(d.nfEmitir){emitir(d.nfEmitir,b);return}
 if(d.nfConsultar){b.disabled=true;try{const r=await fn('fiscal_consultar',{ref:d.nfConsultar});toast(`${STATUS[r.status]?.[0]||r.status}${r.mensagem?' · '+r.mensagem:''}`)}catch(x){toast(x.message)}await carregarNfe();return}
 if(d.nfCancelar){const j=prompt('Justificativa do cancelamento (mínimo 15 caracteres):');if(!j)return;try{await fn('fiscal_cancelar',{ref:d.nfCancelar,justificativa:j});toast('Cancelamento enviado.')}catch(x){toast(x.message)}await carregarNfe();return}
 switch(d.nf){case 'ler':b.disabled=true;b.textContent='Lendo o Bling…';try{const r=await fn('fiscal_ler_produtos',{});toast(`${r.fiscais} produto(s) com dados fiscais lidos.`)}catch(x){toast(x.message)}nfe.status=null;nfe.erro='';nfe.tentou=false;await carregarNfe();break;
  case 'atualizar':nfe.status=null;nfe.erro='';nfe.tentou=false;await carregarNfe();break;
  case 'teste':emitir($('#nfTeste').value.trim(),b);break;
  case 'salvar':{const cfg={...(db.gerencial?.fiscal||{})};$$('[data-fc]').forEach(i=>{const v=i.value.trim();cfg[i.dataset.fc]=/^aliq|modalidade/.test(i.dataset.fc)?Number(v.replace(',','.')):v});$$('[data-fc-bool]').forEach(i=>{cfg[i.dataset.fcBool]=i.dataset.fcBool==='revisado'?(i.checked?(cfg.revisado||new Date().toISOString()):null):i.checked});
   db.gerencial={...(db.gerencial||{}),fiscal:cfg};audit('Configuração fiscal salva',JSON.stringify(cfg).slice(0,400));save();toast('Configuração salva.');setTimeout(()=>{nfe.status=null;nfe.erro='';nfe.tentou=false;carregarNfe()},2500);break}
  case 'ambiente':{const vai=nfe.status?.config?.ambiente!=='producao';if(vai&&!confirm('Ligar a emissão em PRODUÇÃO? As notas passam a ter valor fiscal. Faça isso só depois dos testes aprovados pela Escoben e com o Bling parado de emitir para os mesmos pedidos.'))return;
   db.gerencial={...(db.gerencial||{}),fiscal:{...(db.gerencial?.fiscal||{}),ambiente:vai?'producao':'homologacao'}};audit('Ambiente fiscal',vai?'PRODUÇÃO ligada':'voltou para homologação');save();setTimeout(()=>{nfe.status=null;nfe.erro='';nfe.tentou=false;carregarNfe()},2500);break}}});
function bind(){const s=$('[data-fat-dias]');if(s)s.onchange=()=>{ui.dias=Number(s.value);render()}}
addPage('faturamento','receipt','Faturamento',view,'Pedidos sem nota, ritmo de emissão e a emissão de NF-e pelo EcomBalance (Focus NFe).','',bind);
if(navItems.filter(n=>n[0]==='faturamento').length>1)navItems.splice(navItems.map(n=>n[0]).lastIndexOf('faturamento'),1);
window.Faturamento={avisos:()=>{const l=db.orders.filter(o=>!o.nf&&o.date>=menos(14)&&idadeH(o.date)>36);return l.length?[['bad','receipt',`${l.length} pedido(s) sem nota há mais de 36 h`,'Risco de atraso na postagem','faturamento']]:[]}};
})();
