'use strict';
// Telas adicionais: Integrações, Entradas e saídas, Produtos, Estados e Clientes (CRM),
// conciliação em lote das correspondências exatas e navegação por endereço (#pagina).
(()=>{
Object.assign(paths,{
 box:'M21 8 12 3 3 8v8l9 5 9-5z M3 8l9 5 9-5 M12 13v8',
 pin:'M12 22s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12z M12 12.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5',
 users:'M16 20v-1a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v1 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M22 20v-1a4 4 0 0 0-3-3.9 M16 3.1a4 4 0 0 1 0 7.8',
 plug:'M9 2v6 M15 2v6 M6 8h12v3a6 6 0 0 1-12 0z M12 17v5',
 cash:'M2 6h20v12H2z M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M6 12h.01 M18 12h.01',
 chat:'M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z',
 refresh:'M21 12a9 9 0 1 1-3-6.7L21 8 M21 3v5h-5',
 logout:'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4 M16 17l5-5-5-5 M21 12H9',
 send:'M22 2 11 13 M22 2l-7 20-4-9-9-4z',
 bolt:'M13 2 3 14h9l-1 8 10-12h-9z',
});

const MKT=['Mercado Livre','Shopee','Magalu'];
const fx={period:'mes',platform:'',search:'',segment:'',stage:'',kind:'',syncRange:'mes'};
const STAGES=['Novo','Em contato','Negociação','Ativo','Pós-venda','Perdido'];
const SEGMENTS=['VIP','Recorrente','Novo','Em risco','Inativo'];
const segTone={VIP:'purple',Recorrente:'ok',Novo:'info','Em risco':'warn',Inativo:'bad'};
const num0=n=>Number(n||0).toLocaleString('pt-BR');
const fmtDate=d=>d?String(d).slice(0,10).split('-').reverse().join('/'):'—';
const today=()=>new Date().toLocaleDateString('sv-SE');
const monthLabel=m=>new Date(m+'-15T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});
const norm=s=>normalized(s); // importer.js: sem acentos, minúsculas

// ───────── Dados derivados (usados pelas telas e pelo assistente) ─────────
function ordersFor(m=month,platform=''){let rows=m==='todos'?db.orders:m==='12m'?db.orders.filter(o=>o.date>=new Date(Date.now()-365*864e5).toLocaleDateString('sv-SE')):db.orders.filter(o=>o.date.startsWith(m));return platform?rows.filter(o=>o.platform===platform):rows}
function periodRows(){return ordersFor(fx.period==='mes'?month:fx.period,fx.platform)}
function productRank(rows){const map=new Map();for(const o of rows)for(const it of o.items||[]){const k=norm(it.sku||it.title)||'sem-codigo';const p=map.get(k)||{sku:it.sku||'',title:it.title||it.sku||'Sem descrição',qty:0,revenue:0,orders:new Set(),platforms:new Set()};const q=Number(it.qty)||0;p.qty+=q;p.revenue+=q*(Number(it.price)||0);p.orders.add(o.id);p.platforms.add(o.platform);map.set(k,p)}const total=[...map.values()].reduce((a,p)=>a+p.revenue,0)||1;return [...map.values()].map(p=>({sku:p.sku,title:p.title,qty:round(p.qty),revenue:round(p.revenue),orders:p.orders.size,platforms:[...p.platforms],share:p.revenue/total*100}))}
function ufOf(o){return String(o.state||o.customer?.state||'').toUpperCase().slice(0,2)}
function stateRank(rows){const map=new Map();for(const o of rows){const uf=ufOf(o)||'—';const s=map.get(uf)||{uf,orders:0,gross:0,platforms:{}};s.orders++;s.gross+=o.gross;s.platforms[o.platform]=(s.platforms[o.platform]||0)+1;map.set(uf,s)}const total=rows.reduce((a,o)=>a+o.gross,0)||1;return [...map.values()].map(s=>({...s,gross:round(s.gross),ticket:round(s.gross/s.orders),share:s.gross/total*100})).sort((a,b)=>b.gross-a.gross)}
function customerKey(o){const c=o.customer;if(!c)return null;const d=String(c.doc||'').replace(/\D/g,'');if(d.length>=11)return 'DOC-'+d;if(c.id&&!/-(undefined|null|)$/.test(c.id))return String(c.id);if(c.name)return 'NOME-'+norm(c.name).replace(/\s+/g,'-');return null}
function customers(){const map=new Map(),ref=today();for(const o of db.orders){const k=customerKey(o);if(!k)continue;const c=map.get(k)||{key:k,name:'',doc:'',email:'',phone:'',city:'',state:'',orders:[],total:0,platforms:new Set()};const s=o.customer||{};c.name=c.name||s.name||'';c.doc=c.doc||s.doc||'';c.email=c.email||s.email||'';c.phone=c.phone||s.phone||'';c.city=c.city||s.city||'';c.state=c.state||ufOf(o);c.orders.push(o);c.total+=o.gross;c.platforms.add(o.platform);map.set(k,c)}
 const list=[...map.values()].map(c=>{c.orders.sort((a,b)=>a.date.localeCompare(b.date));const last=c.orders.at(-1).date,first=c.orders[0].date;return {...c,total:round(c.total),count:c.orders.length,ticket:round(c.total/c.orders.length),first,last,recency:Math.max(0,Math.round((new Date(ref)-new Date(last))/864e5)),platforms:[...c.platforms],crm:db.crm[c.key]||{stage:'Novo',tags:[],notes:'',interactions:[]}}});
 const totals=list.map(c=>c.total).sort((a,b)=>a-b),p90=totals[Math.floor(totals.length*.9)]??Infinity;
 for(const c of list)c.segment=c.recency>180?'Inativo':c.recency>90?'Em risco':c.count>=2&&c.total>=p90?'VIP':c.count>=2?'Recorrente':'Novo';
 return list}
function ledgerFor(m=month){return db.ledger.filter(l=>(l.due||l.paidDate||'').startsWith(m))}
window.Insights={ordersFor,productRank,stateRank,customers,ledgerFor,customerKey};

// ───────── Componentes visuais ─────────
const kpi=(label,value,caption,ic='chart',tone='')=>`<div class="card metric"><div class="label">${label}${icon(ic)}</div><div class="value ${tone}">${value}</div><small>${caption}</small></div>`;
const hbars=(rows,label,value,fmt=money,color='var(--accent)')=>{const max=Math.max(1,...rows.map(value));return `<div class="hbars">${rows.map(r=>`<div class="hbar"><span class="hbarlabel" title="${esc(label(r))}">${esc(label(r))}</span><div class="bar"><i style="width:${value(r)/max*100}%;background:${color}"></i></div><strong>${fmt(value(r))}</strong></div>`).join('')}</div>`};
const periodSelect=()=>`<select id="fxPeriod" aria-label="Período"><option value="mes" ${fx.period==='mes'?'selected':''}>Competência: ${monthLabel(month)}</option><option value="12m" ${fx.period==='12m'?'selected':''}>Últimos 12 meses</option><option value="todos" ${fx.period==='todos'?'selected':''}>Todo o histórico</option></select>`;
const platformSelect=()=>`<select id="fxPlatform" aria-label="Plataforma"><option value="">Todas as plataformas</option>${MKT.map(p=>`<option ${fx.platform===p?'selected':''}>${p}</option>`).join('')}</select>`;
const emptyData=(what)=>`<div class="empty">${what} Sincronize o Bling e os marketplaces em <button class="quiet small" data-nav="integracoes">${icon('plug')} Integrações</button> ou importe relatórios com as colunas de cliente, UF e produto.</div>`;

// ───────── Produtos ─────────
function productsView(){const rows=periodRows(),withItems=rows.filter(o=>o.items?.length).length,rank=productRank(rows).sort((a,b)=>fx.sort==='qtd'?b.qty-a.qty:b.revenue-a.revenue),q=norm(fx.search),list=q?rank.filter(p=>norm(p.title+' '+p.sku).includes(q)):rank,rev=rank.reduce((a,p)=>a+p.revenue,0),units=rank.reduce((a,p)=>a+p.qty,0),top=rank.slice(0,Math.max(1,Math.ceil(rank.length*.2))).reduce((a,p)=>a+p.revenue,0);
 return `<div class="filters">${periodSelect()}${platformSelect()}<select id="fxSort" aria-label="Ordenar"><option value="receita">Ordenar por receita</option><option value="qtd" ${fx.sort==='qtd'?'selected':''}>Ordenar por quantidade</option></select><input type="search" id="fxSearch" placeholder="Buscar produto ou SKU…" value="${esc(fx.search)}"><button data-fx="export-products">${icon('download')} Exportar</button></div>
 <div class="grid metrics">${kpi('Receita em produtos',money(rev),`${num0(rank.length)} produtos diferentes`,'box')}${kpi('Unidades vendidas',num0(units),`${num0(withItems)} de ${num0(rows.length)} pedidos com itens`,'chart')}${kpi('Preço médio por unidade',money(units?rev/units:0),'Receita ÷ unidades','wallet')}${kpi('Concentração (curva ABC)',pct(rev?top/rev*100:0),'Receita dos 20% produtos mais vendidos','spark','purple')}</div>
 ${!rank.length?emptyData('Nenhum item de pedido no período.'):`<div class="grid charts"><div class="card"><div class="cardhead"><h2>Top 10 por ${fx.sort==='qtd'?'quantidade':'receita'}</h2>${icon('box')}</div>${hbars(rank.slice(0,10),p=>p.title,p=>fx.sort==='qtd'?p.qty:p.revenue,fx.sort==='qtd'?num0:money)}</div><div class="card"><div class="cardhead"><h2>Receita por plataforma</h2>${icon('chart')}</div>${hbars(MKT.map(p=>({p,v:productRank(rows.filter(o=>o.platform===p)).reduce((a,x)=>a+x.revenue,0)})).filter(x=>x.v),x=>x.p,x=>x.v)}</div></div>
 <div class="tablebox"><div class="tabletop"><h2>Ranking de produtos</h2><span class="badge">${list.length} produtos</span></div><div class="tablewrap"><table><thead><tr><th>#</th><th>Produto</th><th>SKU</th><th class="num">Unidades</th><th class="num">Pedidos</th><th class="num">Receita</th><th>Participação</th><th>Canais</th></tr></thead><tbody>${list.slice(0,300).map((p,i)=>`<tr><td>${i+1}</td><td><strong>${esc(p.title)}</strong></td><td class="caption">${esc(p.sku)}</td><td class="num">${num0(p.qty)}</td><td class="num">${num0(p.orders)}</td><td class="num">${money(p.revenue)}</td><td style="min-width:120px"><div class="bar"><i style="width:${Math.min(100,p.share*3)}%;background:var(--accent)"></i></div><span class="caption">${pct(p.share)}</span></td><td>${p.platforms.map(x=>logo(x)).join(' ')}</td></tr>`).join('')}</tbody></table></div></div>`}`}

// ───────── Estados ─────────
const TILES={RR:[2,0],AP:[4,0],AM:[1,1],PA:[3,1],MA:[4,1],CE:[5,1],RN:[6,1],AC:[0,2],RO:[1,2],MT:[2,2],TO:[3,2],PI:[4,2],PE:[5,2],PB:[6,2],MS:[2,3],GO:[3,3],DF:[4,3],BA:[5,3],AL:[6,3],SP:[3,4],MG:[4,4],ES:[5,4],SE:[6,4],PR:[3,5],RJ:[4,5],SC:[3,6],RS:[3,7]};
function statesView(){const rows=periodRows(),rank=stateRank(rows),by=Object.fromEntries(rank.map(s=>[s.uf,s])),max=Math.max(1,...rank.filter(s=>s.uf!=='—').map(s=>s.gross)),known=rank.filter(s=>s.uf!=='—'),missing=by['—']?.orders||0;
 return `<div class="filters">${periodSelect()}${platformSelect()}<button data-fx="export-states">${icon('download')} Exportar</button></div>
 <div class="grid metrics">${kpi('Estados atendidos',num0(known.length),'UFs com ao menos um pedido','pin')}${kpi('Principal estado',known[0]?known[0].uf:'—',known[0]?`${pct(known[0].share)} da receita · ${money(known[0].gross)}`:'Sem dados de UF','chart','purple')}${kpi('Ticket médio',money(rows.length?rows.reduce((a,o)=>a+o.gross,0)/rows.length:0),`${num0(rows.length)} pedidos no período`,'wallet')}${kpi('Pedidos sem UF',num0(missing),missing?'Sincronize os marketplaces para completar':'Todos com UF de entrega','alert',missing?'gold':'')}</div>
 ${!known.length?emptyData('Nenhum pedido com UF de entrega no período.'):`<div class="grid charts"><div class="card"><div class="cardhead"><div><h2>Mapa de vendas</h2><p class="caption">Intensidade pela receita bruta do período</p></div>${icon('pin')}</div><div class="ufmap">${Object.entries(TILES).map(([uf,[c,r]])=>{const s=by[uf],a=s?.15+.85*s.gross/max:0;return `<div class="uftile ${s?'has':''}" style="grid-column:${c+1};grid-row:${r+1};${s?`background:color-mix(in srgb,var(--accent) ${Math.round(a*100)}%,var(--panel2))`:''}" title="${uf}${s?` · ${s.orders} pedidos · ${money(s.gross)}`:' · sem vendas'}"><b>${uf}</b>${s?`<small>${pct(s.share)}</small>`:''}</div>`}).join('')}</div></div><div class="card"><div class="cardhead"><h2>Top 10 estados</h2>${icon('chart')}</div>${hbars(known.slice(0,10),s=>s.uf,s=>s.gross)}</div></div>
 <div class="tablebox"><div class="tabletop"><h2>Vendas por estado</h2></div><div class="tablewrap"><table><thead><tr><th>UF</th><th class="num">Pedidos</th><th class="num">Receita bruta</th><th class="num">Ticket médio</th><th>Participação</th>${MKT.map(p=>`<th class="num">${p}</th>`).join('')}</tr></thead><tbody>${rank.map(s=>`<tr><td><strong>${s.uf==='—'?'Não informado':s.uf}</strong></td><td class="num">${num0(s.orders)}</td><td class="num">${money(s.gross)}</td><td class="num">${money(s.ticket)}</td><td style="min-width:120px"><div class="bar"><i style="width:${s.share}%;background:var(--accent)"></i></div><span class="caption">${pct(s.share)}</span></td>${MKT.map(p=>`<td class="num">${num0(s.platforms[p]||0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}`}

// ───────── Clientes (CRM) ─────────
function crmView(){const all=customers(),q=norm(fx.search),list=all.filter(c=>(!q||norm(`${c.name} ${c.doc} ${c.city} ${c.state} ${c.crm.tags.join(' ')}`).includes(q))&&(!fx.segment||c.segment===fx.segment)&&(!fx.stage||c.crm.stage===fx.stage)).sort((a,b)=>fx.sort==='recencia'?a.recency-b.recency:fx.sort==='compras'?b.count-a.count:b.total-a.total),
 rec=all.filter(c=>c.count>=2).length,ltv=all.length?all.reduce((a,c)=>a+c.total,0)/all.length:0,tasks=all.flatMap(c=>(c.crm.interactions||[]).map((it,i)=>({c,it,i}))).filter(x=>x.it.due&&!x.it.done).sort((a,b)=>a.it.due.localeCompare(b.it.due)),
 seg=Object.fromEntries(SEGMENTS.map(s=>[s,all.filter(c=>c.segment===s)]));
 if(!all.length)return `<div class="grid metrics">${kpi('Clientes','0','Nenhum cliente identificado','users')}</div>${emptyData('Ainda não há clientes identificados nos pedidos.')}`;
 return `<div class="grid metrics">${kpi('Clientes',num0(all.length),`${num0(seg.Novo.length)} novos nos últimos 90 dias`,'users')}${kpi('Taxa de recompra',pct(rec/all.length*100),`${num0(rec)} clientes com 2+ compras`,'refresh','green')}${kpi('Valor médio por cliente',money(ltv),'Receita bruta acumulada ÷ clientes','wallet')}${kpi('Follow-ups pendentes',num0(tasks.length),tasks.filter(t=>t.it.due<=today()).length+' vencidos ou para hoje','clock',tasks.some(t=>t.it.due<=today())?'gold':'')}</div>
 <div class="grid segs">${SEGMENTS.map(s=>`<button class="card seg ${fx.segment===s?'active':''}" data-fx-seg="${s}"><span class="badge ${segTone[s]}">${s}</span><b>${num0(seg[s].length)}</b><span class="caption">${money(seg[s].reduce((a,c)=>a+c.total,0))}</span></button>`).join('')}</div>
 <div class="grid two" style="margin-bottom:22px"><div class="card"><div class="cardhead"><h2>Ações sugeridas</h2>${icon('bolt')}</div>
 ${[['Reativar clientes inativos','Inativo','Sem comprar há mais de 180 dias. Ofereça cupom de retorno.'],['Segurar clientes em risco','Em risco','Última compra entre 91 e 180 dias. Contato antes que esfriem.'],['Incentivar a segunda compra','Novo','Compraram uma vez nos últimos 90 dias. Pós-venda e recomendação.'],['Mimar os VIPs','VIP','Maiores compradores e recorrentes. Prioridade no atendimento.']].map(([t,s,d])=>`<div class="listline"><div><strong>${t}</strong><br><span class="caption">${d}</span></div><div class="row"><span class="badge ${segTone[s]}">${num0(seg[s].length)}</span><button class="small" data-fx-export-seg="${s}" ${seg[s].length?'':'disabled'}>${icon('download')} Lista</button></div></div>`).join('')}</div>
 <div class="card"><div class="cardhead"><h2>Próximos follow-ups</h2>${icon('clock')}</div>${tasks.length?tasks.slice(0,8).map(t=>`<div class="listline"><div><strong>${esc(t.c.name||t.c.key)}</strong><br><span class="caption">${esc(t.it.type)} · ${esc(t.it.text)}</span></div><div class="row"><span class="badge ${t.it.due<today()?'bad':t.it.due===today()?'warn':'info'}">${fmtDate(t.it.due)}</span><button class="small quiet" data-fx-customer="${esc(t.c.key)}">${icon('arrow')}</button></div></div>`).join(''):'<p class="caption">Nenhum follow-up agendado. Abra um cliente para registrar contatos e lembretes.</p>'}</div></div>
 <div class="filters"><input type="search" id="fxSearch" placeholder="Buscar nome, documento, cidade ou etiqueta…" value="${esc(fx.search)}"><select id="fxSegment"><option value="">Todos os segmentos</option>${SEGMENTS.map(s=>`<option ${fx.segment===s?'selected':''}>${s}</option>`).join('')}</select><select id="fxStage"><option value="">Todos os estágios</option>${STAGES.map(s=>`<option ${fx.stage===s?'selected':''}>${s}</option>`).join('')}</select><select id="fxSort"><option value="total">Maior valor</option><option value="compras" ${fx.sort==='compras'?'selected':''}>Mais compras</option><option value="recencia" ${fx.sort==='recencia'?'selected':''}>Compra mais recente</option></select><button data-fx="export-customers">${icon('download')} Exportar</button></div>
 <div class="tablebox"><div class="tabletop"><h2>Clientes</h2><span class="badge">${list.length}</span></div><div class="tablewrap"><table><thead><tr><th>Cliente</th><th>Local</th><th>Segmento</th><th>Estágio</th><th class="num">Compras</th><th class="num">Total</th><th class="num">Ticket</th><th>Última compra</th><th></th></tr></thead><tbody>${list.slice(0,400).map(c=>`<tr><td><strong>${esc(c.name||'Sem nome')}</strong><br><span class="caption">${esc(c.doc||c.key)}${c.crm.tags.length?' · '+c.crm.tags.map(esc).join(', '):''}</span></td><td>${esc([c.city,c.state].filter(Boolean).join(' / ')||'—')}</td><td><span class="badge ${segTone[c.segment]}">${c.segment}</span></td><td>${esc(c.crm.stage)}</td><td class="num">${c.count}</td><td class="num">${money(c.total)}</td><td class="num">${money(c.ticket)}</td><td>${fmtDate(c.last)}<br><span class="caption">há ${c.recency} dias</span></td><td><div class="row">${c.platforms.map(p=>logo(p)).join('')}<button class="quiet small" data-fx-customer="${esc(c.key)}" aria-label="Abrir cliente">${icon('arrow')}</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
function customerModal(key){const c=customers().find(x=>x.key===key);if(!c)return;const crm=c.crm;
 modal(c.name||'Cliente',`<div class="row wrap" style="margin-bottom:18px"><span class="badge ${segTone[c.segment]}">${c.segment}</span><span class="caption">${esc(c.doc||c.key)} · ${esc([c.city,c.state].filter(Boolean).join(' / '))}${c.email?' · '+esc(c.email):''}${c.phone?' · '+esc(c.phone):''}</span></div>
 <div class="grid three"><div class="detailmetric"><span class="caption">Total comprado</span><strong>${money(c.total)}</strong></div><div class="detailmetric"><span class="caption">Compras</span><strong>${c.count}</strong></div><div class="detailmetric"><span class="caption">Primeira / última</span><strong style="font-size:15px">${fmtDate(c.first)} · ${fmtDate(c.last)}</strong></div></div>
 <div class="grid two" style="margin-top:14px"><div><label for="crmStage">Estágio</label><select id="crmStage" style="width:100%">${STAGES.map(s=>`<option ${crm.stage===s?'selected':''}>${s}</option>`).join('')}</select></div><div><label for="crmTags">Etiquetas (separe por vírgula)</label><input id="crmTags" style="width:100%" value="${esc(crm.tags.join(', '))}"></div></div>
 <label for="crmNotes">Observações</label><textarea id="crmNotes">${esc(crm.notes)}</textarea>
 <h3 style="margin-top:20px">Contatos e lembretes</h3>${(crm.interactions||[]).map((it,i)=>`<div class="listline"><div><strong>${esc(it.type)}</strong> · <span class="caption">${new Date(it.time).toLocaleDateString('pt-BR')}</span><br><span>${esc(it.text)}</span></div><div class="row">${it.due?`<span class="badge ${it.done?'ok':it.due<today()?'bad':'info'}">${it.done?'Feito':'Até '+fmtDate(it.due)}</span>${it.done?'':`<button class="small quiet" data-fx-done="${i}" data-key="${esc(key)}">${icon('check')}</button>`}`:''}</div></div>`).join('')||'<p class="caption">Nenhum contato registrado.</p>'}
 <div class="grid three" style="margin-top:10px"><div><label for="crmType">Tipo</label><select id="crmType" style="width:100%"><option>WhatsApp</option><option>Ligação</option><option>E-mail</option><option>Pós-venda</option><option>Reclamação</option><option>Outro</option></select></div><div style="grid-column:span 2"><label for="crmText">Registro</label><input id="crmText" style="width:100%" placeholder="O que foi conversado ou precisa ser feito"></div></div><label for="crmDue">Lembrete (opcional)</label><input id="crmDue" type="date">
 <h3 style="margin-top:22px">Pedidos</h3><div class="tablewrap"><table><thead><tr><th>Pedido</th><th>Data</th><th>Canal</th><th>Itens</th><th class="num">Bruto</th><th>Status</th></tr></thead><tbody>${c.orders.slice().reverse().map(o=>`<tr><td>${esc(o.id)}</td><td>${fmtDate(o.date)}</td><td>${logo(o.platform)}</td><td class="caption">${esc((o.items||[]).map(i=>`${i.qty}× ${i.title}`).join('; ').slice(0,120))}</td><td class="num">${money(o.gross)}</td><td>${badge(status(o))}</td></tr>`).join('')}</tbody></table></div>
 <div class="modalfoot"><button data-action="close">Fechar</button><button class="primary" data-fx-save-customer="${esc(key)}">${icon('check')} Salvar</button></div>`)}

// ───────── Entradas e saídas (contas do Bling) ─────────
function flowView(){const rows=ledgerFor(),ins=rows.filter(l=>l.kind==='entrada'),outs=rows.filter(l=>l.kind==='saida'),sum=a=>round(a.reduce((s,l)=>s+l.amount,0)),done=a=>a.filter(l=>/liquid|pag|receb/i.test(l.status)),open=a=>a.filter(l=>/aberto|parcial/i.test(l.status)),rec=db.receipts.filter(r=>r.date.startsWith(month)),mk=round(rec.reduce((a,r)=>a+r.amount,0)),list=rows.filter(l=>!fx.kind||l.kind===fx.kind).sort((a,b)=>(a.due||'').localeCompare(b.due||'')),
 cats=Object.entries(outs.reduce((m,l)=>(m[l.category||'Sem categoria']=(m[l.category||'Sem categoria']||0)+l.amount,m),{})).sort((a,b)=>b[1]-a[1]).slice(0,8);
 return `<div class="notice"><strong>Entradas e saídas do ERP.</strong> Contas a receber e a pagar do Bling com vencimento em ${monthLabel(month)}, comparadas aos repasses efetivos das plataformas.</div>
 <div class="grid metrics">${kpi('Entradas previstas',money(sum(ins)),`${ins.length} títulos a receber`,'arrow','green')}${kpi('Entradas liquidadas',money(sum(done(ins))),`${money(sum(open(ins)))} em aberto`,'check','green')}${kpi('Saídas previstas',money(sum(outs)),`${outs.length} títulos a pagar`,'cash','red')}${kpi('Saídas pagas',money(sum(done(outs))),`${money(sum(open(outs)))} em aberto`,'check')}${kpi('Saldo previsto',money(sum(ins)-sum(outs)),'Entradas − saídas do mês','wallet',sum(ins)-sum(outs)<0?'red':'green')}${kpi('Repasses dos marketplaces',money(mk),`${rec.length} liberações no mês`,'link','purple')}${kpi('Diferença repasses × entradas liquidadas',money(mk-sum(done(ins))),'Positivo: repasses sem baixa no Bling','alert',Math.abs(mk-sum(done(ins)))>1?'gold':'')}${kpi('Títulos vencidos',num0([...open(ins),...open(outs)].filter(l=>l.due&&l.due<today()).length),'Em aberto com vencimento passado','clock')}</div>
 ${!db.ledger.length?emptyData('Nenhuma conta a receber ou a pagar carregada.'):`<div class="grid charts"><div class="card"><div class="cardhead"><h2>Maiores saídas por categoria</h2>${icon('cash')}</div>${cats.length?hbars(cats,c=>c[0],c=>c[1],money,'var(--red)'):'<p class="caption">Sem saídas no mês.</p>'}</div><div class="card"><div class="cardhead"><h2>Entradas × saídas</h2>${icon('chart')}</div>${hbars([['Entradas previstas',sum(ins)],['Entradas liquidadas',sum(done(ins))],['Saídas previstas',sum(outs)],['Saídas pagas',sum(done(outs))]],x=>x[0],x=>x[1])}</div></div>
 <div class="filters"><select id="fxKind"><option value="">Entradas e saídas</option><option value="entrada" ${fx.kind==='entrada'?'selected':''}>Somente entradas</option><option value="saida" ${fx.kind==='saida'?'selected':''}>Somente saídas</option></select><button data-fx="export-ledger">${icon('download')} Exportar</button></div>
 <div class="tablebox"><div class="tabletop"><h2>Títulos do mês</h2><span class="badge">${list.length}</span></div><div class="tablewrap"><table><thead><tr><th>Tipo</th><th>Vencimento</th><th>Pagamento</th><th>Contato</th><th>Categoria</th><th>Descrição</th><th>Status</th><th class="num">Valor</th></tr></thead><tbody>${list.map(l=>`<tr><td><span class="badge ${l.kind==='entrada'?'ok':'bad'}">${l.kind==='entrada'?'Entrada':'Saída'}</span></td><td>${fmtDate(l.due)}</td><td>${fmtDate(l.paidDate)}</td><td>${esc(l.contact||'—')}</td><td>${esc(l.category||'—')}</td><td class="caption">${esc(l.description||'')}</td><td>${esc(l.status)}</td><td class="num">${money(l.amount)}</td></tr>`).join('')}</tbody></table></div></div>`}`}

// ───────── Integrações ─────────
const PROVIDERS=[
 {id:'bling',label:'Bling',p:'Bling',brings:'Pedidos de venda e NF (origem fiscal), itens, clientes, UF, taxas informadas e contas a receber/pagar.'},
 {id:'mercadolivre',label:'Mercado Livre',p:'Mercado Livre',brings:'Pedidos, tarifa de venda, frete do vendedor, comprador, UF e liberações do Mercado Pago.'},
 {id:'shopee',label:'Shopee',p:'Shopee',brings:'Pedidos, valor líquido por pedido (escrow), comprador, UF e repasses liberados.'},
 {id:'magalu',label:'Magalu',p:'Magalu',brings:'Pedidos, comissão, frete, cliente e UF. Repasses por importação do extrato.'},
];
const integ={status:null,rows:{},busy:{},progress:{},members:[],loaded:false};
async function callFn(name,body){const r=await Cloud.client.functions.invoke(name,{body:{workspace_id:Cloud.ws,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function loadIntegrations(){if(!window.Cloud?.ws)return;try{const [st,{data:rows},{data:members}]=await Promise.all([callFn('integrations',{action:'status'}).catch(e=>({error:e.message})),Cloud.client.from('integrations').select('*').eq('workspace_id',Cloud.ws),Cloud.client.from('workspace_members').select('user_id,role,created_at').eq('workspace_id',Cloud.ws)]);integ.status=st;integ.rows=Object.fromEntries((rows||[]).map(r=>[r.provider,r]));integ.members=members||[];integ.loaded=true}catch(e){integ.status={error:e.message};integ.loaded=true}if(page==='integracoes')render()}
window.Integrations={load:loadIntegrations,callFn,state:integ};
function syncRange(){const t=today();if(fx.syncRange==='30')return [new Date(Date.now()-30*864e5).toLocaleDateString('sv-SE'),t];if(fx.syncRange==='90')return [new Date(Date.now()-90*864e5).toLocaleDateString('sv-SE'),t];const last=new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).toLocaleDateString('sv-SE');return [month+'-01',last>t?t:last]}
function integrationsView(){
 if(!window.Cloud?.enabled)return `<div class="hero"><div><div class="eyebrow">Modo local</div><h2>Conecte a nuvem para integrar as plataformas.</h2><p>As integrações automáticas com Bling, Mercado Livre, Shopee e Magalu e o assistente de IA funcionam com o banco na nuvem (Supabase). Enquanto isso, os dados ficam neste navegador e entram por importação de relatórios.</p><div class="row"><button class="primary" data-nav="imports">${icon('upload')} Importar relatórios</button></div></div></div><div class="card"><h2>Como ativar</h2><p>Siga <strong>docs/CONFIGURAR.md</strong> no repositório: criar o projeto no Supabase, cadastrar os segredos e publicar. Leva cerca de 15 minutos.</p></div>`;
 if(!integ.loaded){loadIntegrations();return '<div class="empty">Carregando integrações…</div>'}
 const st=integ.status||{},[from,to]=syncRange();
 return `${st.error?`<div class="notice red"><strong>Funções do servidor indisponíveis.</strong> ${esc(st.error)}. Verifique se as Edge Functions foram publicadas (docs/CONFIGURAR.md).</div>`:''}
 <div class="card" style="margin-bottom:22px"><div class="cardhead"><div><h2>Sincronização</h2><p class="caption">Traz pedidos, repasses e contas do período. Vínculos, anotações e fechamentos feitos aqui nunca são sobrescritos.</p></div><div class="row wrap"><select id="fxSyncRange"><option value="mes" ${fx.syncRange==='mes'?'selected':''}>Competência ${monthLabel(month)}</option><option value="30" ${fx.syncRange==='30'?'selected':''}>Últimos 30 dias</option><option value="90" ${fx.syncRange==='90'?'selected':''}>Últimos 90 dias</option></select><button class="primary" data-fx="sync-all" ${Object.values(integ.busy).some(Boolean)?'disabled':''}>${icon('refresh')} Sincronizar tudo</button></div></div><p class="caption">Período: ${fmtDate(from)} a ${fmtDate(to)}. Sincronize primeiro o Bling (origem fiscal) e depois os marketplaces — o botão acima já segue essa ordem.</p></div>
 <div class="grid two">${PROVIDERS.map(pr=>{const row=integ.rows[pr.id]||{},avail=st.available?.[pr.id],on=row.status==='conectado'||row.status==='erro',busy=integ.busy[pr.id],pend=Object.entries(row.settings?.lojasPendentes||{});
  return `<div class="card"><div class="cardhead"><div class="row">${logo(pr.p)}<div><h2>${pr.label}</h2><p class="caption">${esc(row.account_name||'')}</p></div></div><span class="badge ${row.status==='conectado'?'ok':row.status==='erro'?'bad':'warn'}">${row.status==='conectado'?'Conectado':row.status==='erro'?'Erro':'Desconectado'}</span></div><p style="font-size:12px;min-height:38px">${pr.brings}</p>
  <div class="listline"><span>Última sincronização</span><strong>${row.last_sync?new Date(row.last_sync).toLocaleString('pt-BR'):'—'}</strong></div>
  ${row.last_error?`<div class="notice red" style="margin-top:10px">${esc(row.last_error)}</div>`:''}
  ${!avail&&!st.error?`<div class="notice" style="margin-top:10px">Credenciais do aplicativo ${pr.label} ainda não cadastradas no servidor. Veja <strong>docs/INTEGRACOES.md</strong>.</div>`:''}
  ${integ.progress[pr.id]?`<p class="caption" style="margin-top:10px">${esc(integ.progress[pr.id])}</p>`:''}
  ${pr.id==='bling'&&pend.length?`<div class="notice" style="margin-top:12px"><strong>Lojas do Bling sem canal definido.</strong> Diga a qual marketplace pertence cada loja e sincronize novamente.${pend.map(([id,u])=>`<div class="row wrap" style="margin-top:8px"><span>Loja ${esc(id)} · ${u.count} pedidos · ex.: ${esc(u.sample)}${u.name?' · '+esc(u.name):''}</span><select data-fx-loja="${esc(id)}"><option value="">Escolha…</option>${MKT.map(p=>`<option>${p}</option>`).join('')}<option>Ignorar</option></select></div>`).join('')}</div>`:''}
  <div class="row wrap" style="margin-top:16px">${on?`<button class="primary small" data-fx-sync="${pr.id}" ${busy?'disabled':''}>${icon('refresh')} ${busy?'Sincronizando…':'Sincronizar'}</button><button class="small" data-fx-connect="${pr.id}" ${avail?'':'disabled'}>Reconectar</button><button class="small quiet" data-fx-disconnect="${pr.id}">Desconectar</button>`:`<button class="primary small" data-fx-connect="${pr.id}" ${avail?'':'disabled'}>${icon('plug')} Conectar ${pr.label}</button>`}${row.settings?.amostra?`<button class="small quiet" data-fx-sample="${pr.id}">Ver amostra</button>`:''}</div></div>`}).join('')}</div>
 <div class="grid two" style="margin-top:22px"><div class="card"><div class="cardhead"><h2>Assistente de IA</h2>${icon('spark')}</div><p>${st.ai?'Ativo. Abra o assistente pelo botão no canto inferior direito.':'Inativo: cadastre ANTHROPIC_API_KEY nos segredos do Supabase (docs/CONFIGURAR.md).'}</p></div>
 <div class="card"><div class="cardhead"><h2>Equipe · ${esc(Cloud.wsName)}</h2>${icon('users')}</div><p class="caption">${integ.members.length} membro(s). ${Cloud.role==='owner'?'Você é o dono deste workspace.':''}</p>${Cloud.role==='owner'?`<label for="memberEmail">Adicionar colega (ele precisa ter criado a conta)</label><div class="row"><input id="memberEmail" type="email" placeholder="email@empresa.com.br" style="flex:1"><button data-fx="add-member">Adicionar</button></div>`:''}</div></div>`}

async function runSync(id){const [from,to]=syncRange();integ.busy[id]=true;integ.progress[id]='Iniciando…';render();let cursor=null,total={orders:0,receipts:0,ledger:0},round_=0,notes=[];
 try{do{const r=await callFn('integrations',{action:'sync',provider:id,from,to,cursor});cursor=r.next;for(const k in total)total[k]+=r.saved?.[k]||0;notes=r.notes||notes;integ.progress[id]=`${cursor?'Continuando… ':''}${total.orders} pedidos · ${total.receipts} repasses${total.ledger?` · ${total.ledger} contas`:''}`;if(page==='integracoes')render()}while(cursor&&++round_<60);
  audit('Sincronização '+PROVIDERS.find(p=>p.id===id).label,`${from} a ${to}: ${total.orders} pedidos, ${total.receipts} repasses, ${total.ledger} contas.`);
  integ.progress[id]=`Concluído: ${total.orders} pedidos · ${total.receipts} repasses${total.ledger?` · ${total.ledger} contas`:''}${notes.length?' · '+notes.join(' '):''}`;
 }catch(e){integ.progress[id]='Falhou: '+e.message;toast(e.message)}
 finally{integ.busy[id]=false;await Cloud.reload();await loadIntegrations()}}

// ───────── Conciliação em lote (correspondências exatas) ─────────
function exactPairs(){const out=[];for(const o of scoped()){if(status(o)==='Conciliado'||db.closures[o.date.slice(0,7)])continue;const rs=db.receipts.filter(r=>!r.linkedOrder&&r.orderId===o.id&&r.platform===o.platform&&!db.closures[r.date.slice(0,7)]);if(!rs.length)continue;const sum=round(rs.reduce((a,r)=>a+r.amount,0)),open=round(net(o)-paid(o));if(Math.abs(sum-open)<.01)for(const r of rs)out.push({receipt:r.id,order:o.id,amount:r.amount,reason:rs.length>1?`${rs.length} liberações somam o saldo`:'Pedido idêntico e valor exato'})}return out}
// Aplica vínculos já revisados. Usado pela conciliação em lote e pelas propostas do assistente.
window.applyLinks=function(pairs,origin){let ok=0,skipped=[];for(const p of pairs){const r=db.receipts.find(x=>x.id===p.receipt),o=db.orders.find(x=>x.id===p.order);if(!r||!o){skipped.push(`${p.receipt}: não encontrado`);continue}if(r.linkedOrder){skipped.push(`${r.id}: já vinculada`);continue}if(db.closures[o.date.slice(0,7)]||db.closures[r.date.slice(0,7)]){skipped.push(`${r.id}: competência fechada`);continue}r.linkedOrder=o.id;ok++;db.audit.unshift({id:uid(),time:new Date().toISOString(),action:'Vínculo confirmado',detail:`${r.id} → ${o.id} · ${money(r.amount)} · ${origin}${p.reason?' · '+p.reason:''}`})}paymentIndex=null;save();render();return {ok,skipped}};
let batch=[];
function batchModal(pairs,title,origin){batch=pairs;modal(title,pairs.length?`<div class="notice">Revise antes de confirmar. Cada vínculo fica registrado na auditoria e pode ser desfeito no pedido.</div><div class="tablewrap" style="max-height:48vh"><table><thead><tr><th><input type="checkbox" class="check" id="batchAll" checked aria-label="Selecionar todos"></th><th>Liberação</th><th>Pedido</th><th class="num">Valor</th><th>Critério</th></tr></thead><tbody>${pairs.map((p,i)=>`<tr><td><input type="checkbox" class="check" data-batch="${i}" checked></td><td>${esc(p.receipt)}</td><td>${esc(p.order)}</td><td class="num">${money(p.amount??db.receipts.find(r=>r.id===p.receipt)?.amount??0)}</td><td class="caption">${esc(p.reason||'')}</td></tr>`).join('')}</tbody></table></div><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fx-batch-confirm="${esc(origin)}">${icon('check')} Confirmar selecionados</button></div>`:'<div class="empty">Nenhuma correspondência exata pendente nesta competência.</div>')}
window.batchModal=batchModal;
const central0=central;central=function(){return central0().replace('<button class="primary small" data-action="matching">',`<button class="small" data-fx="auto-exact">${icon('bolt')} Conciliar exatos em lote</button><button class="primary small" data-action="matching">`)};

// ───────── Navegação, páginas e decoração ─────────
navItems.splice(navItems.findIndex(n=>n[0]==='imports')+1,0,['integracoes','plug','Integrações']);
navItems.splice(navItems.findIndex(n=>n[0]==='closing'),0,['fluxo','cash','Entradas e saídas']);
navItems.splice(navItems.findIndex(n=>n[0]==='reports'),0,['produtos','box','Produtos'],['estados','pin','Estados'],['clientes','users','Clientes · CRM']);
const pages={integracoes:[integrationsView,'Conecte ERP e marketplaces. Os dados chegam sozinhos, você confirma o que importa.'],fluxo:[flowView,'Contas a receber e a pagar do ERP lado a lado com os repasses.'],produtos:[productsView,'O que mais vende, onde e quanto representa.'],estados:[statesView,'Para onde a operação vende — por receita, pedidos e ticket.'],clientes:[crmView,'Quem compra, quem voltou, quem precisa de atenção.']};
const subtitle0=subtitle;subtitle=function(){return pages[page]?.[1]||subtitle0()};
const known=()=>new Set([...navItems.map(n=>n[0]),...Object.keys(platforms)]);
const navigate0=navigate;navigate=function(p){Object.assign(fx,{search:'',segment:'',stage:'',sort:'',kind:''});navigate0(p);try{history.replaceState(null,'','#'+encodeURIComponent(p))}catch{}};
const render0=render;
render=function(){if(!known().has(page))page='dashboard';if(pages[page]){paymentIndex=null;shell();$('#view').innerHTML=pages[page][0]();bindFilters();bindFx()}else{render0();bindFx()}decorate()};

function dashboardExtras(){const rows=scoped(),prods=productRank(rows).sort((a,b)=>b.revenue-a.revenue).slice(0,5),ufs=stateRank(rows).filter(s=>s.uf!=='—').slice(0,5),cs=customers();if(!prods.length&&!ufs.length&&!cs.length)return '';
 return `<div class="cardhead" style="margin-top:6px"><h2>Inteligência comercial</h2><span class="caption">Competência selecionada</span></div><div class="grid three" style="margin-bottom:22px"><div class="card"><div class="cardhead"><h2>Produtos mais vendidos</h2><button class="quiet small" data-nav="produtos">${icon('arrow')}</button></div>${prods.length?hbars(prods,p=>p.title,p=>p.revenue):'<p class="caption">Sem itens nos pedidos.</p>'}</div><div class="card"><div class="cardhead"><h2>Principais estados</h2><button class="quiet small" data-nav="estados">${icon('arrow')}</button></div>${ufs.length?hbars(ufs,s=>s.uf,s=>s.gross):'<p class="caption">Sem UF nos pedidos.</p>'}</div><div class="card"><div class="cardhead"><h2>Clientes</h2><button class="quiet small" data-nav="clientes">${icon('arrow')}</button></div>${SEGMENTS.map(s=>{const n=cs.filter(c=>c.segment===s).length;return `<div class="listline"><span class="badge ${segTone[s]}">${s}</span><strong>${num0(n)}</strong></div>`}).join('')}</div></div>`}

function decorate(){const cloud=window.Cloud?.enabled&&Cloud.ws;
 const demo=$('header .demo');if(demo){if(cloud){demo.outerHTML=`<span id="cloudStatus" class="badge"></span><button class="quiet small" data-cloud="reload" title="Recarregar dados da nuvem" aria-label="Recarregar dados">${icon('refresh')}</button>`;Cloud.paintStatus()}else demo.textContent='MODO LOCAL'}
 const email=window.Cloud?.session?.user?.email||'';$$('.avatar').forEach(a=>{if(email){a.textContent=email.slice(0,2).toUpperCase();a.title=email}});
 const hdrAvatar=$('header .row:last-child .avatar');if(cloud&&hdrAvatar)hdrAvatar.insertAdjacentHTML('afterend',`<button class="quiet small" data-cloud="logout" title="Sair" aria-label="Sair">${icon('logout')}</button>`);
 const bottom=$('.asidebottom .row div');if(bottom&&cloud)bottom.innerHTML=`${esc(Cloud.wsName)}<br><span style="font-size:10px">${esc(email)}</span>`;
 const foot=$('.footer span');if(foot&&cloud)foot.textContent='CONCIL-IA / Dados na nuvem · Integrações via API oficial das plataformas';
 if(cloud)$$('.caption').forEach(c=>{if(c.textContent==='Importação manual · sem conexão com APIs')c.textContent='API oficial + importação de relatórios'});
 if(page==='dashboard'&&db.orders.length){const anchor=$('#view .grid.platformgrid');if(anchor)anchor.insertAdjacentHTML('afterend',dashboardExtras())}
 window.Assistant?.sync();const ai=$('nav button[data-nav="ai"] .navbadge');if(ai)ai.textContent=window.Cloud?.enabled?'IA':'REGRAS';
}

function bindFx(){const on=(id,k,rerender=true)=>{const el=$('#'+id);if(el)el[el.tagName==='INPUT'&&el.type==='search'?'oninput':'onchange']=e=>{fx[k]=e.target.value;if(rerender){const pos=e.target.selectionStart;render();const again=$('#'+id);if(again&&e.target.type==='search'){again.focus();try{again.setSelectionRange(pos,pos)}catch{}}}}};
 on('fxPeriod','period');on('fxPlatform','platform');on('fxSearch','search');on('fxSegment','segment');on('fxStage','stage');on('fxSort','sort');on('fxKind','kind');on('fxSyncRange','syncRange');
 $$('[data-fx-loja]').forEach(s=>s.onchange=async()=>{const id=s.dataset.fxLoja,v=s.value;if(!v)return;const row=integ.rows.bling||{},settings={...(row.settings||{})};settings.lojas={...(settings.lojas||{}),[id]:v};const pend={...(settings.lojasPendentes||{})};delete pend[id];settings.lojasPendentes=pend;const {error}=await Cloud.client.from('integrations').update({settings}).eq('workspace_id',Cloud.ws).eq('provider','bling');if(error)return toast(error.message);row.settings=settings;toast(`Loja ${id} associada a ${v}. Sincronize o Bling novamente.`);render()});
 $('#batchAll')?.addEventListener('change',e=>$$('[data-batch]').forEach(c=>c.checked=e.target.checked));
}

function exportRows(name,rows){download(`CONCIL-IA_${name}_${fx.period==='mes'?month:fx.period}.csv`,csv(rows));toast('Arquivo CSV gerado.')}
const customerCsv=list=>[['cliente','documento','email','telefone','cidade','uf','segmento','estagio','etiquetas','compras','total','ticket','primeira_compra','ultima_compra','dias_sem_comprar'],...list.map(c=>[c.name,c.doc,c.email,c.phone,c.city,c.state,c.segment,c.crm.stage,c.crm.tags.join(', '),c.count,c.total,c.ticket,c.first,c.last,c.recency])];

document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
 if(d.fxSeg){fx.segment=fx.segment===d.fxSeg?'':d.fxSeg;render();return}
 if(d.fxCustomer){customerModal(d.fxCustomer);return}
 if(d.fxExportSeg){exportRows('clientes_'+d.fxExportSeg,customerCsv(customers().filter(c=>c.segment===d.fxExportSeg)));return}
 if(d.fxSaveCustomer||d.fxDone){const key=d.fxSaveCustomer||d.key,c=db.crm[key]=JSON.parse(JSON.stringify(db.crm[key]||{stage:'Novo',tags:[],notes:'',interactions:[]}));
  if(d.fxDone){c.interactions[Number(d.fxDone)].done=true;save();customerModal(key);return}
  c.stage=$('#crmStage').value;c.tags=$('#crmTags').value.split(',').map(s=>s.trim()).filter(Boolean);c.notes=$('#crmNotes').value;const text=$('#crmText').value.trim();if(text)c.interactions.unshift({time:new Date().toISOString(),type:$('#crmType').value,text,due:$('#crmDue').value||null,done:false});
  audit('Cliente atualizado',`${key}: estágio ${c.stage}${text?' · novo registro':''}`);closeModal();render();toast('Cliente salvo.');return}
 if(d.fxConnect){try{b.disabled=true;const r=await callFn('integrations',{action:'authorize',provider:d.fxConnect,return_url:location.origin+location.pathname});location.href=r.url}catch(err){toast(err.message);b.disabled=false}return}
 if(d.fxDisconnect){modal('Desconectar',`<p>Remover o acesso do CONCIL-IA a ${esc(d.fxDisconnect)}? Os dados já sincronizados permanecem.</p><div class="modalfoot"><button data-action="close">Cancelar</button><button class="primary" data-fx-disconnect-ok="${esc(d.fxDisconnect)}">Desconectar</button></div>`);return}
 if(d.fxDisconnectOk){try{await callFn('integrations',{action:'disconnect',provider:d.fxDisconnectOk});audit('Integração desconectada',d.fxDisconnectOk);closeModal();loadIntegrations()}catch(err){toast(err.message)}return}
 if(d.fxSync){runSync(d.fxSync);return}
 if(d.fxSample){modal('Amostra do último registro recebido',`<p class="caption">Use para conferir o formato que a plataforma devolve. Não contém tokens.</p><pre class="sample">${esc(JSON.stringify(integ.rows[d.fxSample]?.settings?.amostra,null,2))}</pre>`);return}
 if(d.fxBatchConfirm){const sel=$$('[data-batch]').filter(c=>c.checked).map(c=>batch[Number(c.dataset.batch)]);if(!sel.length)return toast('Selecione ao menos um vínculo.');const r=applyLinks(sel,d.fxBatchConfirm);closeModal();toast(`${r.ok} vínculos confirmados${r.skipped.length?` · ${r.skipped.length} ignorados`:''}.`);window.Assistant?.onLinksApplied?.(sel,r);return}
 switch(d.fx){
  case'auto-exact':batchModal(exactPairs(),'Conciliar correspondências exatas','conciliação em lote');break;
  case'sync-all':for(const id of ['bling','mercadolivre','shopee','magalu']){const row=integ.rows[id];if(row&&(row.status==='conectado'||row.status==='erro'))await runSync(id)}break;
  case'add-member':{const email=$('#memberEmail').value.trim();if(!email)return;const {data,error}=await Cloud.client.rpc('add_member',{ws:Cloud.ws,member_email:email});toast(error?error.message:data);loadIntegrations();break}
  case'export-products':exportRows('produtos',[['posicao','produto','sku','unidades','pedidos','receita','participacao_%','canais'],...productRank(periodRows()).sort((a,b)=>b.revenue-a.revenue).map((p,i)=>[i+1,p.title,p.sku,p.qty,p.orders,p.revenue,round(p.share),p.platforms.join(', ')])]);break;
  case'export-states':exportRows('estados',[['uf','pedidos','receita_bruta','ticket_medio','participacao_%'],...stateRank(periodRows()).map(s=>[s.uf,s.orders,s.gross,s.ticket,round(s.share)])]);break;
  case'export-customers':exportRows('clientes',customerCsv(customers()));break;
  case'export-ledger':exportRows('entradas_saidas',[['tipo','vencimento','pagamento','contato','categoria','descricao','status','valor','origem'],...ledgerFor().map(l=>[l.kind,l.due,l.paidDate,l.contact,l.category,l.description,l.status,l.amount,l.source])]);break;
 }
});

// Retorno do OAuth (#integracoes?ok=bling ou ?erro=…)
const [h,qs]=location.hash.slice(1).split('?');
if(h){page=decodeURIComponent(h);if(qs){const q=new URLSearchParams(qs);setTimeout(()=>toast(q.get('ok')?`${PROVIDERS.find(p=>p.id===q.get('ok'))?.label||q.get('ok')} conectado. Clique em Sincronizar.`:'Não foi possível conectar: '+(q.get('erro')||'erro desconhecido')),600);history.replaceState(null,'','#'+h)}}
render();
})();
