'use strict';
// Parametrização fiscal e contábil — a tela da contabilidade. Cada seção nasce SUGERIDA (pelo que o Bling
// pratica hoje, lido do XML das notas autorizadas, e pela legislação de uma empresa de Timbó/SC que vende
// para todo o Brasil), é ajustável e tem APROVAÇÃO registrada (quem, quando). Inclui um simulador de nota
// que calcula ICMS, DIFAL, FCP, PIS e COFINS exatamente como o emissor do EcomBalance.
(()=>{
Object.assign(paths,{sliders:'M4 6h10 M18 6h2 M4 12h4 M12 12h8 M4 18h12 M20 18h0 M14 4v4 M8 10v4 M16 16v4'});
const UFS=['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MG','MS','MT','PA','PB','PE','PI','PR','RJ','RN','RO','RR','RS','SC','SE','SP','TO'];
const NOME_UF={AC:'Acre',AL:'Alagoas',AM:'Amazonas',AP:'Amapá',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MG:'Minas Gerais',MS:'Mato Grosso do Sul',MT:'Mato Grosso',PA:'Pará',PB:'Paraíba',PE:'Pernambuco',PI:'Piauí',PR:'Paraná',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RO:'Rondônia',RR:'Roraima',RS:'Rio Grande do Sul',SC:'Santa Catarina',SE:'Sergipe',SP:'São Paulo',TO:'Tocantins'};
const ALIQ_INTERNA={AC:19,AL:19,AM:20,AP:18,BA:20.5,CE:20,DF:20,ES:17,GO:19,MA:23,MG:18,MS:17,MT:17,PA:19,PB:20,PE:20.5,PI:22.5,PR:19.5,RJ:20,RN:20,RO:19.5,RR:20,RS:17,SC:17,SE:19,SP:18,TO:20};
const INTER_7=new Set(['AC','AL','AM','AP','BA','CE','DF','ES','GO','MA','MS','MT','PA','PB','PE','PI','RN','RO','RR','SE','TO']);
const IMPORTADO=new Set([1,2,3,8]);
const ORIGENS={0:'0 · Nacional',1:'1 · Importação direta',2:'2 · Importada adquirida no mercado interno',3:'3 · Nacional, conteúdo importado > 40%',4:'4 · Nacional, processos produtivos básicos',5:'5 · Nacional, conteúdo importado ≤ 40%',6:'6 · Importação direta sem similar (CAMEX)',7:'7 · Importada no mercado interno sem similar',8:'8 · Nacional, conteúdo importado > 70%'};
const PADRAO={ambiente:'homologacao',cnpj:'65193225000157',uf:'SC',municipio:'Timbó',crt:3,regime:'Lucro Presumido',serie:'2',natureza:'Venda de Mercadoria - NAO CONTRIBUINTE',natureza_contribuinte:'Venda de Mercadoria - CONTRIBUINTE',cfop_interno:'5102',cfop_interestadual:'6108',cfop_interestadual_contribuinte:'6102',cst_icms:'00',aliq_icms_interna:17,cst_pis:'01',aliq_pis:0.65,cst_cofins:'01',aliq_cofins:3,modalidade_frete:0,difal:true,origem_padrao:5,presenca:9,forma_pagamento:'20',ibpt_federal:17.1,ibpt_estadual:17,texto_difal:true,texto_adicional:'',pis_exclui_icms:true,ibs_cst:'000',ibs_cclass:'000001',aliq_cbs:0.9,aliq_ibs_uf:0.1,aliq_ibs_mun:0};
const PLAT_CNPJ={'Mercado Livre':'03007331000141','Shopee':'35635824000112','Magalu':'47960950000121'};
const SECOES=[['empresa','Empresa e regime'],['icms','ICMS, DIFAL e FCP por estado'],['federais','PIS, COFINS, IPI e IBS/CBS'],['nota','Dados da nota fiscal'],['intermed','Intermediadores (marketplaces)'],['produtos','Produtos: NCM e origem'],['contabil','Contábil']];
const ui={sec:'empresa',regras:null,prods:null,carregando:false,sim:{uf:'SP',valor:300,origem:5,frete:0,doc:'cpf'}};
const cfg=()=>({...PADRAO,...(db.gerencial?.fiscal||{})});
const salvarCfg=(novo,msg)=>{db.gerencial={...(db.gerencial||{}),fiscal:{...(db.gerencial?.fiscal||{}),...novo}};save();if(msg)toast(msg)};
const pct=v=>v==null||v===''?'—':String(v).replace('.',',')+'%';
async function carregar(){if(ui.carregando||!window.Cloud?.ws)return;ui.carregando=true;
 try{const [b,p]=await Promise.all([Cloud.client.from('integrations').select('settings').eq('workspace_id',Cloud.ws).eq('provider','bling').maybeSingle(),Cloud.client.from('produtos').select('id,nome,ncm,cest,origem,gtin,saldo,ignorar').eq('workspace_id',Cloud.ws).limit(5000)]);
  ui.regras=b.data?.settings?.regras_fiscais||{};ui.prods=p.data||[]}catch{ui.regras={};ui.prods=[]}finally{ui.carregando=false}if(page==='parametros')render()}

// ─────────── Regras por UF: salvas > Bling > tabela ───────────
function regraUF(uf){const c=cfg(),s=c.por_uf?.[uf]||{},b=ui.regras?.por_uf?.[uf]||{};
 const interna=s.interna??(b.pICMSUFDest!=null?Number(b.pICMSUFDest):ALIQ_INTERNA[uf]),fcp=s.fcp??(b.pFCPUFDest!=null?Number(b.pFCPUFDest):({AL:1,RJ:2}[uf]||0));
 return {interna,fcp,difal:s.difal??c.difal,inter:uf===c.uf?c.aliq_icms_interna:(INTER_7.has(uf)?7:12),bling:b,salvo:s}}
function calcular({uf,valor,origem,frete,doc}){const c=cfg(),interno=uf===c.uf,r=regraUF(uf),base=Number(valor)+Number(frete||0);
 const inter=interno?c.aliq_icms_interna:(IMPORTADO.has(Number(origem))?4:r.inter),icms=base*inter/100,difal=!interno&&r.difal&&doc!=='cnpj'?base*Math.max(0,r.interna-inter)/100:0,fcp=!interno&&r.difal&&doc!=='cnpj'?base*r.fcp/100:0;
 const bp=c.pis_exclui_icms?base-icms-difal-fcp:base,pis=bp*c.aliq_pis/100,cofins=bp*c.aliq_cofins/100,bi=bp-pis-cofins,cbs=bi*c.aliq_cbs/100,ibs=bi*(c.aliq_ibs_uf+c.aliq_ibs_mun)/100;
 return {bp,bi,cbs,ibs,cfop:interno?c.cfop_interno:(doc==='cnpj'?c.cfop_interestadual_contribuinte:c.cfop_interestadual),base,inter,icms,difal,fcp,pis,cofins,total:icms+difal+fcp+pis+cofins+cbs+ibs,interna:r.interna,fcpP:r.fcp}}

// ─────────── Sugestões inteligentes ───────────
function sugestoes(){const c=cfg(),g=ui.regras?.geral||{},out=[],prods=ui.prods||[];
 const add=(tom,t,s,acao)=>out.push({tom,t,s,acao});
 if(g.crt)add(String(g.crt)===String(c.crt)?'ok':'warn','Regime do emitente',`As notas do Bling saem com CRT ${g.crt} (regime normal). Com PIS ${pct(g.pis_p)} e COFINS ${pct(g.cofins_p)} cumulativos, o enquadramento é Lucro Presumido.`);
 const imp=prods.filter(p=>IMPORTADO.has(Number(p.origem)));
 add(imp.length?'warn':'info','ICMS interestadual de 4% (Res. SF 13/2012)',imp.length?`${imp.length} produto(s) com origem 1, 2, 3 ou 8 pagam 4% nas vendas para outros estados — o emissor aplica sozinho pela origem do produto: ${imp.slice(0,4).map(p=>esc(p.nome)).join(', ')}${imp.length>4?'…':''}.`:'Nenhum produto com origem de importação acima de 40% no cadastro.');
 add('info','DIFAL para consumidor final (EC 87/2015 e LC 190/2022)',`Venda a não contribuinte fora de SC: ICMS interestadual para SC e a diferença até a alíquota interna do destino (mais FCP onde houver) para o estado do comprador. O Bling destacou DIFAL em ${g.com_difal??'—'} itens nas notas lidas.`);
 const fcps=UFS.filter(uf=>regraUF(uf).fcp>0);add('info','Fundo de Combate à Pobreza',`FCP no destino em: ${fcps.map(uf=>`${uf} ${pct(regraUF(uf).fcp)}`).join(', ')||'nenhum'}. Confira se algum estado passou a exigir FCP e ainda não está marcado.`);
 add('warn','Base do DIFAL: única × dupla',`Alguns estados exigem a base "dupla" (cálculo por dentro com a alíquota interna do destino). O emissor usa base única, como o Bling faz hoje. Marque na tabela de estados os que a contabilidade indicar como base dupla.`);
 const semNcm=prods.filter(p=>!p.ncm&&!p.ignorar);if(semNcm.length)add('bad','Produtos sem NCM',`${semNcm.length} produto(s) sem NCM não podem ter nota emitida. O servidor lê o NCM do Bling a cada hora; os que continuarem sem NCM precisam ser cadastrados no Bling.`,'produtos');
 const ids=Object.entries(PLAT_CNPJ).filter(([p,cn])=>!(c.intermediadores?.[p]?.id||ui.regras?.intermediadores?.[cn]));if(ids.length)add('warn','Identificador da loja nos marketplaces',`Falta o identificador de ${ids.map(x=>x[0]).join(', ')} (obrigatório na NF-e com intermediador, NT 2020.006).`,'intermed');
 add('info','Lei da Transparência (Lei 12.741/2012)',`A nota informa o total aproximado de tributos (IBPT): hoje ${pct(c.ibpt_federal)} federais + ${pct(c.ibpt_estadual)} estaduais, como no Bling. O ideal é usar a tabela IBPT por NCM — posso importar o arquivo do IBPT quando a contabilidade enviar.`);
 add('info','Reforma Tributária em 2026 (ano-teste)',`Toda NF-e precisa do grupo IBS/CBS: CST ${esc(c.ibs_cst)}, classificação ${esc(c.ibs_cclass)}, CBS ${pct(c.aliq_cbs)} e IBS ${pct(c.aliq_ibs_uf)} — igual às notas do Bling. A partir de 2027 a CBS substitui PIS/COFINS; o EcomBalance já calcula as duas bases.`);
 add('info','Série própria',`O EcomBalance emite na série ${esc(c.serie)}; o Bling usa a série ${esc(g.serie||'1')}. Numerações independentes, sem colisão durante a transição.`);
 add('info','Venda a contribuinte (CNPJ com IE)',`Para empresas com inscrição estadual o CFOP muda para ${esc(c.cfop_interestadual_contribuinte)} e não há DIFAL na nota (o destinatário recolhe). A natureza "${esc(c.natureza_contribuinte)}" já existe no Bling.`);
 return out}

// ─────────── Seções ───────────
const campo=(k,t,extra='')=>{const c=cfg();return `<div class="field"><label>${t}</label><input data-pf="${k}" value="${esc(c[k]??'')}" ${extra}></div>`};
function aprovacao(sec){const a=cfg().aprovacoes?.[sec];return `<div class="aprov ${a?'ok':''}">${a?`${icon('check')} Aprovado por <strong>${esc(a.por)}</strong> em ${new Date(a.em).toLocaleString('pt-BR')}${a.obs?` · ${esc(a.obs)}`:''} <button class="small quiet" data-pf-reabrir="${sec}">Reabrir</button>`:`${icon('alert')} Aguardando aprovação da contabilidade <button class="small primary" data-pf-aprovar="${sec}">${icon('check')} Aprovar esta seção</button>`}</div>`}
function secEmpresa(){const c=cfg(),g=ui.regras?.geral||{};return `<div class="grid three">${campo('cnpj','CNPJ')}${campo('ie','Inscrição estadual')}${campo('razao','Razão social')}${campo('municipio','Município')}${campo('uf','UF')}${campo('cnae','CNAE principal')}
 <div class="field"><label>Regime tributário</label><select data-pf="regime">${['Lucro Presumido','Lucro Real','Simples Nacional'].map(r=>`<option ${c.regime===r?'selected':''}>${r}</option>`).join('')}</select></div>
 <div class="field"><label>CRT na nota</label><select data-pf="crt">${[[1,'1 · Simples Nacional'],[2,'2 · Simples, excesso de sublimite'],[3,'3 · Regime normal']].map(([v,t])=>`<option value="${v}" ${Number(c.crt)===v?'selected':''}>${t}</option>`).join('')}</select><small class="caption">Bling hoje: ${esc(g.crt||'—')}</small></div></div>
 <div class="row"><button class="small" data-pf-receita="1">${icon('refresh')} Preencher pela Receita Federal (CNPJá)</button></div>`}
function secIcms(){const c=cfg();return `<div class="grid three">${campo('cfop_interno','CFOP dentro de SC')}${campo('cfop_interestadual','CFOP outros estados · não contribuinte')}${campo('cfop_interestadual_contribuinte','CFOP outros estados · contribuinte')}${campo('cst_icms','CST ICMS')}${campo('aliq_icms_interna','ICMS interno SC (%)')}
 <div class="field"><label>DIFAL</label><label class="check-l" style="margin:8px 0 0"><input type="checkbox" class="check" data-pf-bool="difal" ${c.difal?'checked':''}> Calcular para não contribuinte</label></div></div>
 <div class="tablewrap" style="margin-top:12px"><table class="uftable"><thead><tr><th>Estado</th><th class="num">Interestadual</th><th class="num">Interna destino</th><th class="num">FCP</th><th>DIFAL</th><th>Base dupla</th><th>Bling hoje</th></tr></thead><tbody>
 ${UFS.map(uf=>{const r=regraUF(uf),b=r.bling,dif=b.pICMSUFDest!=null&&(Number(b.pICMSUFDest)!==r.interna||Number(b.pFCPUFDest||0)!==r.fcp);return `<tr class="${uf===c.uf?'ctbgrupo':''}"><td><strong>${uf}</strong> <span class="caption">${NOME_UF[uf]}</span></td><td class="num">${uf===c.uf?pct(c.aliq_icms_interna)+' (interno)':`${pct(r.inter)} <span class="caption">· 4% importados</span>`}</td>
  <td class="num">${uf===c.uf?'—':`<input class="ufin" data-uf="${uf}" data-uf-campo="interna" value="${r.interna}" aria-label="Alíquota interna ${uf}">`}</td><td class="num">${uf===c.uf?'—':`<input class="ufin" data-uf="${uf}" data-uf-campo="fcp" value="${r.fcp}" aria-label="FCP ${uf}">`}</td>
  <td>${uf===c.uf?'—':`<input type="checkbox" class="check" data-uf="${uf}" data-uf-campo="difal" ${r.difal?'checked':''} aria-label="DIFAL ${uf}">`}</td><td>${uf===c.uf?'—':`<input type="checkbox" class="check" data-uf="${uf}" data-uf-campo="base_dupla" ${r.salvo.base_dupla?'checked':''} aria-label="Base dupla ${uf}">`}</td>
  <td class="caption">${b.notas?`${b.cfop} · inter ${pct(b.pICMSInter||b.pICMS)} · destino ${pct(b.pICMSUFDest)}${Number(b.pFCPUFDest)?` · FCP ${pct(b.pFCPUFDest)}`:''} <span class="${dif?'gold':'green'}">${dif?'≠':'='}</span>`:'sem nota lida'}</td></tr>`}).join('')}</tbody></table></div>
 <div class="row" style="margin-top:10px"><button class="small" data-pf-bling="icms">${icon('refresh')} Usar as alíquotas das notas do Bling</button><button class="small quiet" data-pf-lerbling="1">${icon('refresh')} Ler as notas do Bling de novo</button><span class="caption">${ui.regras?.notas_lidas?`${ui.regras.notas_lidas} notas lidas em ${new Date(ui.regras.em).toLocaleString('pt-BR')}`:''}</span></div>`}
function secFederais(){const g=ui.regras?.geral||{},c=cfg();return `<div class="grid three">${campo('cst_pis','CST PIS')}${campo('aliq_pis','PIS (%)')}${campo('cst_cofins','CST COFINS')}${campo('aliq_cofins','COFINS (%)')}${campo('cst_ipi','CST IPI (se contribuinte)')}${campo('enq_ipi','Enquadramento IPI')}
 <div class="field" style="grid-column:span 3"><label class="check-l" style="margin:0"><input type="checkbox" class="check" data-pf-bool="pis_exclui_icms" ${c.pis_exclui_icms?'checked':''}> Excluir o ICMS (e DIFAL/FCP) da base do PIS/COFINS — tese do século (RE 574.706), como o Bling faz</label></div></div>
 <h3 style="margin:16px 0 6px">Reforma Tributária · IBS e CBS (LC 214/2025)</h3><p class="caption">Em 2026 é o ano-teste: CBS 0,9% e IBS 0,1% destacados na nota, sem recolhimento (compensáveis com PIS/COFINS). Base = base do PIS/COFINS menos PIS e COFINS — conferido ao centavo com as notas do Bling.</p>
 <div class="grid three">${campo('ibs_cst','CST IBS/CBS')}${campo('ibs_cclass','Classificação tributária (cClassTrib)')}${campo('aliq_cbs','CBS (%)')}${campo('aliq_ibs_uf','IBS estadual (%)')}${campo('aliq_ibs_mun','IBS municipal (%)')}</div>
 <p class="caption">Bling hoje: PIS CST ${esc(g.pis_cst||'—')} ${pct(g.pis_p)} · COFINS CST ${esc(g.cofins_cst||'—')} ${pct(g.cofins_p)} · IPI ${g.ipi_cst?esc(g.ipi_cst):'não destacado (comércio)'} · IBS/CBS CST ${esc(g.ibs_cst||'—')} classificação ${esc(g.ibs_cclass||'—')} · CBS ${pct(g.p_cbs)} · IBS UF ${pct(g.p_ibs_uf)} · IBS mun ${pct(g.p_ibs_mun)}.</p>`}
function secNota(){const c=cfg(),g=ui.regras?.geral||{};return `<div class="grid three">${campo('serie','Série do EcomBalance')}${campo('natureza','Natureza · não contribuinte')}${campo('natureza_contribuinte','Natureza · contribuinte')}
 <div class="field"><label>Presença do comprador</label><select data-pf="presenca">${[[2,'2 · Internet'],[3,'3 · Teleatendimento'],[4,'4 · Entrega em domicílio'],[9,'9 · Não presencial, outros']].map(([v,t])=>`<option value="${v}" ${Number(c.presenca)===v?'selected':''}>${t}</option>`).join('')}</select><small class="caption">Bling: ${esc(g.indPres||'—')}</small></div>
 <div class="field"><label>Forma de pagamento (tPag)</label><select data-pf="forma_pagamento">${[['03','03 · Cartão de crédito'],['15','15 · Boleto'],['17','17 · PIX dinâmico'],['18','18 · Transferência/carteira digital'],['20','20 · PIX estático'],['99','99 · Outros']].map(([v,t])=>`<option value="${v}" ${String(c.forma_pagamento)===v?'selected':''}>${t}</option>`).join('')}</select><small class="caption">Bling: ${esc(g.tPag||'—')}</small></div>
 <div class="field"><label>Frete</label><select data-pf="modalidade_frete">${[[0,'0 · Por conta do emitente (CIF)'],[1,'1 · Destinatário (FOB)'],[9,'9 · Sem frete']].map(([v,t])=>`<option value="${v}" ${Number(c.modalidade_frete)===v?'selected':''}>${t}</option>`).join('')}</select><small class="caption">Bling: ${esc(g.modFrete||'—')}</small></div>
 ${campo('ibpt_federal','IBPT federal (%)')}${campo('ibpt_estadual','IBPT estadual (%)')}<div class="field"><label>Texto do DIFAL</label><label class="check-l" style="margin:8px 0 0"><input type="checkbox" class="check" data-pf-bool="texto_difal" ${c.texto_difal?'checked':''}> Informar o valor do DIFAL</label></div></div>
 <div class="field"><label>Texto adicional nas informações complementares</label><textarea data-pf="texto_adicional" rows="2">${esc(c.texto_adicional||'')}</textarea></div>
 <p class="caption">Exemplo do Bling: ${esc(String(g.infCpl||'').replace(/&lt;br \/&gt;/g,' · '))}</p>`}
function secIntermed(){const c=cfg(),rb=ui.regras?.intermediadores||{};return `<p class="caption">Venda em marketplace informa na nota o CNPJ do intermediador e o identificador da loja cadastrado nele (NT 2020.006).</p>
 <div class="tablewrap"><table><thead><tr><th>Marketplace</th><th>CNPJ do intermediador</th><th>Identificador da loja</th><th>Bling hoje</th></tr></thead><tbody>${Object.entries(PLAT_CNPJ).map(([p,cn])=>{const s=c.intermediadores?.[p]||{};return `<tr><td><strong>${p}</strong></td><td><input data-int="${esc(p)}" data-int-campo="cnpj" value="${esc(s.cnpj||cn)}"></td><td><input data-int="${esc(p)}" data-int-campo="id" value="${esc(s.id||rb[cn]||'')}" placeholder="${p==='Magalu'?'ainda sem nota lida':''}"></td><td class="caption">${rb[cn]?esc(rb[cn]):'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function secProdutos(){const l=ui.prods||[];if(!ui.prods)return '<p class="caption">Carregando…</p>';const sem=l.filter(p=>!p.ncm&&!p.ignorar),imp=l.filter(p=>IMPORTADO.has(Number(p.origem))),ori={};for(const p of l)ori[p.origem??'—']=(ori[p.origem??'—']||0)+1;
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">Produtos</span><span class="kpiv">${l.length}</span><span class="kpis">no cadastro</span></div><div class="card kpi"><span class="kpil">Sem NCM</span><span class="kpiv ${sem.length?'red':''}">${sem.length}</span><span class="kpis">não emitem nota</span></div><div class="card kpi"><span class="kpil">Importados (4%)</span><span class="kpiv">${imp.length}</span><span class="kpis">origem 1, 2, 3 ou 8</span></div><div class="card kpi"><span class="kpil">Origens</span><span class="kpiv" style="font-size:16px">${Object.entries(ori).map(([o,n])=>`${o}: ${n}`).join(' · ')}</span><span class="kpis">NCM e origem vêm do Bling</span></div></div>
 <div class="tablewrap" style="max-height:420px"><table><thead><tr><th>SKU</th><th>Produto</th><th>NCM</th><th>CEST</th><th>Origem</th><th>GTIN</th></tr></thead><tbody>${l.sort((a,b)=>(a.ncm?1:0)-(b.ncm?1:0)).map(p=>`<tr><td class="mono">${esc(p.id)}</td><td>${esc(p.nome)}</td><td class="mono ${p.ncm?'':'red'}">${esc(p.ncm||'faltando')}</td><td class="mono">${esc(p.cest||'')}</td><td>${p.origem!=null?`<span class="badge ${IMPORTADO.has(Number(p.origem))?'warn':''}">${esc(ORIGENS[p.origem]||p.origem)}</span>`:'—'}</td><td class="mono caption">${esc(p.gtin||'')}</td></tr>`).join('')}</tbody></table></div>
 <p class="caption">Correções de NCM e origem são feitas no cadastro do produto no Bling; o EcomBalance relê a cada hora (botão em Faturamento › Emissão para ler agora).</p>`}
function secContabil(){const c=db.gerencial?.contabil||{},plano=window.Contab?.plano?.()||[],mapa=window.Contab?.mapaCategorias?.()||{};
 return `<div class="grid three"><div class="field"><label>Tributos sobre vendas</label><select data-pc="provisao"><option value="1" ${c.provisao!==false?'selected':''}>Competência (provisão pela alíquota efetiva)</option><option value="0" ${c.provisao===false?'selected':''}>Caixa (quando pagar a guia)</option></select></div>
 <div class="field"><label>Alíquota efetiva fixa (%)</label><input data-pc="aliq_efetiva" value="${esc(c.aliq_efetiva??'')}" placeholder="vazio = usa o balancete de cada mês"></div><div class="field"><label>Plano de contas do escritório</label><input value="Mapeado em Resultado › DRE do escritório" disabled></div></div>
 <div class="tablewrap" style="max-height:420px;margin-top:10px"><table><thead><tr><th>Categoria do financeiro</th><th>Conta contábil (EcomBalance)</th></tr></thead><tbody>${Object.keys(mapa).sort().map(cat=>`<tr><td>${esc(cat)}</td><td><select data-pc-mapa="${esc(cat)}">${plano.filter(p=>p.c.split('.').length>=3).map(p=>`<option value="${p.c}" ${(c.mapa?.[cat]||mapa[cat])===p.c?'selected':''}>${p.c} · ${esc(p.n)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>
 <p class="caption">O mapeamento vale para a contabilidade automática (diário, balancete, DRE). O diário exporta em CSV para o escritório em Resultado › Contabilidade automática.</p>`}

function simulador(){const s=ui.sim,r=calcular(s);return `<section class="card simcard"><div class="cardhead"><div><h2>${icon('spark')} Simulador de nota</h2><p class="caption">Mesmo cálculo do emissor. Mude e veja.</p></div></div>
 <div class="grid three"><div class="field"><label>Destino</label><select data-sim="uf">${UFS.map(u=>`<option ${s.uf===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="field"><label>Valor dos produtos</label><input data-sim="valor" value="${s.valor}"></div><div class="field"><label>Frete</label><input data-sim="frete" value="${s.frete}"></div>
 <div class="field" style="grid-column:span 2"><label>Origem do produto</label><select data-sim="origem">${Object.entries(ORIGENS).map(([v,t])=>`<option value="${v}" ${Number(s.origem)===Number(v)?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Comprador</label><select data-sim="doc"><option value="cpf" ${s.doc==='cpf'?'selected':''}>Consumidor (CPF)</option><option value="cnpj" ${s.doc==='cnpj'?'selected':''}>Empresa com IE</option></select></div></div>
 <div class="simres"><div><small>CFOP</small><strong>${r.cfop}</strong></div><div><small>ICMS ${pct(r.inter)}</small><strong>${money(r.icms)}</strong></div><div><small>DIFAL (${pct(Math.max(0,r.interna-r.inter))})</small><strong>${money(r.difal)}</strong></div><div><small>FCP ${pct(r.fcpP)}</small><strong>${money(r.fcp)}</strong></div><div><small>PIS + COFINS (base ${money(r.bp)})</small><strong>${money(r.pis+r.cofins)}</strong></div><div><small>IBS + CBS (base ${money(r.bi)})</small><strong>${money(r.ibs+r.cbs)}</strong></div><div class="simtot"><small>Tributos na nota</small><strong>${money(r.total)}</strong><small>${(r.total/(r.base||1)*100).toFixed(1).replace('.',',')}% do valor</small></div></div></section>`}

function view(){if(!window.Cloud?.ws)return '<div class="empty">Entre no portal.</div>';if(!ui.regras&&!ui.carregando)carregar();
 const c=cfg(),apr=SECOES.filter(([k])=>c.aprovacoes?.[k]).length,sug=sugestoes();
 const conteudo={empresa:secEmpresa,icms:secIcms,federais:secFederais,nota:secNota,intermed:secIntermed,produtos:secProdutos,contabil:secContabil}[ui.sec]();
 const boasVindas=window.Cloud?.role==='contador'&&apr<SECOES.length?`<section class="card welcome"><h2>${icon('spark')} Bem-vindo(a), contabilidade</h2><p class="caption">Este é o seu espaço no EcomBalance. As regras abaixo já vêm preenchidas com o que o Bling aplica hoje nas notas da Wolfach (lidas do XML de notas autorizadas) e com a legislação para uma empresa de Timbó/SC que vende para todo o Brasil. Sugestão de ordem:</p><ol class="atpassos"><li>Empresa e regime — confirme Lucro Presumido e o CRT.</li><li>ICMS, DIFAL e FCP por estado — confira alíquotas internas, FCP e marque base dupla onde couber. Use o simulador.</li><li>PIS, COFINS e IBS/CBS — exclusão do ICMS da base e o ano-teste de 2026.</li><li>Dados da nota e intermediadores.</li><li>Contábil — mapeamento das categorias para o plano de contas.</li></ol><p class="caption">Aprove cada seção quando estiver de acordo; cada aprovação fica registrada com seu nome e data. Você também tem acesso a Resultado (balancete e DRE automáticos, conferência com o seu balancete), Financeiro (leitura) e Relatórios.</p></section>`:'';
 return `${boasVindas}<div class="pfhero"><div><h2>Parametrização fiscal e contábil</h2><p class="caption">Wolfach E-commerce · Timbó/SC · vendas para todo o Brasil. Cada seção vem sugerida (regras que o Bling aplica hoje + legislação) e precisa da aprovação da contabilidade.</p></div>
  <div class="pfprog"><strong>${apr}/${SECOES.length}</strong><small>seções aprovadas</small><span class="bartrack"><i style="width:${apr/SECOES.length*100}%"></i></span></div></div>
 <div class="pfgrid"><nav class="card pfnav">${SECOES.map(([k,t])=>`<button class="${ui.sec===k?'active':''}" data-pf-sec="${k}">${c.aprovacoes?.[k]?`<span class="green">${icon('check')}</span>`:`<span class="gold">${icon('alert')}</span>`}<span>${t}</span></button>`).join('')}</nav>
 <div class="pfmain"><section class="card"><div class="cardhead"><h2>${SECOES.find(s=>s[0]===ui.sec)[1]}</h2><button class="small primary" data-pf-salvar="1">${icon('check')} Salvar</button></div>${conteudo}${aprovacao(ui.sec)}</section>
 ${['icms','federais','nota','empresa'].includes(ui.sec)?simulador():''}
 <section class="card"><div class="cardhead"><h2>${icon('spark')} Sugestões do EcomBalance</h2><span class="caption">baseadas nas notas do Bling, no cadastro e na legislação</span></div>${sug.map(s=>`<div class="tarefa"><span class="avico ${s.tom}">${icon(s.tom==='ok'?'check':s.tom==='bad'?'alert':'spark')}</span><div><strong>${s.t}</strong><small>${s.s}</small></div>${s.acao?`<button class="small" data-pf-sec="${s.acao}">Ver</button>`:''}</div>`).join('')}</section></div></div>`}

function coletar(){const novo={};$$('[data-pf]').forEach(i=>{const k=i.dataset.pf,v=i.value.trim();novo[k]=/^(aliq|ibpt|modalidade|presenca|crt)/.test(k)?Number(v.replace(',','.')):v});$$('[data-pf-bool]').forEach(i=>novo[i.dataset.pfBool]=i.checked);
 if($$('[data-uf]').length){const pu={...(cfg().por_uf||{})};$$('[data-uf]').forEach(i=>{const uf=i.dataset.uf,k=i.dataset.ufCampo;pu[uf]={...(pu[uf]||{}),[k]:i.type==='checkbox'?i.checked:Number(String(i.value).replace(',','.'))}});novo.por_uf=pu}
 if($$('[data-int]').length){const im={...(cfg().intermediadores||{})};$$('[data-int]').forEach(i=>{const p=i.dataset.int;im[p]={...(im[p]||{}),[i.dataset.intCampo]:i.value.trim()}});novo.intermediadores=im}
 if($$('[data-pc]').length||$$('[data-pc-mapa]').length){const cc={...(db.gerencial?.contabil||{})};$$('[data-pc]').forEach(i=>{cc[i.dataset.pc]=i.dataset.pc==='provisao'?i.value==='1':(i.value.trim()===''?null:Number(i.value.replace(',','.')))});const mp={...(cc.mapa||{})};$$('[data-pc-mapa]').forEach(i=>mp[i.dataset.pcMapa]=i.value);cc.mapa=mp;db.gerencial={...(db.gerencial||{}),contabil:cc}}
 return novo}
async function fn(action,body){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-pf-sec],[data-pf-salvar],[data-pf-aprovar],[data-pf-reabrir],[data-pf-bling],[data-pf-lerbling],[data-pf-receita]');if(!b)return;const d=b.dataset;
 if(d.pfSec){ui.sec=d.pfSec;render();return}
 if(d.pfSalvar){const n=coletar();salvarCfg(n,'Parametrização salva.');audit('Parametrização fiscal/contábil',`${ui.sec} salva`);render();return}
 if(d.pfAprovar){const obs=prompt('Observação da aprovação (opcional):')??'';const n=coletar();const quem=window.Cloud?.session?.user?.email||'—';salvarCfg({...n,aprovacoes:{...(cfg().aprovacoes||{}),[d.pfAprovar]:{por:quem,em:new Date().toISOString(),obs}}},'Seção aprovada.');audit('Parametrização aprovada',`${d.pfAprovar} por ${quem}${obs?' · '+obs:''}`);render();return}
 if(d.pfReabrir){const a={...(cfg().aprovacoes||{})};delete a[d.pfReabrir];salvarCfg({aprovacoes:a},'Seção reaberta.');audit('Parametrização reaberta',d.pfReabrir);render();return}
 if(d.pfBling){const pu={...(cfg().por_uf||{})};for(const [uf,r] of Object.entries(ui.regras?.por_uf||{})){if(r.pICMSUFDest==null)continue;pu[uf]={...(pu[uf]||{}),interna:Number(r.pICMSUFDest),fcp:Number(r.pFCPUFDest||0)}}salvarCfg({por_uf:pu},'Alíquotas das notas do Bling aplicadas.');render();return}
 if(d.pfLerbling){b.disabled=true;b.textContent='Lendo as notas do Bling…';try{ui.regras=await fn('fiscal_regras_bling',{});toast(`${ui.regras.notas_lidas} nota(s) lida(s).`)}catch(x){toast(x.message)}render();return}
 if(d.pfReceita){b.disabled=true;try{const r=await fn('cnpj',{cnpj:cfg().cnpj});salvarCfg({razao:r.razao,ie:String(r.ie||'').replace(/\D/g,''),municipio:r.cidade,uf:r.uf,cnae:r.atividade},'Dados da Receita preenchidos.')}catch(x){toast(x.message)}render();return}});
document.addEventListener('change',e=>{const s=e.target.closest('[data-sim]');if(s){ui.sim[s.dataset.sim]=s.dataset.sim==='uf'||s.dataset.sim==='doc'?s.value:Number(String(s.value).replace(',','.'))||0;render()}});
addPage('parametros','sliders','Parametrização fiscal e contábil',view,'Regras fiscais e contábeis sugeridas, simulador de nota e aprovação da contabilidade.','',()=>{});
})();
