'use strict';
// Venda direta (B2B, atacado, lojistas) e Contas a receber. A venda nasce como rascunho com o cliente
// preenchido pelo CNPJ (Receita/CNPJá), itens do cadastro, frete, desconto e parcelas; ao faturar emite a
// NF-e pelo EcomBalance (contribuinte: CFOP de revenda, sem DIFAL) e gera um título a receber por parcela.
(()=>{
Object.assign(paths,{handshake:'M3 12l4-4 4 3 3-3 7 7 M3 12l6 6 M14 11l3 3 M11 14l3 3',coins:'M8 8a5 3 0 1 0 10 0 5 3 0 1 0-10 0z M8 8v8c0 1.7 2.2 3 5 3s5-1.3 5-3V8 M8 12c0 1.7 2.2 3 5 3s5-1.3 5-3'});
const hoje=()=>new Date().toLocaleDateString('sv-SE');
const somaDias=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toLocaleDateString('sv-SE')};
const dBR=d=>d?new Date(String(d).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const dig=s=>String(s||'').replace(/\D/g,'');
const quem=()=>window.Cloud?.session?.user?.email||'—';
const st={vendas:null,rec:null,prods:null,aberta:null,filtroRec:'aberto'};
async function fn(action,body){const r=await Cloud.client.functions.invoke('integrations',{body:{workspace_id:Cloud.ws,action,...body}});if(r.error){let msg=r.error.message;try{msg=(await r.error.context.json()).error||msg}catch{}throw Error(msg)}return r.data}
async function carregar(){if(!window.Cloud?.ws)return;const [v,r,p]=await Promise.all([Cloud.client.from('vendas_diretas').select('*').eq('workspace_id',Cloud.ws).order('created_at',{ascending:false}).limit(300),Cloud.client.from('recebiveis').select('*').eq('workspace_id',Cloud.ws).order('vencimento').limit(2000),Cloud.client.from('produtos').select('id,nome,preco,custo,saldo,gtin,ncm').eq('workspace_id',Cloud.ws).limit(5000)]);
 st.vendas=v.data||[];st.rec=r.data||[];st.prods=p.data||[];if(['vendadireta','receber'].includes(page)&&!document.querySelector('.modalback'))render()}
const up=async(t,row)=>{const {error}=await Cloud.client.from(t).upsert({...row,workspace_id:Cloud.ws,updated_at:new Date().toISOString()},{onConflict:'workspace_id,id'});if(error)throw error};
const total=v=>Math.round(((v.itens||[]).reduce((s,i)=>s+Number(i.qtd||0)*Number(i.preco||0),0)+Number(v.frete||0)-Number(v.desconto||0))*100)/100;
const CONDICOES=[['0','À vista'],['30','30 dias'],['30/60','30/60'],['30/60/90','30/60/90'],['28/56/84','28/56/84']];
function gerarParcelas(v){const cond=v.condicao||'0',base=v.emissao||hoje(),dias=cond.split('/').map(Number),t=total(v),n=dias.length,val=Math.floor(t/n*100)/100;
 return dias.map((d,k)=>({n:k+1,vencimento:somaDias(base,d),valor:k===n-1?Math.round((t-val*(n-1))*100)/100:val}))}

// ─────────── Venda direta ───────────
const ST={rascunho:['Rascunho',''],faturado:['Faturada','ok'],cancelado:['Cancelada','']};
function vendasView(){if(!st.vendas){carregar();return '<div class="empty">Carregando…</div>'}
 const mes=st.vendas.filter(v=>v.status==='faturado'&&String(v.emissao||'').startsWith(month)),rasc=st.vendas.filter(v=>v.status==='rascunho');
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">Faturado no mês</span><span class="kpiv">${money(mes.reduce((s,v)=>s+Number(v.total||0),0))}</span><span class="kpis">${mes.length} venda(s)</span></div><div class="card kpi"><span class="kpil">Rascunhos</span><span class="kpiv">${rasc.length}</span><span class="kpis">${money(rasc.reduce((s,v)=>s+total(v),0))}</span></div><div class="card kpi"><span class="kpil">A receber de vendas diretas</span><span class="kpiv">${money((st.rec||[]).filter(r=>r.origem==='venda_direta'&&['aberto','parcial'].includes(r.status)).reduce((s,r)=>s+Number(r.valor)-Number(r.valor_recebido||0),0))}</span><span class="kpis"><button class="small quiet" data-nav="receber">Ver títulos</button></span></div><div class="card kpi"><span class="kpil">Clientes</span><span class="kpiv">${new Set(st.vendas.map(v=>dig(v.cliente?.doc))).size}</span><span class="kpis">atacado e lojistas</span></div></div>
 <div class="crmbar"><button class="primary small" data-vd="nova">${icon('plus')} Nova venda</button></div>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Nº</th><th>Cliente</th><th>Situação</th><th>Emissão</th><th>Condição</th><th class="num">Itens</th><th class="num">Total</th><th>Nota</th></tr></thead><tbody>
 ${st.vendas.map(v=>{const [t,tom]=ST[v.status]||[v.status,''];return `<tr class="clickrow" data-vd-abrir="${esc(v.id)}"><td class="mono">${v.numero||'—'}</td><td><strong>${esc(v.cliente?.fantasia||v.cliente?.nome||'—')}</strong><br><span class="caption">${esc(v.cliente?.doc||'')} · ${esc(v.cliente?.endereco?.municipio||'')}/${esc(v.cliente?.endereco?.uf||'')}</span></td><td><span class="badge ${tom}">${t}</span></td><td>${dBR(v.emissao)}</td><td>${esc((CONDICOES.find(c=>c[0]===v.condicao)||[0,v.condicao||'—'])[1])}</td><td class="num">${(v.itens||[]).length}</td><td class="num">${money(v.status==='rascunho'?total(v):v.total)}</td><td class="caption">${esc(v.nfe_ref||'—')}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">Nenhuma venda direta ainda.</td></tr>'}</tbody></table></div></div>`}
function abrir(id){const v=st.vendas.find(x=>x.id===id);if(!v)return;st.aberta=id;const ed=v.status==='rascunho',c=v.cliente||{},e=c.endereco||{},t=total(v),parc=ed||!v.parcelas?.length?gerarParcelas(v):v.parcelas;
 const inp=(k,lb,val,x='')=>`<div class="field" ${x}><label>${lb}</label><input data-vc="${k}" value="${esc(val??'')}" ${ed?'':'disabled'}></div>`;
 modal(`Venda direta ${v.numero?'nº '+v.numero:''}`,`<h3>Cliente</h3><div class="grid three"><div class="field"><label>CPF/CNPJ</label><div class="row"><input data-vc="doc" value="${esc(c.doc||'')}" ${ed?'':'disabled'} style="flex:1"><button class="small" data-vd-cnpj="1" ${ed?'':'disabled'}>Buscar</button></div></div>${inp('nome','Razão social / nome',c.nome,'style="grid-column:span 2"')}${inp('fantasia','Nome fantasia',c.fantasia)}${inp('ie','Inscrição estadual',c.ie)}${inp('email','E-mail (recebe a nota)',c.email)}
 ${inp('logradouro','Endereço',e.logradouro,'style="grid-column:span 2"')}${inp('numero','Número',e.numero)}${inp('bairro','Bairro',e.bairro)}${inp('municipio','Município',e.municipio)}${inp('uf','UF',e.uf)}${inp('cep','CEP',e.cep)}${inp('complemento','Complemento',e.complemento)}${inp('telefone','Telefone',c.telefone)}</div>
 <p class="caption">${dig(c.doc).length===14&&dig(c.ie)?'Contribuinte do ICMS: nota de revenda (CFOP 5102/6102), sem DIFAL.':dig(c.doc).length===14?'CNPJ sem inscrição estadual: tratado como não contribuinte (consumidor final, com DIFAL fora de SC).':'Consumidor final pessoa física.'}</p>
 <h3 style="margin-top:14px">Itens</h3><div class="tablewrap" style="max-height:260px"><table><thead><tr><th>Produto</th><th class="num">Qtd.</th><th class="num">Preço</th><th class="num">Total</th><th class="num">Saldo</th>${ed?'<th></th>':''}</tr></thead><tbody>${(v.itens||[]).map((i,k)=>{const p=st.prods.find(x=>x.id===i.sku);return `<tr><td>${esc(i.nome||i.sku)}<br><span class="caption mono">${esc(i.sku)}${p&&!p.ncm?' · <span class="red">sem NCM</span>':''}</span></td><td class="num">${ed?`<input class="ufin" data-vi="${k}" data-vi-c="qtd" value="${i.qtd}">`:i.qtd}</td><td class="num">${ed?`<input class="ufin" data-vi="${k}" data-vi-c="preco" value="${i.preco}">`:money(i.preco)}</td><td class="num">${money(i.qtd*i.preco)}</td><td class="num">${p?Number(p.saldo||0).toLocaleString('pt-BR'):'—'}</td>${ed?`<td><button class="small quiet" data-vd-tirar="${k}">${icon('x')}</button></td>`:''}</tr>`}).join('')||'<tr><td colspan="6" class="empty">Adicione produtos.</td></tr>'}</tbody></table></div>
 ${ed?`<div class="row" style="margin-top:8px"><input id="vdAdd" list="vdProds" placeholder="Produto: SKU, EAN ou nome" style="flex:1"><datalist id="vdProds">${st.prods.slice(0,500).map(p=>`<option value="${esc(p.id)}">${esc(p.nome)}</option>`).join('')}</datalist><input id="vdAddQ" type="number" value="1" min="1" style="width:80px"><button class="small" data-vd-add="1">Adicionar</button></div>`:''}
 <div class="grid three" style="margin-top:12px">${inp('frete','Frete (R$)',v.frete)}${inp('desconto','Desconto (R$)',v.desconto)}<div class="field"><label>Condição</label><select data-vc="condicao" ${ed?'':'disabled'}>${CONDICOES.map(([k,t])=>`<option value="${k}" ${v.condicao===k?'selected':''}>${t}</option>`).join('')}</select></div>
 <div class="field"><label>Forma de pagamento</label><select data-vc="forma_pagamento" ${ed?'':'disabled'}>${[['15','Boleto'],['17','PIX'],['03','Cartão de crédito'],['01','Dinheiro'],['99','Outros']].map(([k,t])=>`<option value="${k}" ${v.forma_pagamento===k?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>Emissão</label><input data-vc="emissao" type="date" value="${esc(v.emissao||hoje())}" ${ed?'':'disabled'}></div><div class="field"><label>Total</label><input value="${money(t)}" disabled></div></div>
 <p class="caption">Parcelas: ${parc.map(p=>`${dBR(p.vencimento)} ${money(p.valor)}`).join(' · ')}</p>
 <label>Observação</label><textarea data-vc="observacao" rows="2" ${ed?'':'disabled'}>${esc(v.observacao||'')}</textarea>
 <div class="modalfoot"><button data-action="close">Fechar</button>${ed?`<button class="quiet" data-vd-cancelar="1">Cancelar venda</button><button data-vd-salvar="1">${icon('check')} Salvar rascunho</button><button data-vd-semnota="1">Faturar sem nota</button><button class="primary" data-vd-faturar="1">${icon('receipt')} Faturar e emitir NF-e</button>`:''}</div>`)}
function lerModal(v){if(v.status!=='rascunho')return;const g=k=>$(`[data-vc="${k}"]`)?.value?.trim()??'';
 v.cliente={doc:g('doc'),nome:g('nome'),fantasia:g('fantasia'),ie:g('ie'),email:g('email'),telefone:g('telefone'),endereco:{logradouro:g('logradouro'),numero:g('numero'),complemento:g('complemento'),bairro:g('bairro'),municipio:g('municipio'),uf:g('uf').toUpperCase(),cep:g('cep')}};
 $$('[data-vi]').forEach(i=>{v.itens[Number(i.dataset.vi)][i.dataset.viC]=Number(String(i.value).replace(',','.'))||0});
 v.frete=Number(g('frete').replace(',','.'))||0;v.desconto=Number(g('desconto').replace(',','.'))||0;v.condicao=g('condicao');v.forma_pagamento=g('forma_pagamento');v.emissao=g('emissao')||hoje();v.observacao=g('observacao');v.total=total(v);v.parcelas=gerarParcelas(v)}
async function gerarTitulos(v,ref){for(const p of v.parcelas){await up('recebiveis',{id:`vd-${v.id}-${p.n}`,origem:'venda_direta',referencia:v.id,cliente:v.cliente.fantasia||v.cliente.nome,cliente_doc:v.cliente.doc,descricao:`Venda direta nº ${v.numero}`,documento:ref||null,parcela:p.n,parcelas:v.parcelas.length,emissao:v.emissao,vencimento:p.vencimento,valor:p.valor,valor_recebido:0,status:'aberto',categoria:'Venda direta'})}}

// ─────────── Contas a receber ───────────
function receberView(){if(!st.rec){carregar();return '<div class="empty">Carregando…</div>'}const h=hoje(),ab=st.rec.filter(r=>['aberto','parcial'].includes(r.status)),saldo=r=>Number(r.valor)-Number(r.valor_recebido||0);
 const venc=ab.filter(r=>r.vencimento<h),sem=ab.filter(r=>r.vencimento>=h&&r.vencimento<=somaDias(h,7));
 const l=st.rec.filter(r=>st.filtroRec==='todos'||(st.filtroRec==='aberto'?['aberto','parcial'].includes(r.status):st.filtroRec==='vencido'?['aberto','parcial'].includes(r.status)&&r.vencimento<h:r.status===st.filtroRec));
 return `<div class="grid kpis4"><div class="card kpi"><span class="kpil">A receber</span><span class="kpiv">${money(ab.reduce((s,r)=>s+saldo(r),0))}</span><span class="kpis">${ab.length} título(s)</span></div><div class="card kpi"><span class="kpil">Vencidos</span><span class="kpiv ${venc.length?'red':''}">${money(venc.reduce((s,r)=>s+saldo(r),0))}</span><span class="kpis">${venc.length} título(s)</span></div><div class="card kpi"><span class="kpil">Próximos 7 dias</span><span class="kpiv">${money(sem.reduce((s,r)=>s+saldo(r),0))}</span><span class="kpis">${sem.length} título(s)</span></div><div class="card kpi"><span class="kpil">Recebido no mês</span><span class="kpiv green">${money(st.rec.filter(r=>String(r.recebido_em||'').startsWith(month)).reduce((s,r)=>s+Number(r.valor_recebido||0),0))}</span><span class="kpis">baixas pelo extrato ou manuais</span></div></div>
 <div class="crmbar"><div class="segtabs">${[['aberto','Em aberto'],['vencido','Vencidos'],['recebido','Recebidos'],['todos','Todos']].map(([k,t])=>`<button class="${st.filtroRec===k?'active':''}" data-rc-f="${k}">${t}</button>`).join('')}</div><button class="small" data-rc="novo">${icon('plus')} Título manual</button></div>
 <p class="caption" style="margin:-6px 0 12px">Marketplaces ficam em Vendas › Conciliação; aqui estão vendas diretas e outros créditos. A conciliação bancária sugere a baixa quando o valor entra no extrato.</p>
 <div class="tablebox"><div class="tablewrap"><table><thead><tr><th>Vencimento</th><th>Cliente</th><th>Descrição</th><th>Parcela</th><th class="num">Valor</th><th class="num">Recebido</th><th>Situação</th><th></th></tr></thead><tbody>
 ${l.map(r=>`<tr><td class="${['aberto','parcial'].includes(r.status)&&r.vencimento<h?'red':''}">${dBR(r.vencimento)}</td><td><strong>${esc(r.cliente||'—')}</strong><br><span class="caption">${esc(r.cliente_doc||'')}</span></td><td>${esc(r.descricao||'')}${r.documento?`<br><span class="caption">${esc(r.documento)}</span>`:''}</td><td>${r.parcela}/${r.parcelas}</td><td class="num">${money(r.valor)}</td><td class="num">${money(r.valor_recebido||0)}</td><td><span class="badge ${r.status==='recebido'?'ok':r.vencimento<h&&r.status!=='cancelado'?'bad':r.status==='parcial'?'warn':''}">${r.status}</span></td><td>${['aberto','parcial'].includes(r.status)?`<button class="small" data-rc-baixar="${esc(r.id)}">Baixar</button>`:''}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Nada aqui.</td></tr>'}</tbody></table></div></div>`}

document.addEventListener('click',async e=>{const b=e.target.closest('[data-vd],[data-vd-abrir],[data-vd-cnpj],[data-vd-add],[data-vd-tirar],[data-vd-salvar],[data-vd-cancelar],[data-vd-faturar],[data-vd-semnota],[data-rc],[data-rc-f],[data-rc-baixar]');if(!b)return;const d=b.dataset;
 try{
 if(d.vd==='nova'){const numero=Math.max(0,...st.vendas.map(v=>v.numero||0))+1,v={id:'vd-'+uid(),numero,cliente:{endereco:{}},itens:[],frete:0,desconto:0,condicao:'30',forma_pagamento:'15',status:'rascunho',emissao:hoje(),criado_por:quem()};v.total=0;await up('vendas_diretas',v);st.vendas.unshift(v);abrir(v.id);return}
 if(d.vdAbrir){abrir(d.vdAbrir);return}
 if(d.rcF){st.filtroRec=d.rcF;render();return}
 if(d.rc==='novo'){const cliente=prompt('Cliente:');if(!cliente)return;const valor=Number(String(prompt('Valor (R$):')||'').replace(/\./g,'').replace(',','.'));if(!valor)return;const venc=prompt('Vencimento (AAAA-MM-DD):',somaDias(hoje(),30));const r={id:'rc-'+uid(),origem:'manual',cliente,descricao:prompt('Descrição:')||'Título a receber',parcela:1,parcelas:1,emissao:hoje(),vencimento:venc,valor,valor_recebido:0,status:'aberto',categoria:'Outras receitas'};await up('recebiveis',r);st.rec.push(r);audit('Título a receber',`${cliente} · ${money(valor)}`);render();return}
 if(d.rcBaixar){const r=st.rec.find(x=>x.id===d.rcBaixar),falta=Number(r.valor)-Number(r.valor_recebido||0);const v=Number(String(prompt(`Valor recebido (falta ${money(falta)}):`,falta.toFixed(2).replace('.',','))||'').replace(/\./g,'').replace(',','.'));if(!v)return;const data=prompt('Data do recebimento (AAAA-MM-DD):',hoje())||hoje();
  r.valor_recebido=Math.round((Number(r.valor_recebido||0)+v)*100)/100;r.recebido_em=data;r.status=r.valor_recebido>=Number(r.valor)-0.009?'recebido':'parcial';await up('recebiveis',r);audit('Baixa de título a receber',`${r.cliente} · ${money(v)} em ${dBR(data)}`);render();return}
 const v=st.vendas?.find(x=>x.id===st.aberta);if(!v)return;
 if(d.vdCnpj){lerModal(v);const doc=dig(v.cliente.doc);if(doc.length!==14)return toast('Informe um CNPJ com 14 dígitos (CPF não tem consulta).');b.disabled=true;const r=await fn('cnpj',{cnpj:doc});
  v.cliente={...v.cliente,doc:r.doc,nome:r.razao,fantasia:r.fantasia,ie:String(r.ie||'').replace(/\s*\(inativa\)/,''),email:v.cliente.email||r.email,telefone:v.cliente.telefone||r.telefone,endereco:{logradouro:r.endereco,numero:r.numero,complemento:r.complemento,bairro:r.bairro,municipio:r.cidade,uf:r.uf,cep:r.cep}};await up('vendas_diretas',v);abrir(v.id);toast(`${r.razao} · ${r.situacao||''}${r.regime?' · '+r.regime:''}`);return}
 if(d.vdAdd){lerModal(v);const c=$('#vdAdd').value.trim(),p=st.prods.find(x=>x.id===c||x.gtin===c)||st.prods.find(x=>normalized(x.nome).includes(normalized(c)));if(!p)return toast('Produto não encontrado.');v.itens.push({sku:p.id,nome:p.nome,qtd:Number($('#vdAddQ').value)||1,preco:Number(p.preco)||0});v.total=total(v);await up('vendas_diretas',v);abrir(v.id);return}
 if(d.vdTirar!==undefined){lerModal(v);v.itens.splice(Number(d.vdTirar),1);v.total=total(v);await up('vendas_diretas',v);abrir(v.id);return}
 if(d.vdSalvar){lerModal(v);await up('vendas_diretas',v);closeModal();toast('Rascunho salvo.');render();return}
 if(d.vdCancelar){if(!confirm('Cancelar esta venda?'))return;v.status='cancelado';await up('vendas_diretas',v);closeModal();render();return}
 const valida=()=>{if(!v.itens.length)throw Error('Adicione pelo menos um item.');if(!dig(v.cliente.doc))throw Error('Informe o CPF/CNPJ do cliente.');const e=v.cliente.endereco;if(!e.logradouro||!e.municipio||!e.uf||!dig(e.cep))throw Error('Endereço completo do cliente é obrigatório (rua, município, UF e CEP).')};
 if(d.vdSemnota){lerModal(v);valida();if(!confirm('Faturar sem emitir nota pelo EcomBalance (a nota foi ou será emitida em outro sistema)? Os títulos a receber serão gerados.'))return;const ref=prompt('Número da nota emitida em outro sistema (opcional):')||null;v.status='faturado';v.nfe_ref=ref;await up('vendas_diretas',v);await gerarTitulos(v,ref);audit('Venda direta faturada',`nº ${v.numero} · ${money(v.total)} · sem nota pelo EcomBalance`);closeModal();await carregar();toast('Venda faturada e títulos gerados.');return}
 if(d.vdFaturar){lerModal(v);valida();await up('vendas_diretas',v);const s=await fn('fiscal_status',{}),prod=s.config?.ambiente==='producao';
  if(!confirm(prod?`Emitir NF-e COM VALOR FISCAL de ${money(v.total)} para ${v.cliente.nome}?`:`Ambiente de TESTE: emitir nota de homologação (sem valor fiscal) para validar a venda nº ${v.numero}?`))return;b.disabled=true;b.textContent='Emitindo…';
  const r=await fn('fiscal_emitir_venda',{venda:v.id,producao:prod});if(r.status==='erro'){toast('Recusada: '+r.mensagem);b.disabled=false;b.textContent='Faturar e emitir NF-e';return}
  await new Promise(x=>setTimeout(x,5000));const c=await fn('fiscal_consultar',{ref:r.ref}).catch(()=>({}));
  if(c.status==='autorizado'){if(prod){v.status='faturado';await up('vendas_diretas',v);await gerarTitulos(v,`NF ${c.numero}/${c.serie}`)}audit('Venda direta — NF-e',`nº ${v.numero} · ${c.status} · ${prod?'produção':'homologação'}`);closeModal();await carregar();toast(prod?`NF-e ${c.numero} autorizada. Títulos gerados.`:`Nota de teste ${c.numero} autorizada — em produção a venda seria faturada.`);if(c.danfe_url)window.open(c.danfe_url,'_blank')}
  else{toast(`${c.status||r.status}: ${c.mensagem||r.mensagem||'consulte em Faturamento › Emissão'}`);closeModal();await carregar()}return}
 }catch(x){toast(x.message||String(x));b.disabled=false}});
addPage('vendadireta','handshake','Venda direta',vendasView,'Vendas para lojistas e atacado: cliente pelo CNPJ, itens, condições e NF-e emitida pelo EcomBalance.','',()=>{});
addPage('receber','coins','Contas a receber',receberView,'Títulos de vendas diretas e outros créditos, vencidos e a vencer, com baixa pelo extrato.','',()=>{});
async function baixar(id,valor,data,sinal=1){const r=(st.rec||[]).find(x=>x.id===id);if(!r)return;r.valor_recebido=Math.max(0,Math.round((Number(r.valor_recebido||0)+sinal*valor)*100)/100);r.recebido_em=sinal>0?data:(r.valor_recebido?r.recebido_em:null);r.status=r.valor_recebido>=Number(r.valor)-0.009?'recebido':r.valor_recebido>0?'parcial':'aberto';await up('recebiveis',r)}
window.VendaDireta={carregar,titulos:()=>st.rec||[],vendas:()=>st.vendas||[],baixar};
let wsVd=null;setInterval(()=>{if(window.Cloud?.ws&&Cloud.ws!==wsVd){wsVd=Cloud.ws;carregar()}},2500);
})();
